<?php

namespace AwardWallet\Engine\choice\Transfer;

use AwardWallet\Engine\ProxyList;

class Register extends \TAccountChecker
{
    use ProxyList;

    public static $titles = [
        'Mr'  => 'Mr',
        'Mrs' => 'Mrs',
        'Ms'  => 'Ms',
        'Dr'  => 'Dr',
    ];
    public static $addressTypes = [
        'H' => 'Home',
        'B' => 'Business',
    ];
    public static $countries = [
        'US' => 'United States',
        'CA' => 'Canada',
        'GB' => 'United Kingdom',
        'AF' => 'Afghanistan',
        'AL' => 'Albania',
        'DZ' => 'Algeria',
        'AD' => 'Andorra',
        'AO' => 'Angola',
        'AI' => 'Anguilla',
        'AG' => 'Antigua and Barbuda',
        'AM' => 'Armenia',
        'AW' => 'Aruba',
        'AU' => 'Australia',
        'AT' => 'Austria',
        'AZ' => 'Azerbaijan',
        'BS' => 'Bahamas',
        'BH' => 'Bahrain',
        'BB' => 'Barbados',
        'BE' => 'Belgium',
        'BZ' => 'Belize',
        'BJ' => 'Benin',
        'BM' => 'Bermuda',
        'BQ' => 'Bonaire, Sint Eustatius and Saba',
        'BA' => 'Bosnia and Herzegovina',
        'BW' => 'Botswana',
        'VG' => 'British Virgin Islands',
        'BG' => 'Bulgaria',
        'BF' => 'Burkina Faso',
        'BI' => 'Burundi',
        'CM' => 'Cameroon',
        'CV' => 'Cape Verde',
        'KY' => 'Cayman Islands',
        'CF' => 'Central African Republic',
        'TD' => 'Chad',
        'KM' => 'Comoros',
        'CG' => 'Congo',
        'CR' => 'Costa Rica',
        'HR' => 'Croatia',
        'CW' => 'Curacao',
        'CY' => 'Cyprus',
        'CZ' => 'Czech Republic',
        'DK' => 'Denmark',
        'DJ' => 'Djibouti',
        'DM' => 'Dominica',
        'DO' => 'Dominican Republic',
        'EG' => 'Egypt',
        'SV' => 'El Salvador',
        'GQ' => 'Equatorial Guinea',
        'ER' => 'Eritrea',
        'EE' => 'Estonia',
        'ET' => 'Ethiopia',
        'FJ' => 'Fiji',
        'FI' => 'Finland',
        'FR' => 'France',
        'GF' => 'French Guiana',
        'PF' => 'French Polynesia',
        'GA' => 'Gabon',
        'GM' => 'Gambia',
        'DE' => 'Germany',
        'GH' => 'Ghana',
        'GR' => 'Greece',
        'GD' => 'Grenada',
        'GP' => 'Guadeloupe',
        'GT' => 'Guatemala',
        'GN' => 'Guinea',
        'GW' => 'Guinea-Bissau',
        'HT' => 'Haiti',
        'HN' => 'Honduras',
        'HU' => 'Hungary',
        'IS' => 'Iceland',
        'IQ' => 'Iraq',
        'IE' => 'Ireland',
        'IL' => 'Israel',
        'IT' => 'Italy',
        'JM' => 'Jamaica',
        'JO' => 'Jordan',
        'KZ' => 'Kazakhstan',
        'KE' => 'Kenya',
        'KW' => 'Kuwait',
        'KG' => 'Kyrgyzstan',
        'LV' => 'Latvia',
        'LB' => 'Lebanon',
        'LS' => 'Lesotho',
        'LY' => 'Libya',
        'LI' => 'Liechtenstein',
        'LT' => 'Lithuania',
        'LU' => 'Luxembourg',
        'MK' => 'Macedonia',
        'MG' => 'Madagascar',
        'MW' => 'Malawi',
        'ML' => 'Mali',
        'MT' => 'Malta',
        'MQ' => 'Martinique',
        'MR' => 'Mauritania',
        'MU' => 'Mauritius',
        'YT' => 'Mayotte',
        'MX' => 'Mexico',
        'MD' => 'Moldova',
        'MC' => 'Monaco',
        'ME' => 'Montenegro',
        'MS' => 'Montserrat',
        'MA' => 'Morocco',
        'MZ' => 'Mozambique',
        'NA' => 'Namibia',
        'NL' => 'Netherlands',
        'NC' => 'New Caledonia',
        'NZ' => 'New Zealand',
        'NI' => 'Nicaragua',
        'NE' => 'Niger',
        'NG' => 'Nigeria',
        'MP' => 'Northern Mariana Islands',
        'NO' => 'Norway',
        'OM' => 'Oman',
        'PK' => 'Pakistan',
        'PA' => 'Panama',
        'PG' => 'Papua New Guinea',
        'PL' => 'Poland',
        'PT' => 'Portugal',
        'PR' => 'Puerto Rico',
        'QA' => 'Qatar',
        'RE' => 'Reunion',
        'RO' => 'Romania',
        'RU' => 'Russia',
        'RW' => 'Rwanda',
        'BL' => 'Saint Barthelemy',
        'SH' => 'Saint Helena',
        'KN' => 'Saint Kitts-Nevis',
        'LC' => 'Saint Lucia',
        'MF' => 'Saint Martin',
        'PM' => 'Saint Pierre Et Miquelon',
        'VC' => 'Saint Vincent-The Grenadines',
        'SM' => 'San Marino',
        'ST' => 'Sao Tome and Principe',
        'SA' => 'Saudi Arabia',
        'SN' => 'Senegal',
        'RS' => 'Serbia',
        'SC' => 'Seychelles',
        'SL' => 'Sierra Leone',
        'SG' => 'Singapore',
        'SX' => 'Sint Maarten',
        'SK' => 'Slovakia',
        'SI' => 'Slovenia',
        'SO' => 'Somalia',
        'ZA' => 'South Africa',
        'ES' => 'Spain',
        'SZ' => 'Swaziland',
        'SE' => 'Sweden',
        'CH' => 'Switzerland',
        'TJ' => 'Tajikistan',
        'TZ' => 'Tanzania',
        'TG' => 'Togo',
        'TT' => 'Trinidad and Tobago',
        'TN' => 'Tunisia',
        'TR' => 'Turkey',
        'TM' => 'Turkmenistan',
        'TC' => 'Turks and Caicos Islands',
        'VI' => 'U.S. Virgin Islands',
        'UG' => 'Uganda',
        'UA' => 'Ukraine',
        'AE' => 'United Arab Emirates',
        'UZ' => 'Uzbekistan',
        'VA' => 'Vatican',
        'WF' => 'Wallis and Futuna Islands',
        'EH' => 'Western Sahara',
        'YE' => 'Yemen',
        'ZM' => 'Zambia',
    ];
    public static $states = [
        'ES' =>
            [
                'C'  => 'A Coruna',
                'VI' => 'Alava',
                'AB' => 'Albacete',
                'A'  => 'Alicante',
                'AL' => 'Almeria',
                'O'  => 'Asturias',
                'AV' => 'Avila',
                'BA' => 'Badajoz',
                'PM' => 'Baleares',
                'B'  => 'Barcelona',
                'BU' => 'Burgos',
                'CC' => 'Caceres',
                'CA' => 'Cadiz',
                'S'  => 'Cantabria',
                'CS' => 'Castellon',
                'CR' => 'Ciudad Real',
                'CO' => 'Cordoba',
                'CU' => 'Cuenca',
                'GI' => 'Girona',
                'GR' => 'Granada',
                'GU' => 'Guadalajara',
                'SS' => 'Guipuzcoa',
                'H'  => 'Huelva',
                'HU' => 'Huesca',
                'J'  => 'Jaen',
                'LO' => 'La Rioja',
                'GC' => 'Las Palmas',
                'LE' => 'Leon',
                'L'  => 'Lleida',
                'LU' => 'Lugo',
                'M'  => 'Madrid',
                'MA' => 'Malaga',
                'MU' => 'Murcia',
                'NA' => 'Navarre',
                'OR' => 'Ourense',
                'P'  => 'Palencia',
                'PO' => 'Pontevedra',
                'SA' => 'Salamanca',
                'TF' => 'Santa Cruz De Tenerife',
                'SG' => 'Segovia',
                'SE' => 'Seville',
                'SO' => 'Soria',
                'T'  => 'Tarragona',
                'TE' => 'Teruel',
                'TO' => 'Toledo',
                'V'  => 'Valencia',
                'VA' => 'Valladolid',
                'BI' => 'Vizcaya',
                'ZA' => 'Zamora',
                'Z'  => 'Zaragoza',
            ],
        'NG' =>
            [
                'AB' => 'Abia',
                'AD' => 'Adamawa',
                'AK' => 'Akwa Ibom',
                'AN' => 'Anambra',
                'BA' => 'Bauchi',
                'BY' => 'Bayelsa',
                'BE' => 'Benue',
                'BO' => 'Borno',
                'CR' => 'Cross River',
                'DE' => 'Delta',
                'EB' => 'Ebonyi',
                'FD' => 'Edo',
                'EK' => 'Ekiti',
                'EN' => 'Enugu',
                'FC' => 'Federal Capital Territory',
                'GO' => 'Gombe',
                'IM' => 'Imo',
                'JI' => 'Jigawa',
                'KD' => 'Kaduna',
                'KN' => 'Kano',
                'KT' => 'Katsina',
                'KB' => 'Kebbi',
                'KO' => 'Kogi',
                'KW' => 'Kwara',
                'LA' => 'Lagos',
                'NA' => 'Nassarawa',
                'NI' => 'Niger',
                'OG' => 'Ogun',
                'ON' => 'Ondo',
                'OS' => 'Osun',
                'OY' => 'Oyo',
                'PL' => 'Plateau',
                'RI' => 'Rivers',
                'SO' => 'Sokoto',
                'TA' => 'Taraba',
                'YO' => 'Yobe',
                'ZA' => 'Zamfara',
            ],
        'IT' =>
            [
                'AG' => 'Agrigento',
                'AL' => 'Alessandria',
                'AN' => 'Ancona',
                'AO' => 'Aosta',
                'AR' => 'Arezzo',
                'AP' => 'Ascoli Piceno',
                'AT' => 'Asti',
                'AV' => 'Avellino',
                'BA' => 'Bari',
                'BT' => 'Barletta-Andria-Trani',
                'BL' => 'Belluno',
                'BN' => 'Benevento',
                'BG' => 'Bergamo',
                'BI' => 'Biella',
                'BO' => 'Bologna',
                'BZ' => 'Bolzano',
                'BS' => 'Brescia',
                'BR' => 'Brindisi',
                'CA' => 'Cagliari',
                'CL' => 'Caltanissetta',
                'CB' => 'Campobasso',
                'CI' => 'Carbonia-Iglesias',
                'CE' => 'Caserta',
                'CT' => 'Catania',
                'CZ' => 'Catanzaro',
                'CH' => 'Chieti',
                'CO' => 'Como',
                'CS' => 'Cosenza',
                'CR' => 'Cremona',
                'KR' => 'Crotone',
                'CN' => 'Cuneo',
                'EN' => 'Enna',
                'FM' => 'Fermo',
                'FE' => 'Ferrara',
                'FI' => 'Firenze',
                'FG' => 'Foggia',
                'FO' => 'Forli-Cesena',
                'FR' => 'Frosinone',
                'GE' => 'Genova',
                'GO' => 'Gorizia',
                'GR' => 'Grosseto',
                'IM' => 'Imperia',
                'IS' => 'Isernia',
                'AQ' => 'L\'Aquila',
                'SP' => 'La Spezia',
                'LT' => 'Latina',
                'LE' => 'Lecce',
                'LC' => 'Lecco',
                'LI' => 'Livorno',
                'LO' => 'Lodi',
                'LU' => 'Lucca',
                'MC' => 'Macerata',
                'MN' => 'Mantova',
                'MS' => 'Massa-Carrara',
                'MT' => 'Matera',
                'MA' => 'Medio Campidano',
                'ME' => 'Messina',
                'MI' => 'Milano',
                'MO' => 'Modena',
                'MZ' => 'Monza',
                'NA' => 'Napoli',
                'NO' => 'Novara',
                'NU' => 'Nuoro',
                'OG' => 'Ogliastra',
                'OL' => 'Olbia-Tempio',
                'OR' => 'Oristano',
                'PD' => 'Padova',
                'PA' => 'Palermo',
                'PR' => 'Parma',
                'PV' => 'Pavia',
                'PG' => 'Perugia',
                'PS' => 'Pesaro e Urbino',
                'PE' => 'Pescara',
                'PC' => 'Piacenza',
                'PI' => 'Pisa',
                'PT' => 'Pistoia',
                'PN' => 'Pordenone',
                'PZ' => 'Potenza',
                'PO' => 'Prato',
                'RG' => 'Ragusa',
                'RA' => 'Ravenna',
                'RC' => 'Reggio Calabria',
                'RE' => 'Reggio Emilia',
                'RI' => 'Rieti',
                'RN' => 'Rimini',
                'RM' => 'Roma',
                'RO' => 'Rovigo',
                'SA' => 'Salerno',
                'SS' => 'Sassari',
                'SV' => 'Savona',
                'SI' => 'Siena',
                'SR' => 'Siracusa',
                'SO' => 'Sondrio',
                'TA' => 'Taranto',
                'TE' => 'Teramo',
                'TR' => 'Terni',
                'TO' => 'Torino',
                'TP' => 'Trapani',
                'TN' => 'Trento',
                'TV' => 'Treviso',
                'TS' => 'Trieste',
                'UD' => 'Udine',
                'VA' => 'Varese',
                'VE' => 'Venezia',
                'VB' => 'Verbano-Cusio-Ossola',
                'VC' => 'Vercelli',
                'VR' => 'Verona',
                'VV' => 'Vibo Valentia',
                'VI' => 'Vicenza',
                'VT' => 'Viterbo',
            ],
        'MX' =>
            [
                'AGU' => 'Aguascalientes',
                'BCN' => 'Baja California',
                'BCS' => 'Baja California Sur',
                'CAM' => 'Campeche',
                'CHP' => 'Chiapas',
                'CHH' => 'Chihuahua',
                'COA' => 'Coahuila',
                'COL' => 'Colima',
                'DIF' => 'Distrito Federal',
                'DUR' => 'Durango',
                'GUA' => 'Guanajuato',
                'GRO' => 'Guerrero',
                'HID' => 'Hidalgo',
                'JAL' => 'Jalisco',
                'MEX' => 'Mexico',
                'MIC' => 'Michoacán',
                'MOR' => 'Morelos',
                'NAY' => 'Nayarit',
                'NLE' => 'Nuevo León',
                'OAX' => 'Oaxaca',
                'PUE' => 'Puebla',
                'QUE' => 'Querétaro',
                'ROO' => 'Quintana Roo',
                'SLP' => 'San Luis Potosí',
                'SIN' => 'Sinaloa',
                'SON' => 'Sonora',
                'TAB' => 'Tabasco',
                'TAM' => 'Tamaulipas',
                'TLA' => 'Tlaxcala',
                'VER' => 'Veracruz',
                'YUC' => 'Yucatán',
                'ZAC' => 'Zacatecas',
            ],
        'SV' =>
            [
                'AH' => 'Ahuachapan',
                'CA' => 'Cabanas',
                'CH' => 'Chalatenango',
                'CU' => 'Cuscatlan',
                'LI' => 'La Libertad',
                'PA' => 'La Paz',
                'UN' => 'La Union',
                'MO' => 'Morazan',
                'SM' => 'San Miguel',
                'SS' => 'San Salvador',
                'SV' => 'San Vicente',
                'SA' => 'Santa Ana',
                'SO' => 'Sonsonate',
                'US' => 'Usulutan',
            ],
        'KZ' =>
            [
                'AKM' => 'Akmolinskaya',
                'AKT' => 'Aktyubinskaya',
                'ALM' => 'Almatinskaya',
                'ATY' => 'Atyrauskaya',
                'KAR' => 'Karagandinskaya',
                'KUS' => 'Kostanayskaya',
                'KZY' => 'Kyzylordinskaya',
                'MAN' => 'Mangistauskaya',
                'PAV' => 'Pavlodarskaya',
                'SEV' => 'Severo-Kazakhstanskaya',
                'VOS' => 'Vostochno-Kazakhstanskaya',
                'YUZ' => 'Yuzhno-Kazakhstanskaya',
                'ZAP' => 'Zapadna-Kazakhstanskaya',
                'ZHA' => 'Zhambylskaya',
            ],
        'IQ' =>
            [
                'AN' => 'Al Anbar',
                'BA' => 'Al Basrah',
                'MU' => 'Al Munthana',
                'QA' => 'Al Quadisiya',
                'TS' => 'Al Ta\'amim',
                'NA' => 'An Najaf',
                'AR' => 'Arbil',
                'SU' => 'As Sulaymaniah',
                'BB' => 'Babil',
                'BG' => 'Baghdad',
                'DQ' => 'Dhi Qar',
                'DI' => 'Diyala',
                'KA' => 'Karbala',
                'MA' => 'Maysan',
                'NI' => 'Nainawa',
                'SD' => 'Salah Al Deen',
                'WA' => 'Wasit',
            ],
        'US' =>
            [
                'AL' => 'Alabama',
                'AK' => 'Alaska',
                'AS' => 'American Samoa',
                'AZ' => 'Arizona',
                'AR' => 'Arkansas',
                'AA' => 'Armed Forces Americas (AA)',
                'AE' => 'Armed Forces Europe (AE)',
                'AP' => 'Armed Forces Pacific (AP)',
                'CA' => 'California',
                'CO' => 'Colorado',
                'CT' => 'Connecticut',
                'DE' => 'Delaware',
                'DC' => 'District of Columbia',
                'FL' => 'Florida',
                'GA' => 'Georgia',
                'GU' => 'Guam',
                'HI' => 'Hawaii',
                'ID' => 'Idaho',
                'IL' => 'Illinois',
                'IN' => 'Indiana',
                'IA' => 'Iowa',
                'KS' => 'Kansas',
                'KY' => 'Kentucky',
                'LA' => 'Louisiana',
                'ME' => 'Maine',
                'MH' => 'Marshall Islands',
                'MD' => 'Maryland',
                'MA' => 'Massachusetts',
                'MI' => 'Michigan',
                'FM' => 'Micronesia',
                'MN' => 'Minnesota',
                'MS' => 'Mississippi',
                'MO' => 'Missouri',
                'MT' => 'Montana',
                'NE' => 'Nebraska',
                'NV' => 'Nevada',
                'NH' => 'New Hampshire',
                'NJ' => 'New Jersey',
                'NM' => 'New Mexico',
                'NY' => 'New York',
                'NC' => 'North Carolina',
                'ND' => 'North Dakota',
                'OH' => 'Ohio',
                'OK' => 'Oklahoma',
                'OR' => 'Oregon',
                'PW' => 'Palau',
                'PA' => 'Pennsylvania',
                'RI' => 'Rhode Island',
                'SC' => 'South Carolina',
                'SD' => 'South Dakota',
                'TN' => 'Tennessee',
                'TX' => 'Texas',
                'UT' => 'Utah',
                'VT' => 'Vermont',
                'VA' => 'Virginia',
                'WA' => 'Washington',
                'WV' => 'West Virginia',
                'WI' => 'Wisconsin',
                'WY' => 'Wyoming',
            ],
        'CR' =>
            [
                'A'  => 'Alajuela',
                'C'  => 'Cartago',
                'G'  => 'Guanacaste',
                'H'  => 'Heredia',
                'L'  => 'Limon',
                'P'  => 'Puntarenas',
                'SJ' => 'San Jose',
            ],
        'CA' =>
            [
                'AB' => 'Alberta',
                'BC' => 'British Columbia',
                'MB' => 'Manitoba',
                'NB' => 'New Brunswick',
                'NL' => 'Newfoundland and Labrador',
                'NT' => 'Northwest Territories',
                'NS' => 'Nova Scotia',
                'ON' => 'Ontario',
                'PE' => 'Prince Edward Island',
                'QC' => 'Quebec',
                'SK' => 'Saskatchewan',
                'YT' => 'Yukon Territory',
            ],
        'GT' =>
            [
                'AV' => 'Alta Verapaz',
                'BV' => 'Baja Verapaz',
                'CM' => 'Chimaltenango',
                'CQ' => 'Chiquimula',
                'PR' => 'El Progreso',
                'ES' => 'Escuintla',
                'GU' => 'Guatemala',
                'HU' => 'Huehuetenango',
                'IZ' => 'Izabal',
                'JA' => 'Jalapa',
                'JU' => 'Jutiapa',
                'PE' => 'Peten',
                'QZ' => 'Quetzaltenango',
                'QC' => 'Quiche',
                'RE' => 'Retalhuleu',
                'SA' => 'Sacatepequez',
                'SM' => 'San Marcos',
                'SR' => 'Santa Rosa',
                'SO' => 'Solola',
                'SU' => 'Suchitepequez',
                'TO' => 'Totonicapan',
                'ZA' => 'Zacapa',
            ],
        'HN' =>
            [
                'AT' => 'Atlántida',
                'CH' => 'Choluteca',
                'CL' => 'Colón',
                'CM' => 'Comayagua',
                'CP' => 'Copán',
                'CR' => 'Cortés',
                'EP' => 'El Paraíso',
                'FM' => 'Francisco Morazán',
                'GD' => 'Gracias a Dios',
                'IN' => 'Intibucá',
                'IB' => 'Islas de la Bahia',
                'LP' => 'La Paz',
                'LE' => 'Lempira',
                'OC' => 'Ocotepeque',
                'OL' => 'Olancho',
                'SB' => 'Santa Barbara',
                'VA' => 'Valle',
                'YO' => 'Yoro',
            ],
        'AU' =>
            [
                'ACT' => 'Australia Capital Territory',
                'NSW' => 'New South Wales',
                'NT'  => 'Northern Territory',
                'QLD' => 'Queensland',
                'SA'  => 'South Australia',
                'TAS' => 'Tasmania',
                'VIC' => 'Victoria',
                'WA'  => 'Western Australia',
            ],
        'SO' =>
            [
                'AW' => 'Awdal',
                'BK' => 'Bakool',
                'BN' => 'Banaadir',
                'BR' => 'Bari',
                'BY' => 'Bay',
                'GA' => 'GalgaDuud',
                'GE' => 'Gedo',
                'HI' => 'Hiraan',
                'JG' => 'Jubbada Dhexe',
                'JH' => 'Jubbada Hoose',
                'MU' => 'Mudug',
                'NU' => 'Nugaal',
                'Sa' => 'Sanaag',
                'SD' => 'Shabeellada Dhexe',
                'SH' => 'Shabeellada Hoose',
                'SO' => 'Sool',
                'TO' => 'Togdheer',
                'WO' => 'Waqooyi Galbeed',
            ],
        'DO' =>
            [
                '02'  => 'Azua',
                '03'  => 'Bahoruco',
                '04'  => 'Barahona',
                '05'  => 'Dajabon',
                '01 ' => 'Districto Nacional',
                '06'  => 'Duarte',
                '08'  => 'El Seybo',
                '09'  => 'Espaillat',
                '30'  => 'Hato  Mayor',
                '19'  => 'Hermanas Mirabal',
                '10'  => 'Independencia',
                '11'  => 'La Altagracia',
                '07'  => 'La Estralleta',
                '12'  => 'La Romana',
                '13'  => 'La Vega',
                '14'  => 'Maria Trinidad Sanchez',
                '28'  => 'Monsenor Nouel',
                '15'  => 'Monte Cristi',
                '29'  => 'Monte Plata',
                '16'  => 'Pedernales',
                '17'  => 'Peravia',
                '18'  => 'Puerto Plata',
                '20'  => 'Samana',
                '21'  => 'San Cristobal',
                '31'  => 'San Jose de Ocoa',
                '22'  => 'San Juan',
                '23'  => 'San Pedro de Macoris',
                '25'  => 'Santiago',
                '26'  => 'Santiago Rodríguez',
                '32'  => 'Santo Domingo',
                '24'  => 'Sánchez Ramírez',
            ],
        'PA' =>
            [
                '1' => 'BOCAS DEL TORO',
                '2' => 'CHIRIQUI',
                '3' => 'COCLE',
                '4' => 'COLON',
                '5' => 'DARIEN',
                '6' => 'HERRERA',
                '0' => 'KUNA YALA',
                '7' => 'LOS SANTOS',
                '8' => 'PANAMA',
                '9' => 'VERAGUAS',
            ],
        'NI' =>
            [
                'BO' => 'Boaco',
                'CA' => 'Carazo',
                'CI' => 'Chinandega',
                'CO' => 'Chontales',
                'ES' => 'Esteli',
                'GR' => 'Granada',
                'JI' => 'Jinotega',
                'LE' => 'Leon',
                'MD' => 'Madriz',
                'MN' => 'Managua',
                'MS' => 'Masaya',
                'MT' => 'Matagalpa',
                'NS' => 'Nueva Segovia',
                'SJ' => 'Rio San Juan',
                'RI' => 'Rivas',
            ],
        'PG' =>
            [
                'BO' => 'Bougainville',
                'CE' => 'Central',
                'CH' => 'Chimbu',
                'EB' => 'East New Britain',
                'ES' => 'East Sepik',
                'EH' => 'Eastern Highlands',
                'EN' => 'Enga',
                'GU' => 'Gulf',
                'MD' => 'Madang',
                'MU' => 'Manus',
                'MB' => 'Milne Bay',
                'MO' => 'Morobe',
                'CD' => 'National Capital District',
                'NI' => 'New Ireland',
                'NO' => 'Northern',
                'NS' => 'Northern Solomons',
                'OR' => 'Oro',
                'SA' => 'Sandaun',
                'SI' => 'Simbu',
                'SH' => 'Southern Highlands',
                'WB' => 'West New Britain',
                'WS' => 'West Sepik',
                'WE' => 'Western',
                'WH' => 'Western Highlands',
            ],
        'MZ' =>
            [
                'P' => 'Cabo Delgado',
                'G' => 'Gaza',
                'I' => 'Inhambane',
                'B' => 'Manica',
                'L' => 'Maputo',
                'N' => 'Nampula',
                'A' => 'Niassa',
                'S' => 'Sofala',
                'T' => 'Tete',
                'Q' => 'Zambezia',
            ],
        'JM' =>
            [
                'JM-13' => 'Clarendon',
                'JM-09' => 'Hanover',
                'JM-01' => 'Kingston',
                'JM-12' => 'Manchester',
                'JM-04' => 'Portland',
                'JM-02' => 'Saint Andrew',
                'JM-06' => 'Saint Ann',
                'JM-14' => 'Saint Catherine',
                'JM-11' => 'Saint Elizabeth',
                'JM-08' => 'Saint James',
                'JM-05' => 'Saint Mary',
                'JM-03' => 'Saint Thomas',
                'JM-07' => 'Trelawny',
                'JM-10' => 'Westmoreland',
            ],
        'RW' =>
            [
                'RW-02' => 'Est',
                'RW-03' => 'Nord',
                'RW-04' => 'Ouest',
                'RW-05' => 'Sud',
                'RW-01' => 'Ville de Kigali',
            ],
        'AL' =>
            [
                'BERAT'       => 'Berat',
                'DIBER'       => 'Diber',
                'DURRES'      => 'Durres',
                'ELBASAN'     => 'Elbasan',
                'FIER'        => 'Fier',
                'GJIROKASTER' => 'Gjirokaster',
                'KORCE'       => 'Korce',
                'KUKES'       => 'Kukes',
                'LEZHE'       => 'Lezhe',
                'SHKODER'     => 'Shkoder',
                'TIRANA'      => 'Tirana',
                'VLORE'       => 'Vlore',
            ],
        'IE' =>
            [
                'CARLOW'    => 'Carlow',
                'CAVAN'     => 'Cavan',
                'CLARE'     => 'Clare',
                'CORK'      => 'Cork',
                'DONEGAL'   => 'Donegal',
                'DUBLIN'    => 'Dublin',
                'GALWAY'    => 'Galway',
                'KERRY'     => 'Kerry',
                'KILDARE'   => 'Kildare',
                'KILKENNY'  => 'Kilkenny',
                'LAOIS'     => 'Laois',
                'LEITRIM'   => 'Leitrim',
                'LIMERICK'  => 'Limerick',
                'LONGFORD'  => 'Longford',
                'LOUTH'     => 'Louth',
                'MAYO'      => 'Mayo',
                'MEATH'     => 'Meath',
                'MONAGHAN'  => 'Monaghan',
                'OFFALY'    => 'Offaly',
                'ROSCOMMON' => 'Roscommon',
                'SLIGO'     => 'Sligo',
                'TIPPERARY' => 'Tipperary',
                'WATERFORD' => 'Waterford',
                'WESTMEATH' => 'Westmeath',
                'WEXFORD'   => 'Wexford',
                'WICKLOW'   => 'Wicklow',
            ],
    ];

    public function InitBrowser()
    {
        $this->UseCurlBrowser();

        if (ConfigValue(CONFIG_SITE_STATE) != SITE_STATE_DEBUG) {
            $this->http->SetProxy($this->proxyDOP());
//            $this->http->SetProxy($this->proxyUK());
        } else {
            $this->http->SetProxy("localhost:8000");
        }
        $this->http->setDefaultHeader("User-Agent", \HttpBrowser::PROXY_USER_AGENT);
    }

    public function registerAccount(array $fields)
    {
        $fields['FullPhone'] = $fields['PhoneCountryCodeNumeric'] . $fields['PhoneAreaCode'] . $fields['PhoneLocalNumber'];

        if ($fields['AddressType'] == 'H') {
            $fields['AddressType'] = 'HOME';
        } else {
            $fields['AddressType'] = 'WORK';
        }
        $this->http->Form = [
            'address1'              => 'AddressLine1',
            'address2'              => 'AddressLine2',
            'addressType'           => 'AddressType',
            'city'                  => 'City',
            'country'               => 'Country',
            'email'                 => 'Email',
            'firstName'             => 'FirstName',
            'homePhone'             => 'FullPhone',
            'lastName'              => 'LastName',
            'middleName'            => 'MiddleInitial',
            'partnerShare'          => 'false',
            'password'              => 'Password',
            'postalCode'            => 'PostalCode',
            'preferredLanguageCode' => 'EN',
            'sendDirectMail'        => 'true',
            'sendEmail'             => 'false',
            'sendNewsletterEmail'   => 'true',
            'sendPartnerEmail'      => 'false',
            'sendPromotionalEmail'  => 'true',
            'sendStatementEmail'    => 'true',
            'sendSurveyEmail'       => 'true',
            'title'                 => 'Title',
            'username'              => 'Username',
        ];

        foreach ($this->http->Form as $k => $v) {
            if (isset($fields[$v])) {
                if (!empty($fields[$v])) {
                    $this->http->Form[$k] = $fields[$v];
                } else {
                    unset($this->http->Form[$k]);
                }
            }
        }

        if (!empty($fields['StateOrProvince'])) {
            if (in_array($fields['Country'], ['AL', 'IE'])) {
                $this->http->Form['county'] = $fields['StateOrProvince'];
            } else {
                $this->http->Form['subdivision'] = $fields['StateOrProvince'];
            }
        }
        $this->http->RetryCount = 0;
        $this->http->FormURL = 'https://www.choicehotels.com/webapi/user-account/';
        $this->http->PostForm();
        $response = json_decode($this->http->Response['body'], true);

        if ($response == false) {
            $this->http->Log('response is not json', LOG_LEVEL_ERROR);

            return false;
        }

        if (isset($response['status']) && $response['status'] === 'OK') {
            $this->http->Log('got OK status');
            $this->ErrorMessage = 'Account registered.';

            if (isset($response['guestProfile']['loyaltyAccountNumber'])) {
                $this->ErrorMessage .= ' Your account number: ' . $response['guestProfile']['loyaltyAccountNumber'];
            }

            return true;
        }

        if (isset($response['status']) && $response['status'] === 'ERROR') {
            if (isset($response['inputErrors']) && is_array($response['inputErrors'])) {
                $error = "";

                foreach ($response['inputErrors'] as $k => $v) {
                    $error .= $k . ' ' . $v . ', ';
                }
                $error = trim($error, ' ,');

                throw new \UserInputError($error); // Is it always user input error?
            }

            if (isset($response['outputErrors']) && is_array($response['outputErrors'])) {
                $errmsg = array_shift($response['outputErrors']);

                if ($errmsg == 'Sorry, a possible duplicate account exists with the information you provided.') {
                    throw new \ProviderError($errmsg);
                } else {
                    throw new \UserInputError($errmsg);
                } // Is it always user input error?
            }
        }
        $this->http->Log('unknown error', LOG_LEVEL_ERROR);

        return false;
    }

    public function getRegisterFields()
    {
        return [
            'Title' => [
                'Type'     => 'string',
                'Caption'  => 'Title',
                'Required' => false,
                'Options'  => self::$titles,
            ],
            'FirstName' => [
                'Type'     => 'string',
                'Caption'  => 'FirstName',
                'Required' => true,
            ],
            'MiddleInitial' => [
                'Type'     => 'string',
                'Caption'  => 'Middle Initial',
                'Required' => false,
            ],
            'LastName' => [
                'Type'     => 'string',
                'Caption'  => 'LastName',
                'Required' => true,
            ],
            'Country' => [
                'Type'     => 'string',
                'Caption'  => 'Country Code',
                'Required' => true,
                'Options'  => self::$countries,
            ],
            'AddressType' => [
                'Type'     => 'string',
                'Caption'  => 'Primary Address Type',
                'Required' => true,
                'Options'  => self::$addressTypes,
            ],
            'StateOrProvince' => [
                'Type'     => 'string',
                'Caption'  => 'State/County, required for certain countries',
                'Required' => false,
            ],
            'City' => [
                'Type'     => 'string',
                'Caption'  => 'City',
                'Required' => true,
            ],
            'PostalCode' => [
                'Type'     => 'string',
                'Caption'  => 'Postal Code, required for certain countries',
                'Required' => false,
            ],
            'AddressLine1' => [
                'Type'     => 'string',
                'Caption'  => 'Address Line 1',
                'Required' => true,
            ],
            'AddressLine2' => [
                'Type'     => 'string',
                'Caption'  => 'Address Line 2',
                'Required' => false,
            ],
            'Email' => [
                'Type'     => 'string',
                'Caption'  => 'Email Address',
                'Required' => true,
            ],
            'PhoneCountryCodeNumeric' => [
                'Type'     => 'string',
                'Caption'  => 'Phone country code',
                'Required' => true,
            ],
            'PhoneAreaCode' => [
                'Type'     => 'string',
                'Caption'  => 'Phone area code',
                'Required' => true,
            ],
            'PhoneLocalNumber' => [
                'Type'     => 'string',
                'Caption'  => 'Phone number',
                'Required' => true,
            ],
            'Username' => [
                'Type'     => 'string',
                'Caption'  => 'Username, 6 to 20 characters',
                'Required' => true,
            ],
            'Password' => [
                'Type'     => 'string',
                'Caption'  => 'Password, 6 to 20 characters',
                'Required' => true,
            ],
        ];
    }
}
