<?php

namespace AwardWallet\Engine\worldpoints\Transfer;

class Register extends \TAccountCheckerWorldpoints
{
    public static $titles = [
        '01' => 'Mr',
        '02' => 'Mrs',
        '03' => 'Miss',
        '04' => 'Ms',
        '05' => 'Dr',
        '17' => 'Baron',
        '27' => 'Baroness',
        '07' => 'Capt',
        '34' => 'Dame',
        '09' => 'Lady',
        '11' => 'Lord',
        '16' => 'Mstr',
        '06' => 'Prof',
        '35' => 'Rabbi',
        '08' => 'Rev',
        '10' => 'Sir',
        '59' => 'The RT Hon',
        '55' => 'Viscount',
        '57' => 'Viscountess',
    ];

    public static $genders = [
        'M' => 'Male',
        'F' => 'Female',
    ];

    public static $nationalities = [
        '069' => 'Afghan',
        '092' => 'Albanian',
        '070' => 'Algerian',
        '002' => 'American',
        '145' => 'American Samoan',
        '150' => 'Andorran',
        '100' => 'Angolan',
        '192' => 'Anguillan',
        '137' => 'Antiguan or Barbudan',
        '060' => 'Argentinian',
        '087' => 'Armenian',
        '170' => 'Aruban',
        '014' => 'Australian',
        '040' => 'Austrian',
        '071' => 'Azerbaijani',
        '135' => 'Bahamian',
        '075' => 'Bahraini',
        '065' => 'Bangladeshi',
        '085' => 'Barbadian',
        '038' => 'Belgian',
        '122' => 'Belizian',
        '055' => 'Belorussian',
        '186' => 'Beninese',
        '121' => 'Bermudian',
        '199' => 'Bhutanese',
        '118' => 'Bolivian',
        '119' => 'Bosnian',
        '111' => 'Botswanan',
        '029' => 'Brazilian',
        '001' => 'British',
        '115' => 'British Virgin Islander',
        '094' => 'Bruneian',
        '037' => 'Bulgarian',
        '168' => 'Burkinese',
        '089' => 'Burmese',
        '158' => 'Burundian',
        '164' => 'Cambodian',
        '114' => 'Cameroonian',
        '013' => 'Canadian',
        '181' => 'Cape Verdean',
        '149' => 'Caymanian',
        '146' => 'Central African',
        '143' => 'Chadian',
        '095' => 'Chilean',
        '005' => 'Chinese',
        '179' => 'Christmas Islander',
        '084' => 'Colombian',
        '142' => 'Congolese',
        '126' => 'Costa Rican',
        '067' => 'Croatian',
        '131' => 'Cuban',
        '051' => 'Cypriot',
        '036' => 'Czech',
        '024' => 'Danish',
        '169' => 'Djiboutian',
        '123' => 'Dominican',
        '021' => 'Dutch',
        '157' => 'Dutch Antillean',
        '112' => 'Ecuadorean',
        '042' => 'Egyptian',
        '086' => 'Emirati',
        '010' => 'English',
        '177' => 'Equatorial Guinean',
        '144' => 'Eritrean',
        '057' => 'Estonian',
        '136' => 'Ethiopian',
        '166' => 'Faroese',
        '124' => 'Fijian',
        '032' => 'Finnish',
        '011' => 'French',
        '195' => 'French Guianese',
        '156' => 'French Polynesian',
        '184' => 'Gabonese',
        '133' => 'Gambian',
        '096' => 'Georgian',
        '007' => 'German',
        '047' => 'Ghanaian',
        '148' => 'Gibraltarian',
        '022' => 'Greek',
        '167' => 'Greenlander',
        '125' => 'Grenadian',
        '197' => 'Guamanian',
        '161' => 'Guatemalan',
        '175' => 'Guinean',
        '127' => 'Guyanese',
        '191' => 'Haitian',
        '172' => 'Honduran',
        '035' => 'Hungarian',
        '160' => 'I-Kiribati',
        '074' => 'Icelandic',
        '003' => 'Indian',
        '077' => 'Indonesian',
        '058' => 'Iranian',
        '105' => 'Iraqi',
        '004' => 'Irish',
        '044' => 'Israeli',
        '008' => 'Italian',
        '132' => 'Ivoirian',
        '073' => 'Jamaican',
        '016' => 'Japanese',
        '078' => 'Jordanian',
        '064' => 'Kazakh',
        '056' => 'Kenyan',
        '173' => 'Kittitian',
        '048' => 'Korean',
        '059' => 'Kuwaiti',
        '117' => 'Kyrgyzstani',
        '196' => 'Laotian',
        '043' => 'Latvian',
        '076' => 'Lebanese',
        '154' => 'Liberian',
        '104' => 'Libyan',
        '198' => 'Liechtensteiner',
        '020' => 'Lithuanian',
        '099' => 'Luxembourger',
        '109' => 'Macedonian',
        '185' => 'Madagascan',
        '141' => 'Malawian',
        '023' => 'Malaysian',
        '129' => 'Maldivian',
        '182' => 'Malian',
        '052' => 'Maltese',
        '130' => 'Mauritanian',
        '050' => 'Mauritian',
        '062' => 'Mexican',
        '079' => 'Moldovan',
        '139' => 'Monacan',
        '176' => 'Mongolian',
        '155' => 'Montenegrin',
        '187' => 'Montserratian',
        '080' => 'Moroccan',
        '178' => 'Mosotho',
        '147' => 'Mozambican',
        '128' => 'Namibian',
        '066' => 'Nepalese',
        '028' => 'New Zealander',
        '165' => 'Nicaraguan',
        '012' => 'Nigerian',
        '082' => 'Nigerien',
        '188' => 'Niuean',
        '201' => 'Norfolk Islander',
        '025' => 'Norwegian',
        '103' => 'Omani',
        '026' => 'Pakistani',
        '190' => 'Palauan',
        '180' => 'Panamanian',
        '171' => 'Paraguayan',
        '107' => 'Peruvian',
        '039' => 'Philippine',
        '204' => 'Pitcairn Islander',
        '006' => 'Polish',
        '017' => 'Portuguese',
        '159' => 'Puerto Rican',
        '106' => 'Qatari',
        '203' => 'Reunionese',
        '034' => 'Romanian',
        '009' => 'Russian',
        '189' => 'Rwandan',
        '162' => 'Sahrawi',
        '108' => 'Saint Lucian',
        '140' => 'Saint Vincentian',
        '151' => 'Salvadorean',
        '202' => 'Sammarinese',
        '194' => 'Sao Tomean',
        '053' => 'Saudi Arabian',
        '030' => 'Scottish',
        '152' => 'Senegalese',
        '068' => 'Serbian',
        '116' => 'Seychellois',
        '102' => 'Sierra Leonian',
        '033' => 'Singaporean',
        '031' => 'Slovak',
        '081' => 'Slovenian',
        '138' => 'Somali',
        '018' => 'South African',
        '015' => 'Spanish',
        '049' => 'Sri Lankan',
        '110' => 'Sudanese',
        '200' => 'Surinamese',
        '174' => 'Swazi',
        '019' => 'Swedish',
        '045' => 'Swiss',
        '090' => 'Syrian',
        '054' => 'Taiwanese',
        '153' => 'Tajik',
        '101' => 'Tanzanian',
        '041' => 'Thai',
        '163' => 'Togolese',
        '061' => 'Trinidadian and Tobagonian',
        '098' => 'Tunisian',
        '046' => 'Turkish',
        '120' => 'Turkmen',
        '193' => 'Tuvaluan',
        '097' => 'Ugandan',
        '027' => 'Ukrainian',
        '113' => 'Uruguayan',
        '093' => 'Uzbek',
        '183' => 'Vanuatuan',
        '083' => 'Venezuelan',
        '088' => 'Vietnamese',
        '063' => 'Welsh',
        '134' => 'Yemeni',
        '091' => 'Zambian',
        '072' => 'Zimbabwean',
    ];

    public static $countries = [
        'AF' => 'Afghanistan',
        'AX' => 'Aland Islands',
        'AL' => 'Albania',
        'DZ' => 'Algeria',
        'AS' => 'American Samoa',
        'AD' => 'Andorra',
        'AO' => 'Angola',
        'AI' => 'Anguilla',
        'AQ' => 'Antarctica',
        'AG' => 'Antigua and Barbuda',
        'AR' => 'Argentina',
        'AM' => 'Armenia',
        'AW' => 'Aruba',
        'AU' => 'Australia',
        'AT' => 'Austria',
        'AZ' => 'Azerbaijan',
        'BS' => 'Bahamas',
        'BH' => 'Bahrain',
        'BD' => 'Bangladesh',
        'BB' => 'Barbados',
        'BY' => 'Belarus',
        'BE' => 'Belgium',
        'BZ' => 'Belize',
        'BJ' => 'Benin',
        'BM' => 'Bermuda',
        'BT' => 'Bhutan',
        'BO' => 'Bolivia',
        'BA' => 'Bosnia and Herzegovina',
        'BW' => 'Botswana',
        'BV' => 'Bouvet Island',
        'BR' => 'Brazil',
        'IO' => 'British Indian Ocean Territory',
        'BN' => 'Brunei Darussalam',
        'BG' => 'Bulgaria',
        'BF' => 'Burkina Faso',
        'BI' => 'Burundi',
        'KH' => 'Cambodia',
        'CM' => 'Cameroon',
        'CA' => 'Canada',
        'CV' => 'Cape Verde',
        'KY' => 'Cayman Islands',
        'CF' => 'Central African Republic',
        'TD' => 'Chad',
        'CL' => 'Chile',
        'CN' => 'China',
        'CX' => 'Christmas Island',
        'CC' => 'Cocos (Keeling) Islands',
        'CO' => 'Colombia',
        'KM' => 'Comoros',
        'CG' => 'Congo',
        'CD' => 'Congo, the Democratic Republic of the',
        'CK' => 'Cook Islands',
        'CR' => 'Costa Rica',
        'CI' => 'Cote D\'Ivoire',
        'HR' => 'Croatia',
        'CU' => 'Cuba',
        'CW' => 'Curaçao',
        'CY' => 'Cyprus',
        'CZ' => 'Czech Republic',
        'DK' => 'Denmark',
        'DJ' => 'Djibouti',
        'DM' => 'Dominica',
        'DO' => 'Dominican Republic',
        'EC' => 'Ecuador',
        'EG' => 'Egypt',
        'SV' => 'El Salvador',
        'GQ' => 'Equatorial Guinea',
        'ER' => 'Eritrea',
        'EE' => 'Estonia',
        'ET' => 'Ethiopia',
        'FK' => 'Falkland Islands (Malvinas)',
        'FO' => 'Faroe Islands',
        'FJ' => 'Fiji',
        'FI' => 'Finland',
        'FR' => 'France',
        'GF' => 'French Guiana',
        'PF' => 'French Polynesia',
        'TF' => 'French Southern Territories',
        'GA' => 'Gabon',
        'GM' => 'Gambia',
        'GE' => 'Georgia',
        'DE' => 'Germany',
        'GH' => 'Ghana',
        'GI' => 'Gibraltar',
        'GR' => 'Greece',
        'GL' => 'Greenland',
        'GD' => 'Grenada',
        'GP' => 'Guadeloupe',
        'GU' => 'Guam',
        'GT' => 'Guatemala',
        'GG' => 'Guernsey',
        'GN' => 'Guinea',
        'GW' => 'Guinea-Bissau',
        'GY' => 'Guyana',
        'HT' => 'Haiti',
        'HM' => 'Heard Island and McDonald Islands',
        'VA' => 'Holy See (Vatican City State)',
        'HN' => 'Honduras',
        'HK' => 'Hong Kong',
        'HU' => 'Hungary',
        'IS' => 'Iceland',
        'IN' => 'India',
        'ID' => 'Indonesia',
        'IR' => 'Iran, Islamic Republic of',
        'IQ' => 'Iraq',
        'IE' => 'Ireland',
        'IM' => 'Isle of Man',
        'IL' => 'Israel',
        'IT' => 'Italy',
        'JM' => 'Jamaica',
        'JP' => 'Japan',
        'JE' => 'Jersey',
        'JO' => 'Jordan',
        'KZ' => 'Kazakhstan',
        'KE' => 'Kenya',
        'KI' => 'Kiribati',
        'KP' => 'Korea, Democratic People\'s Republic of',
        'KR' => 'Korea, Republic of',
        'KW' => 'Kuwait',
        'KG' => 'Kyrgyzstan',
        'LA' => 'Lao People\'s Democratic Republic',
        'LV' => 'Latvia',
        'LB' => 'Lebanon',
        'LS' => 'Lesotho',
        'LR' => 'Liberia',
        'LY' => 'Libyan Arab Jamahiriya',
        'LI' => 'Liechtenstein',
        'LT' => 'Lithuania',
        'LU' => 'Luxembourg',
        'MO' => 'Macao',
        'MK' => 'Macedonia, the Former Yugoslav Republic of',
        'MG' => 'Madagascar',
        'MW' => 'Malawi',
        'MY' => 'Malaysia',
        'MV' => 'Maldives',
        'ML' => 'Mali',
        'MT' => 'Malta',
        'MH' => 'Marshall Islands',
        'MQ' => 'Martinique',
        'MR' => 'Mauritania',
        'MU' => 'Mauritius',
        'YT' => 'Mayotte',
        'MX' => 'Mexico',
        'FM' => 'Micronesia, Federated States of',
        'MD' => 'Moldova, Republic of',
        'MC' => 'Monaco',
        'MN' => 'Mongolia',
        'ME' => 'Montenegro',
        'MS' => 'Montserrat',
        'MA' => 'Morocco',
        'MZ' => 'Mozambique',
        'MM' => 'Myanmar',
        'NA' => 'Namibia',
        'NR' => 'Nauru',
        'NP' => 'Nepal',
        'NL' => 'Netherlands',
        'NC' => 'New Caledonia',
        'NZ' => 'New Zealand',
        'NI' => 'Nicaragua',
        'NE' => 'Niger',
        'NG' => 'Nigeria',
        'NU' => 'Niue',
        'NF' => 'Norfolk Island',
        'MP' => 'Northern Mariana Islands',
        'NO' => 'Norway',
        'OM' => 'Oman',
        'PK' => 'Pakistan',
        'PW' => 'Palau',
        'PS' => 'Palestinian Territory, Occupied',
        'PA' => 'Panama',
        'PG' => 'Papua New Guinea',
        'PY' => 'Paraguay',
        'PE' => 'Peru',
        'PH' => 'Philippines',
        'PN' => 'Pitcairn',
        'PL' => 'Poland',
        'PT' => 'Portugal',
        'PR' => 'Puerto Rico',
        'QA' => 'Qatar',
        'RE' => 'Reunion',
        'RO' => 'Romania',
        'RU' => 'Russian Federation',
        'RW' => 'Rwanda',
        'BL' => 'Saint Barthélemy',
        'SH' => 'Saint Helena',
        'KN' => 'Saint Kitts and Nevis',
        'LC' => 'Saint Lucia',
        'MF' => 'Saint Martin (French part)',
        'PM' => 'Saint Pierre and Miquelon',
        'VC' => 'Saint Vincent and the Grenadines',
        'WS' => 'Samoa',
        'SM' => 'San Marino',
        'ST' => 'Sao Tome and Principe',
        'SA' => 'Saudi Arabia',
        'SN' => 'Senegal',
        'RS' => 'Serbia',
        'SC' => 'Seychelles',
        'SL' => 'Sierra Leone',
        'SG' => 'Singapore',
        'SK' => 'Slovakia',
        'SI' => 'Slovenia',
        'SB' => 'Solomon Islands',
        'SO' => 'Somalia',
        'ZA' => 'South Africa',
        'GS' => 'South Georgia and the South Sandwich Islands',
        'ES' => 'Spain',
        'LK' => 'Sri Lanka',
        'SD' => 'Sudan',
        'SR' => 'Suriname',
        'SJ' => 'Svalbard and Jan Mayen',
        'SZ' => 'Swaziland',
        'SE' => 'Sweden',
        'CH' => 'Switzerland',
        'SY' => 'Syrian Arab Republic',
        'TW' => 'Taiwan, Province of China',
        'TJ' => 'Tajikistan',
        'TZ' => 'Tanzania, United Republic of',
        'TH' => 'Thailand',
        'TL' => 'Timor-Leste',
        'TG' => 'Togo',
        'TK' => 'Tokelau',
        'TO' => 'Tonga',
        'TT' => 'Trinidad and Tobago',
        'TN' => 'Tunisia',
        'TR' => 'Turkey',
        'TM' => 'Turkmenistan',
        'TC' => 'Turks and Caicos Islands',
        'TV' => 'Tuvalu',
        'UG' => 'Uganda',
        'UA' => 'Ukraine',
        'AE' => 'United Arab Emirates',
        'GB' => 'United Kingdom',
        'US' => 'United States',
        'UM' => 'United States Minor Outlying Islands',
        'UY' => 'Uruguay',
        'UZ' => 'Uzbekistan',
        'VU' => 'Vanuatu',
        'VE' => 'Venezuela',
        'VN' => 'Vietnam',
        'VG' => 'Virgin Islands, British',
        'VI' => 'Virgin Islands, U.s.',
        'WF' => 'Wallis and Futuna',
        'EH' => 'Western Sahara',
        'YE' => 'Yemen',
        'ZM' => 'Zambia',
        'ZW' => 'Zimbabwe',
    ];

    // TODO: Seems that it is standard ISO alpha-3 country code, recheck it and if so - make generic mapping method for all such providers
    public static $countriesMap = [
        'AF' => 'AFG',
        'AX' => 'ALA',
        'AL' => 'ALB',
        'DZ' => 'DZA',
        'AS' => 'ASM',
        'AD' => 'AND',
        'AO' => 'AGO',
        'AI' => 'AIA',
        'AQ' => 'ATA',
        'AG' => 'ATG',
        'AR' => 'ARG',
        'AM' => 'ARM',
        'AW' => 'ABW',
        'AU' => 'AUS',
        'AT' => 'AUT',
        'AZ' => 'AZE',
        'BS' => 'BHS',
        'BH' => 'BHR',
        'BD' => 'BGD',
        'BB' => 'BRB',
        'BY' => 'BLR',
        'BE' => 'BEL',
        'BZ' => 'BLZ',
        'BJ' => 'BEN',
        'BM' => 'BMU',
        'BT' => 'BTN',
        'BO' => 'BOL',
        'BA' => 'BIH',
        'BW' => 'BWA',
        'BV' => 'BVT',
        'BR' => 'BRA',
        'IO' => 'IOT',
        'BN' => 'BRN',
        'BG' => 'BGR',
        'BF' => 'BFA',
        'BI' => 'BDI',
        'KH' => 'KHM',
        'CM' => 'CMR',
        'CA' => 'CAN',
        'CV' => 'CPV',
        'KY' => 'CYM',
        'CF' => 'CAF',
        'TD' => 'TCD',
        'CL' => 'CHL',
        'CN' => 'CHN',
        'CX' => 'CXR',
        'CC' => 'CCK',
        'CO' => 'COL',
        'KM' => 'COM',
        'CG' => 'COG',
        'CD' => 'COD',
        'CK' => 'COK',
        'CR' => 'CRI',
        'CI' => 'CIV',
        'HR' => 'HRV',
        'CU' => 'CUB',
        'CW' => 'CUW',
        'CY' => 'CYP',
        'CZ' => 'CZE',
        'DK' => 'DNK',
        'DJ' => 'DJI',
        'DM' => 'DMA',
        'DO' => 'DOM',
        'EC' => 'ECU',
        'EG' => 'EGY',
        'SV' => 'SLV',
        'GQ' => 'GNQ',
        'ER' => 'ERI',
        'EE' => 'EST',
        'ET' => 'ETH',
        'FK' => 'FLK',
        'FO' => 'FRO',
        'FJ' => 'FJI',
        'FI' => 'FIN',
        'FR' => 'FRA',
        'GF' => 'GUF',
        'PF' => 'PYF',
        'TF' => 'ATF',
        'GA' => 'GAB',
        'GM' => 'GMB',
        'GE' => 'GEO',
        'DE' => 'DEU',
        'GH' => 'GHA',
        'GI' => 'GIB',
        'GR' => 'GRC',
        'GL' => 'GRL',
        'GD' => 'GRD',
        'GP' => 'GLP',
        'GU' => 'GUM',
        'GT' => 'GTM',
        'GG' => 'GGY',
        'GN' => 'GIN',
        'GW' => 'GNB',
        'GY' => 'GUY',
        'HT' => 'HTI',
        'HM' => 'HMD',
        'VA' => 'VAT',
        'HN' => 'HND',
        'HK' => 'HKG',
        'HU' => 'HUN',
        'IS' => 'ISL',
        'IN' => 'IND',
        'ID' => 'IDN',
        'IR' => 'IRN',
        'IQ' => 'IRQ',
        'IE' => 'IRL',
        'IM' => 'IMN',
        'IL' => 'ISR',
        'IT' => 'ITA',
        'JM' => 'JAM',
        'JP' => 'JPN',
        'JE' => 'JEY',
        'JO' => 'JOR',
        'KZ' => 'KAZ',
        'KE' => 'KEN',
        'KI' => 'KIR',
        'KP' => 'PRK',
        'KR' => 'KOR',
        'KW' => 'KWT',
        'KG' => 'KGZ',
        'LA' => 'LAO',
        'LV' => 'LVA',
        'LB' => 'LBN',
        'LS' => 'LSO',
        'LR' => 'LBR',
        'LY' => 'LBY',
        'LI' => 'LIE',
        'LT' => 'LTU',
        'LU' => 'LUX',
        'MO' => 'MAC',
        'MK' => 'MKD',
        'MG' => 'MDG',
        'MW' => 'MWI',
        'MY' => 'MYS',
        'MV' => 'MDV',
        'ML' => 'MLI',
        'MT' => 'MLT',
        'MH' => 'MHL',
        'MQ' => 'MTQ',
        'MR' => 'MRT',
        'MU' => 'MUS',
        'YT' => 'MYT',
        'MX' => 'MEX',
        'FM' => 'FSM',
        'MD' => 'MDA',
        'MC' => 'MCO',
        'MN' => 'MNG',
        'ME' => 'MNE',
        'MS' => 'MSR',
        'MA' => 'MAR',
        'MZ' => 'MOZ',
        'MM' => 'MMR',
        'NA' => 'NAM',
        'NR' => 'NRU',
        'NP' => 'NPL',
        'NL' => 'NLD',
        'NC' => 'NCL',
        'NZ' => 'NZL',
        'NI' => 'NIC',
        'NE' => 'NER',
        'NG' => 'NGA',
        'NU' => 'NIU',
        'NF' => 'NFK',
        'MP' => 'MNP',
        'NO' => 'NOR',
        'OM' => 'OMN',
        'PK' => 'PAK',
        'PW' => 'PLW',
        'PS' => 'PSE',
        'PA' => 'PAN',
        'PG' => 'PNG',
        'PY' => 'PRY',
        'PE' => 'PER',
        'PH' => 'PHL',
        'PN' => 'PCN',
        'PL' => 'POL',
        'PT' => 'PRT',
        'PR' => 'PRI',
        'QA' => 'QAT',
        'RE' => 'REU',
        'RO' => 'ROU',
        'RU' => 'RUS',
        'RW' => 'RWA',
        'BL' => 'BLM',
        'SH' => 'SHN',
        'KN' => 'KNA',
        'LC' => 'LCA',
        'MF' => 'MAF',
        'PM' => 'SPM',
        'VC' => 'VCT',
        'WS' => 'WSM',
        'SM' => 'SMR',
        'ST' => 'STP',
        'SA' => 'SAU',
        'SN' => 'SEN',
        'RS' => 'SRB',
        'SC' => 'SYC',
        'SL' => 'SLE',
        'SG' => 'SGP',
        'SK' => 'SVK',
        'SI' => 'SVN',
        'SB' => 'SLB',
        'SO' => 'SOM',
        'ZA' => 'ZAF',
        'GS' => 'SGS',
        'ES' => 'ESP',
        'LK' => 'LKA',
        'SD' => 'SDN',
        'SR' => 'SUR',
        'SJ' => 'SJM',
        'SZ' => 'SWZ',
        'SE' => 'SWE',
        'CH' => 'CHE',
        'SY' => 'SYR',
        'TW' => 'TWN',
        'TJ' => 'TJK',
        'TZ' => 'TZA',
        'TH' => 'THA',
        'TL' => 'TLS',
        'TG' => 'TGO',
        'TK' => 'TKL',
        'TO' => 'TON',
        'TT' => 'TTO',
        'TN' => 'TUN',
        'TR' => 'TUR',
        'TM' => 'TKM',
        'TC' => 'TCA',
        'TV' => 'TUV',
        'UG' => 'UGA',
        'UA' => 'UKR',
        'AE' => 'ARE',
        'GB' => 'GBR',
        'US' => 'USA',
        'UM' => 'UMI',
        'UY' => 'URY',
        'UZ' => 'UZB',
        'VU' => 'VUT',
        'VE' => 'VEN',
        'VN' => 'VNM',
        'VG' => 'VGB',
        'VI' => 'VIR',
        'WF' => 'WLF',
        'EH' => 'ESH',
        'YE' => 'YEM',
        'ZM' => 'ZMB',
        'ZW' => 'ZWE',
    ];

    public static $phoneTypes = [
        'H' => 'Home',
        'B' => 'Business',
        'M' => 'Mobile',
    ];

    public static $inputFieldsMap = [
        'Title'        => 'customer.cardholder.title',
        'FirstName'    => 'customer.cardholder.firstName',
        'LastName'     => 'customer.cardholder.lastName',
        'Gender'       => 'customer.cardholder.sexCode',
        'BirthDay'     => 'dobDay',
        'BirthMonth'   => 'dobMonth',
        'BirthYear'    => 'dobYear',
        'Nationality'  => 'extAttr[extAttr.CRH_EXT_NATIONALITY]',
        'Email'        => ['customer.cardholder.email', 'confirmEmail'],
        'Password'     => ['customer.cardholder.password', 'confirmPassword'],
        'Country'      => 'homeAddress.countryId',
        'AddressLine1' => 'homeAddress.addressLine1',
        'City'         => 'homeAddress.city',
        'PostalCode'   => ['postCode', 'homeAddress.zipCode'],
    ];

    public function registerAccount(array $fields)
    {
        $this->http->LogHeaders = true;

        $this->http->GetURL('https://rewards.heathrow.com/web/lhr/join-page');
        $status = $this->http->ParseForm('registrationForm');

        if (!$status) {
            $this->http->Log('Failed to parse create account form');

            return false;
        }

        $origCountryCode = $fields['Country'];
        $fields['Country'] = self::$countriesMap[$fields['Country']];
        $this->logger->debug('Mapped standard country code "' . $origCountryCode . '" to provider code "' . $fields['Country'] . '"');

        foreach (self::$inputFieldsMap as $awKey => $provKeys) {
            if (!isset($fields[$awKey])) {
                continue;
            }

            if (!is_array($provKeys)) {
                $provKeys = [$provKeys];
            }

            foreach ($provKeys as $provKey) {
                $this->http->SetInputValue($provKey, $fields[$awKey]);
            }
        }

        $phone = '+' . $fields['PhoneCountryCodeNumeric'] . $fields['PhoneAreaCode'] . $fields['PhoneLocalNumber'];
        $this->http->SetInputValue('customer.cardholder.phone', $phone);
        $this->http->SetInputValue('useOldLhrCard', 'false');
        $this->http->SetInputValue('extAttr[extAttr.CRH_EXT_STAFF_FLAG]', '');

        $status = $this->http->PostForm();

        if (!$status) {
            $this->http->Log('Failed to post create account form');

            return false;
        }

        if ($errorMessage = $this->http->FindSingleNode("//label[@id='registrationForm.errors']")) {
            throw new \UserInputError($errorMessage);
        } // Is it always user input error?

        if ($successMessage = $this->http->FindSingleNode("//*[contains(@class,'gray-important-header2') and contains(text(),'registration is complete')]")) {
            $this->ErrorMessage = $successMessage;

            return true;
        }

        return false;
    }

    public function getRegisterFields()
    {
        return [
            'Title' =>
                [
                    'Type'     => 'string',
                    'Caption'  => 'Title',
                    'Required' => true,
                    'Options'  => self::$titles,
                ],
            'FirstName' =>
                [
                    'Type'     => 'string',
                    'Caption'  => 'First Name',
                    'Required' => true,
                ],
            'LastName' =>
                [
                    'Type'     => 'string',
                    'Caption'  => 'Last Name',
                    'Required' => true,
                ],
            'Gender' =>
                [
                    'Type'     => 'string',
                    'Caption'  => 'Gender',
                    'Required' => true,
                    'Options'  => self::$genders,
                ],
            'BirthDay' =>
                [
                    'Type'     => 'integer',
                    'Caption'  => 'Birth Day',
                    'Required' => true,
                ],
            'BirthMonth' =>
                [
                    'Type'     => 'integer',
                    'Caption'  => 'Birth Month',
                    'Required' => true,
                ],
            'BirthYear' =>
                [
                    'Type'     => 'integer',
                    'Caption'  => 'Birth Year',
                    'Required' => true,
                ],
            'Nationality' =>
                [
                    'Type'     => 'string',
                    'Caption'  => 'Nationality',
                    'Required' => true,
                    'Options'  => self::$nationalities,
                ],
            'Email' =>
                [
                    'Type'     => 'string',
                    'Caption'  => 'Email (Your email will also be your login)',
                    'Required' => true,
                ],
            'Password' =>
                [
                    'Type'     => 'string',
                    'Caption'  => 'Password (must be 6 to 10 characters in length and contain both letters and numbers)',
                    'Required' => true,
                ],
            'Country' =>
                [
                    'Type'     => 'string',
                    'Caption'  => '',
                    'Required' => true,
                    'Options'  => self::$countries,
                ],
            'AddressLine1' =>
                [
                    'Type'     => 'string',
                    'Caption'  => 'Address Line 1',
                    'Required' => true,
                ],
            'City' =>
                [
                    'Type'     => 'string',
                    'Caption'  => 'City ',
                    'Required' => true,
                ],
            'PostalCode' =>
                [
                    'Type'     => 'string',
                    'Caption'  => 'Postal Code (If you don’t have one and you live outside of the United Kingdom, please enter ‘None)',
                    'Required' => true,
                ],
            'PhoneCountryCodeNumeric' =>
                [
                    'Type'     => 'string',
                    'Caption'  => '1-3 numbers Phone Country Code',
                    'Required' => true,
                ],
            'PhoneAreaCode' =>
                [
                    'Type'     => 'string',
                    'Caption'  => 'Phone Area Code',
                    'Required' => true,
                ],
            'PhoneLocalNumber' =>
                [
                    'Type'     => 'string',
                    'Caption'  => 'Phone Number',
                    'Required' => true,
                ],
            'PhoneType' =>
                [
                    'Type'     => 'string',
                    'Caption'  => 'Phone Type',
                    'Required' => true,
                    'Options'  => self::$phoneTypes,
                ],
        ];
    }
}
