<?php

namespace AwardWallet\Engine;

class MonthTranslate
{
    public static $MonthNames = [
        "en" => [
            "january"   => 0, "jan" => 0,
            "february"  => 1, "feb" => 1,
            "march"     => 2, "mar" => 2, 'mars' => 2,
            "april"     => 3, "apr" => 3,
            "may"       => 4, "mai" => 4,
            "june"      => 5, "jun" => 5, "juin" => 5,
            "july"      => 6, "jul" => 6,
            "august"    => 7, "aug" => 7,
            "september" => 8, "sep" => 8,
            "october"   => 9, "oct" => 9,
            "november"  => 10, "nov" => 10,
            "december"  => 11, "dec" => 11,
        ],
        "ru" => [
            "январь"  => 0, "янв" => 0, "января" => 0, "янвa" => 1,
            "февраля" => 1, "фев" => 1, "февраль" => 1, "февр" => 1,
            "марта"   => 2, "мар" => 2, "март" => 2, "мрт" => 2, "мартa" => 2,
            "апреля"  => 3, "апр" => 3, "апрель" => 3, "апре" => 3,
            "мая"     => 4, "май" => 4,
            "июн"     => 5, "июня" => 5, "июнь" => 5,
            "июля"    => 6, "июль" => 6, "июл" => 6,
            "августа" => 7, "авг" => 7, "август" => 7, "авгу" => 7,
            "сен"     => 8, "сентябрь" => 8, "сентября" => 8, "сент" => 8,
            "окт"     => 9, "октября" => 9, "октябрь" => 9, "октя" => 9,
            "ноя"     => 10, "ноября" => 10, "ноябрь" => 10, "нояб" => 10,
            "дек"     => 11, "декабрь" => 11, "декабря" => 11, "дека" => 11,
        ],
        "de" => [
            "januar"    => 0, "jan" => 0, "jän" => 0, "jänner" => 0,
            "februar"   => 1, "feb" => 1, "febr" => 1,
            "mae"       => 2, "maerz" => 2, "märz" => 2, "mrz" => 2, "mär" => 2, "mrzch" => 2,
            "apr"       => 3, "april" => 3,
            "mai"       => 4,
            "juni"      => 5, "jun" => 5,
            "jul"       => 6, "juli" => 6,
            "august"    => 7, "aug" => 7,
            "september" => 8, "sep" => 8,
            "oktober"   => 9, "okt" => 9,
            "nov"       => 10, "november" => 10,
            "dez"       => 11, "dezember" => 11,
        ],
        "nl" => [
            "januari"   => 0, "jan" => 0,
            "februari"  => 1, "feb" => 1,
            "maart"     => 2, "mrt" => 2, "maa" => 2,
            "april"     => 3, "apr" => 3,
            "mei"       => 4,
            "juni"      => 5, 'jun' => 5,
            "juli"      => 6, "jul" => 6,
            "augustus"  => 7, "aug" => 7,
            "september" => 8, "sep" => 8,
            "oktober"   => 9, "okt" => 9,
            "november"  => 10, "nov" => 10,
            "december"  => 11, "dec" => 11,
        ],
        "no" => [
            "januar"    => 0, "jan" => 0,
            "februar"   => 1, "feb" => 1, "febr" => 1,
            "mars"      => 2, "mar" => 2,
            "april"     => 3, "apr" => 3,
            "mai"       => 4, "kan" => 4,
            "juni"      => 5, "jun" => 5,
            "juli"      => 6, "jul" => 6,
            "august"    => 7, "aug" => 7,
            "september" => 8, "sept" => 8,
            "oktober"   => 9, "okt" => 9,
            "november"  => 10, "nov" => 10,
            "desember"  => 11, "des" => 11,
        ],
        "es" => [
            "enero"      => 0, "ene" => 0,
            "febrero"    => 1, "feb" => 1,
            "marzo"      => 2, "mar" => 2,
            "abril"      => 3, "abr" => 3,
            "mayo"       => 4, "may" => 4,
            "junio"      => 5, "jun" => 5,
            "julio"      => 6, "jul" => 6,
            "agosto"     => 7, "ago" => 7,
            "septiembre" => 8, "sep" => 8, "sept" => 8, "set" => 8, /*es_PE, es_UY*/ "setiembre" => 8,
            "octubre"    => 9, "oct" => 9,
            "noviembre"  => 10, "nov" => 10,
            "diciembre"  => 11, "dic" => 11,
        ],
        "pt" => [
            "jan"      => 0, "janeiro" => 0,
            "fev"      => 1, "fevereiro" => 1,
            "março"    => 2, "marco" => 2, "mar" => 2,
            "abr"      => 3, "abril" => 3,
            "maio"     => 4, "mai" => 4,
            "jun"      => 5, "junho" => 5,
            "julho"    => 6, "jul" => 6,
            "ago"      => 7, "agosto" => 7,
            "setembro" => 8, "set" => 8,
            "out"      => 9, "outubro" => 9,
            "novembro" => 10, "non" => 10, "nov" => 10,
            "dez"      => 11, "dezembro" => 11, 'dec' => 11,
        ],
        "id" => [
            "januari"   => 0, "jan" => 0,
            "februari"  => 1, "feb" => 1,
            "maret"     => 2, "mar" => 2,
            "april"     => 3, "apr" => 3,
            "mei"       => 4,
            "juni"      => 5, "jun" => 5,
            "juli"      => 6, "jul" => 6,
            "agustus"   => 7, "agu" => 7, "agt" => 7,
            "september" => 8, "sep" => 8,
            "oktober"   => 9, "okt" => 9,
            "november"  => 10, "nov" => 10,
            "desember"  => 11, "des" => 11,
        ],
        "it" => [
            "gen"       => 0, "gennaio" => 0,
            "feb"       => 1, "febbraio" => 1,
            "marzo"     => 2, "mar" => 2,
            "apr"       => 3, "aprile" => 3,
            "maggio"    => 4, "mag" => 4,
            "giu"       => 5, "giugno" => 5,
            "luglio"    => 6, "lug" => 6,
            "ago"       => 7, "agosto" => 7,
            "settembre" => 8, "set" => 8, "sett" => 8,
            "ott"       => 9, "ottobre" => 9,
            "novembre"  => 10, "nov" => 10,
            "dic"       => 11, "dicembre" => 11,
        ],
        "fi" => [
            "tammikuuta"  => 0, "tammi" => 0, 'tammikuu' => 0, 'tammik' => 0,
            "helmikuuta"  => 1, "helmi" => 1, "helmikuu" => 1, "helmik" => 1,
            "maaliskuuta" => 2, "maalis" => 2, 'maaliskuu' => 2, 'maalisk' => 2,
            "huhtikuuta"  => 3, "huhti" => 3, 'huhtikuu' => 3, 'huhtik' => 3,
            "toukokuuta"  => 4, 'touko' => 4, 'toukokuu' => 4, 'toukok' => 4,
            "kesäkuuta"   => 5, 'kesä' => 5, 'kesäkuu' => 5, 'kesäk' => 5,
            "heinäkuuta"  => 6, "heinä" => 6, 'heinäkuu' => 6, 'hein' => 6, 'heinäk' => 6,
            "elokuuta"    => 7, 'elo' => 7, 'elokuu' => 7, 'elok' => 7,
            "syyskuuta"   => 8, "syys" => 8, "syyskuu" => 8, "syysk" => 8,
            "lokakuuta"   => 9, "loka" => 9, "lokakuu" => 9, "lokak" => 9,
            "marraskuuta" => 10, "marras" => 10, 'marraskuu' => 10, 'marrask' => 10,
            "joulukuuta"  => 11, "joulu" => 11, 'joulukuu' => 11, 'jouluk' => 11,
        ],
        "fr" => [
            "janv"     => 0, "janvier" => 0, "jan" => 0,
            "févr"     => 1, "fevrier" => 1, "février" => 1, "fev" => 1, "fevr" => 1, "fév" => 1,
            "mars"     => 2, "mar" => 2,
            "avril"    => 3, "avr" => 3, "avri" => 3,
            "mai"      => 4,
            "juin"     => 5, "jun" => 5, 'jui' => 5,
            "juillet"  => 6, "juil" => 6, "juill" => 6, 'jul' => 6,
            "août"     => 7, "aout" => 7, "aoû" => 7, "aou" => 7,
            "sept"     => 8, "septembre" => 8, 'sep' => 8,
            "oct"      => 9, "octobre" => 9,
            "novembre" => 10, "nov" => 10,
            "decembre" => 11, "décembre" => 11, "déc" => 11, "dec" => 11, "déce" => 11,
        ],
        "da" => [
            "januar"    => 0,    "jan" => 0,
            "februar"   => 1,   "feb" => 1,
            "marts"     => 2,     "mar" => 2,
            "april"     => 3,     "apr" => 3,
            "maj"       => 4,
            "juni"      => 5,      "jun" => 5,
            "juli"      => 6,      "jul" => 6,
            "august"    => 7,    "aug" => 7,
            "september" => 8, "sep" => 8,
            "oktober"   => 9,   "okt" => 9,
            "november"  => 10, "nov" => 10,
            "december"  => 11, "dec" => 11,
        ],
        "tr" => [
            "ocak"    => 0, "oca" => 0,
            "şubat"   => 1, "şub" => 1,
            "mart"    => 2, "mar" => 2,
            "nisan"   => 3, "nis" => 3,
            "mayıs"   => 4, "mayis" => 4, "may" => 4,
            "haziran" => 5, "haz" => 5,
            "temmuz"  => 6, "tem" => 6,
            "ağustos" => 7, "ağu" => 7,
            "eylül"   => 8, "eyl" => 8,
            "ekim"    => 9, "eki" => 9,
            "kasım"   => 10, "kasim" => 10, "kas" => 10,
            "aralık"  => 11, "ara" => 11,
        ],
        "pl" => [
            "styczeń"     => 0, "styczen" => 0, "stycznia" => 0, "sty" => 0,
            "luty"        => 1, "lutego" => 1, "lut" => 1,
            "marzec"      => 2, "marca" => 2, "mar" => 2,
            "kwiecień"    => 3, "kwiecien" => 3, "kwietnia" => 3, "kwi" => 3,
            "maj"         => 4, "maja" => 4,
            "czerwiec"    => 5, "czerwca" => 5, "cze" => 5, "czer" => 5,
            "lipiec"      => 6, "lipca" => 6, 'lip' => 6,
            "sierpien"    => 7, "sierpień" => 7, "sierpnia" => 7, 'sie' => 7,
            "wrzesien"    => 8, "wrzesień" => 8, "września" => 8, "wrz" => 8,
            "pazdziernik" => 9, "październik" => 9, "października" => 9, "październka" => 9, "paź" => 9, "pa" => 9,
            "listopad"    => 10, "listopada" => 10, "lis" => 10,
            "grudzien"    => 11, "grudzień" => 11, "grudnia" => 11, "gru" => 11,
        ],
        "zh" => [
            "一月"  => 0,
            "二月"  => 1,
            "三月"  => 2,
            "四月"  => 3,
            "五月"  => 4,
            "六月"  => 5,
            "七月"  => 6,
            "八月"  => 7,
            "九月"  => 8,
            "十月"  => 9,
            "十一月" => 10,
            "十二月" => 11,
        ],
        "hu" => [
            "január"     => 0, "jan" => 0,
            "február"    => 1, "feb" => 1, "febr" => 1,
            "március"    => 2, "már" => 2, "márc" => 2,
            "április"    => 3, "ápr" => 3,
            "május"      => 4, "máj" => 4,
            "június"     => 5, "jún" => 5,
            "július"     => 6, "júl" => 6,
            "augusztus"  => 7, "aug" => 7,
            "szeptember" => 8, "sze" => 8, "szept" => 8,
            "október"    => 9, "okt" => 9,
            "november"   => 10, "nov" => 10,
            "december"   => 11, "dec" => 11,
        ],
        "sv" => [
            "januari"   => 0, "jan" => 0, "januar" => 0,
            "februari"  => 1, "feb" => 1, "februar" => 1,
            "mars"      => 2, "mar" => 2,
            "april"     => 3, "apr" => 3,
            "maj"       => 4, "mai" => 4,
            "juni"      => 5, "jun" => 5,
            "juli"      => 6, "jul" => 6,
            "augusti"   => 7, "aug" => 7,
            "september" => 8, "sep" => 8,
            "oktober"   => 9, "okt" => 9,
            "november"  => 10, "nov" => 10,
            "december"  => 11, "dec" => 11,
        ],
        "cs" => [
            "ledna"     => 0, "leden" => 0, "led" => 0,
            "února"     => 1, "únor" => 1, "úno" => 1,
            "března"    => 2, "březen" => 2, "bře" => 2,
            "dubna"     => 3, "duben" => 3, "dub" => 3,
            "května"    => 4, "květen" => 4, "kvě" => 4,
            "června"    => 5, "červen" => 5, "čer" => 5, "čen" => 5, "čvn" => 5,
            "července"  => 6, "červenec" => 6, "čvc" => 6, "čec" => 6,
            "srpna"     => 7, "srpen" => 7, "srp" => 7,
            "září"      => 8, "zář" => 8,
            "října"     => 9, "říjen" => 9, "říj" => 9,
            "listopadu" => 10, "listopad" => 10, "lis" => 10,
            "prosince"  => 11, "prosinec" => 11, "pro" => 11,
        ],
        "th" => [
            "มกราคม"     => 0, "ม.ค." => 0, "ม.ค" => 0,  "มค" => 0,
            "กุมภาพันธ์" => 1, "ก.พ." => 1, "ก.พ" => 1, "กพ" => 1,
            "มีนาคม"     => 2, "มี.ค." => 2, "มี.ค" => 2, "มีค" => 2,
            "เมษายน"     => 3, "เม.ย." => 3, "เม.ย" => 3, "เมย" => 3,
            "พฤษภาคม"    => 4, "พ.ค." => 4, "พ.ค" => 4, "พค" => 4,
            "มิถุนายน"   => 5, "มิ.ย." => 5, "มิ.ย" => 5, "มิย" => 5,
            "กรกฎาคม"    => 6, "ก.ค." => 6, "ก.ค" => 6, "กค" => 6,
            "สิงหาคม"    => 7, "ส.ค." => 7, "ส.ค" => 7, "สค" => 7,
            "กันยายน"    => 8, "ก.ย." => 8, "ก.ย" => 8, "กย" => 8,
            "ตุลาคม"     => 9, "ต.ค." => 9, "ต.ค" => 9, "ตค" => 9,
            "พฤศจิกายน"  => 10, "พ.ย." => 10, "พ.ย" => 10, "พย" => 10,
            "ธันวาคม"    => 11, "ธ.ค." => 11, "ธ.ค" => 11, "ธค" => 11,
        ],
        "he" => [
            "ינואר"   => 0,	"ינו" => 0,	"בינואר" => 0,
            "פברואר"  => 1,	"פבר" => 1,	"בפברואר" => 1, "פבר'" => 1,
            "מרץ"     => 2,             	"במרץ" => 2,
            "אפריל"   => 3,	"אפר" => 3,	"באפריל" => 3,
            "מאי"     => 4,             	"במאי" => 4,
            "יוני"    => 5,	"יונ" => 5,	"ביוני" => 5,
            "יולי"    => 6,	"יול" => 6,	"ביולי" => 6,
            "אוגוסט"  => 7,	"אוג" => 7,	"באוגוסט" => 7,	"באוג" => 7,
            "ספטמבר"  => 8,	"ספט" => 8,	"בספטמבר" => 8,
            "אוקטובר" => 9, "אוק" => 9,	"באוקטובר" => 9,
            "נובמבר"  => 10,	"נוב" => 10, "בנובמבר" => 10,
            "דצמבר"   => 11,	"דצמ" => 11, "בדצמבר" => 11,
        ],
        "ro" => [
            "ian" => 0, "ianuarie" => 0,
            "feb" => 1, "februarie" => 1,
            "mar" => 2, "martie" => 2,
            "apr" => 3, "aprilie" => 3,
            "mai" => 4,
            "iun" => 5, "iunie" => 5,
            "iul" => 6, "iulie" => 6,
            "aug" => 7, "august" => 7,
            "sep" => 8, "septembrie" => 8,
            "oct" => 9, "octombrie" => 9,
            "noi" => 10, "noiembrie" => 10,
            "dec" => 11, "decembrie" => 11,
        ],
        "ca" => [
            "gener"    => 0, "gen" => 0,
            "febrer"   => 1, "feb" => 1,
            "març"     => 2, "mar" => 2,
            "abril"    => 3, "abr" => 3,
            "maig"     => 4, "mai" => 4,
            "juny"     => 5, "jun" => 5,
            "juliol"   => 6, "jul" => 6,
            "agost"    => 7, "ag" => 7,
            "setembre" => 8, "set" => 8,
            "octubre"  => 9, "oct" => 9,
            "novembre" => 10, "nov" => 10,
            "desembre" => 11, "des" => 11,
        ],
        "el" => [
            "ιανουάριος"  => 0,  "ιανουαρίου"  => 0,  "ιαν" => 0,
            "φεβρουάριος" => 1,  "φεβρουαρίου" => 1,  "φεβ" => 1,  "φεβρ" => 1,
            "μάρτιος"     => 2,  "μαρτίου"     => 2,  "μαρ" => 2,  "μάρ" => 2,
            "απρίλιος"    => 3,  "απριλίου"    => 3,  "απρ" => 3,
            "μάϊος"       => 4,  "μαΐου"       => 4,  "μαϊ" => 4,  "μάι" => 4, "μαΐ" => 4, "μάιος" => 4,
            "ιούνιος"     => 5,  "ιουνιουν"    => 5,  "ιουν" => 5, "ιούν" => 5, "ιουνίου" => 5,
            "ιούλιος"     => 6,  "ιουλίου"     => 6,  "ιουλ" => 6, "ιούλ" => 6,
            "αύγουστος"   => 7,  "αυγούστου"   => 7,  "αυγ" => 7,  "αύγ" => 7,
            "σεπτέμβριος" => 8,  "σεπτεμβρίου" => 8,  "σεπ" => 8,
            "οκτώβριος"   => 9,  "οκτωβρίου"   => 9,  "οκτ" => 9,
            "νοέμβριος"   => 10, "νοεμβρίου"   => 10, "νοε" => 10, "νοέ" => 10,
            "δεκέμβριος"  => 11, "δεκεμβρίου"  => 11, "δεκ" => 11,
        ],
        "lt" => [
            "sausio"    => 0, "sausis"    => 0, "sau" => 0,
            "vasario"   => 1, "vasaris"   => 1, "vas" => 1,
            "kovo"      => 2, "kovas"      => 2, "kov" => 2,
            "balandžio" => 3, "balandis" => 3, "bal" => 3,
            "gegužės"   => 4, "gegužė"   => 4, "geg" => 4,
            "birželio"  => 5, "birželis"  => 5, "bir" => 5,
            "liepos"    => 6, "liepa"    => 6, "lie" => 6, "lip" => 6,
            "rugpjūčio" => 7, "rugpjūtis" => 7, "rgp" => 7, "rup" => 7,
            "rugsėjo"   => 8, "rugsėjis"   => 8, "rgs" => 8, "rug" => 8,
            "spalio"    => 9, "spalis"    => 9, "spa" => 9, "spl" => 9,
            "lapkričio" => 10, "lapkritis" => 10, "lap" => 10,
            "gruodžio"  => 11, "gruodis"  => 11, "grd" => 11, "gru" => 11,
        ],
        "lv" => [
            "janvāris"   => 0, "janv"  => 0, "jan" => 0,
            "februāris"  => 1, "febr"  => 1, "feb" => 1,
            "martā"      => 2, "marts" => 2, "mar" => 2,
            "aprīlis"    => 3, "apr"   => 3,
            "maijs"      => 4, "maijs" => 4, "mai" => 4,
            "jūnijs"     => 5, "jūn"   => 5,
            "jūlijs"     => 6, "jūl"   => 6,
            "augusts"    => 7, "aug"   => 7,
            "septembris" => 8, "sept"  => 8, "sep" => 8,
            "oktobris"   => 9, "okt"   => 9,
            "novembrī"   => 10, "novembris" => 10, "nov" => 10,
            "decembris"  => 11, "dec"  => 11,
        ],
        "et" => [
            "jaanuar"   => 0,		"jaan" => 0,
            "veebruar"  => 1,	"veebr" => 1,
            "märts"     => 2,
            "aprill"    => 3,		"apr" => 3,
            "mai"       => 4,
            "juuni"     => 5,
            "juuli"     => 6,
            "august"    => 7,		"aug" => 7,
            "september" => 8,	"sept" => 8,
            "oktoober"  => 9,	"okt" => 9,
            "november"  => 10,	"nov" => 10,
            "detsember" => 11,	"dets" => 11,
        ],
        "uk" => [
            "січень"   => 0, "сiч" => 0, "січ" => 0, 'січня' => 0,
            "лютий"    => 1, "лют" => 1, 'лютого' => 1,
            "березень" => 2, "бер" => 2, 'березня' => 2,
            "квітень"  => 3,	"квiт" => 3, "квіт" => 3, 'квітня' => 3, "квi" => 3, "кві" => 3, // its not the same
            "травень"  => 4, "трав" => 4, "тра" => 4, 'травня' => 4,
            "червень"  => 5, "черв" => 5, "чер" => 5, 'червня' => 5,
            "липень"   => 6, "лип" => 6, 'липня' => 6,
            "серпень"  => 7, "серп" => 7, "сер" => 7, 'серпня' => 7,
            "вересень" => 8, "вер" => 8, 'вересня' => 8,
            "жовтень"  => 9, "жовт" => 9, "жов" => 9, 'жовтня' => 9,
            "листопад" => 10, "лист" => 10, "лис" => 10, 'листопада' => 10,
            "грудень"  => 11, "груд" => 11, "гру" => 11, 'грудня' => 11,
        ],
        "is" => [
            "janúar"    => 0, "jan" => 0,
            "febrúar"   => 1, "feb" => 1,
            "mars"      => 2, "mar" => 2,
            "apríl"     => 3, "apr" => 3,
            "maí"       => 4,
            "júní"      => 5, "jún" => 5,
            "júlí"      => 6, "júl" => 6,
            "ágúst"     => 7, "ágú" => 7,
            "september" => 8, "sep" => 8,
            "október"   => 9, "okt" => 9,
            "nóvember"  => 10, "nóv" => 10,
            "desember"  => 11, "des" => 11,
        ],
        "mt" => [
            "jannar"    => 0, "jan" => 0,
            "frar"      => 1, "fra" => 1,
            "marzu"     => 2, "mar" => 2,
            "april"     => 3, "apr" => 3,
            "mejju"     => 4, "mej" => 4,
            "ġunju"     => 5, "ġun" => 5,
            "lulju"     => 6, "lul" => 6,
            "awissu"    => 7, "awi" => 7,
            "settembru" => 8, "set" => 8,
            "ottubru"   => 9, "ott" => 9,
            "novembru"  => 10, "nov" => 10,
            "diċembru"  => 11, "diċ" => 11,
        ],
        "hr" => [
            "siječanj" => 0, "sij" => 0, "siječnja" => 0,
            "veljača"  => 1, "vel" => 1, "veljače" => 1,
            "ožujak"   => 2, "ožu" => 2, "ožujka" => 2,
            "travanj"  => 3, "tra" => 3, "travnja" => 3,
            "svibanj"  => 4, "svi" => 4, "svibnja" => 4,
            "lipanj"   => 5, "lip" => 5, "lipnja" => 5,
            "srpanj"   => 6, "srp" => 6, "srpnja" => 6,
            "kolovoz"  => 7, "kol" => 7, "kolovoza" => 7,
            "rujan"    => 8, "ruj" => 8, "rujna" => 8,
            "listopad" => 9, "lis" => 9, "listopada" => 9,
            "studeni"  => 10, "stu" => 10, "studenog" => 10,
            "prosinac" => 11, "pro" => 11, "prosinca" => 11,
        ],
        "bs" => [
            "januar"    => 0, "jan" => 0,
            "februar"   => 1, "feb" => 1,
            "mart"      => 2, "mar" => 2,
            "april"     => 3, "apr" => 3,
            "maj"       => 4,
            "juna"      => 5, "jun" => 5,
            "juli"      => 6, "jul" => 6,
            "avgust"    => 7, "avg" => 7,
            "septembar" => 8, "sep" => 8,
            "oktobar"   => 9, "okt" => 9,
            "novembar"  => 10, "nov" => 10,
            "decembar"  => 11, "dec" => 11,
        ],
        "ar" => [
            "يناير"  => 0, "ينا" => 0,
            "فبراير" => 1, "فبر" => 1,
            "مارس"   => 2, "مار" => 2,
            "أبريل"  => 3, "أبر" => 3, "ابريل" => 3,
            "مايو"   => 4, "ماي" => 4,
            "يونيو"  => 5, "يون" => 5,
            "يوليو"  => 6, "يول" => 6,
            "أغسطس"  => 7, "أغس" => 7,
            "سبتمبر" => 8, "سبت" => 8,
            "أكتوبر" => 9, "أكت" => 9,
            "نوفمبر" => 10, "نوف" => 10,
            "ديسمبر" => 11, "ديس" => 11,
        ],
        "bg" => [
            "януари"    => 0, "ян" => 0,
            "февруари"  => 1, "февр" => 1, "фев" => 1,
            "март"      => 2,
            "април"     => 3, "апр" => 3,
            "май"       => 4,
            "юни"       => 5,
            "муле"      => 6, "мул" => 6,
            "август"    => 7, "авг" => 7,
            "септември" => 8, "сеп" => 8, "септ" => 8,
            "октомври"  => 9, "окт" => 9,
            "ноември"   => 10, "ноем" => 10,
            "декември"  => 11, "дек" => 11,
        ],
        "gl" => [
            "xaneiro"  => 0,
            "febreiro" => 1,
            "marzo"    => 2,
            "abril"    => 3,
            "maio"     => 4,
            "xuño"     => 5,
            "xullo"    => 6,
            "agosto"   => 7,
            "setembro" => 8,
            "outubro"  => 9,
            "novembro" => 10,
            "decembro" => 11,
        ],
        "sr" => [
            "јануар"    => 0, "јан" => 0,
            "фебруар"   => 1, "феб" => 1,
            "март"      => 2, "мар" => 2,
            "април"     => 3, "апр" => 3,
            "мај"       => 4,
            "јун"       => 5,
            "јул"       => 6,
            "август"    => 7, "авг" => 7,
            "септембар" => 8, "сеп" => 8,
            "октобар"   => 9, "окт" => 9,
            "новембар"  => 10, "нов" => 10,
            "децембар"  => 11, "дец" => 11,
        ],
        "sl" => [
            "januar"    => 0, "jan" => 0, "januarja" => 0,
            "februar"   => 1, "feb" => 1, "februarja" => 1,
            "marec"     => 2, "mar" => 2, "marca" => 2,
            "april"     => 3, "apr" => 3, "aprila" => 3,
            "maj"       => 4, "maja" => 4,
            "junij"     => 5, "jun" => 5, "junija" => 5,
            "julij"     => 6, "jul" => 6, "julija" => 6,
            "avgust"    => 7, "avg" => 7, "avgusta" => 7,
            "september" => 8, "sep" => 8, "septembra" => 8,
            "oktober"   => 9, "okt" => 9, "oktobra" => 9,
            "november"  => 10, "nov" => 10, "novembra" => 10,
            "december"  => 11, "dec" => 11, "decembra" => 11,
        ],
        "sk" => [
            "januára"   => 0, "jan" => 0, "január" => 0,
            "februára"  => 1, "feb" => 1, "február" => 1,
            "marca"     => 2, "mar" => 2, "marec" => 2,
            "apríla"    => 3, "apr" => 3, "apríl" => 3,
            "mája"      => 4, "máj" => 4, "máj" => 4,
            "júna"      => 5, "jún" => 5, "jún" => 5,
            "júla"      => 6, "júl" => 6, "júl" => 6,
            "augusta"   => 7, "aug" => 7, "august" => 7,
            "septembra" => 8, "sep" => 8, "september" => 8,
            "októbra"   => 9, "okt" => 9, "október" => 9,
            "novembra"  => 10, "nov" => 10, "november" => 10,
            "decembra"  => 11, "dec" => 11, "december" => 11,
        ],
        "vi" => [
            "tháng một"      => 0,
            "tháng hai"      => 1,
            "tháng ba"       => 2,
            "tháng tư"       => 3,
            "tháng năm"      => 4, "có thể" => 4,
            "tháng sáu"      => 5,
            "tháng bảy"      => 6,
            "tháng tám"      => 7,
            "tháng chín"     => 8,
            "tháng mười"     => 9,
            "tháng mười một" => 10,
            "tháng mười hai" => 11,
        ],
        "kk" => [
            "қаңтар"     => 0, "қаң" => 0,
            "ақпан"      => 1, "ақп" => 1,
            "наурыз"     => 2, "нау" => 2,
            "сәуір"      => 3, "сәу" => 3,
            "мамыр"      => 4, "мам" => 4,
            "маусым"     => 5, "мау" => 5,
            "шілде"      => 6, "шіл" => 6,
            "тамыз"      => 7, "там" => 7,
            "қыркүйек"   => 8, "қыр" => 8,
            "қазан"      => 9, "қаз" => 9,
            "қараша"     => 10, "қар" => 10,
            "желтоқсан"  => 11, "жел" => 11,
        ],
        "br" => [
            "genver"    => 0, "gen" => 0,
            "cʼhwevrer" => 1, "cʼhwe" => 1,
            "meurzh"    => 2, "meur" => 2,
            "ebrel"     => 3, "ebr" => 3,
            "mae"       => 4, "mae" => 4,
            "mezheven"  => 5, "mezh" => 5,
            "gouere"    => 6, "goue" => 6,
            "eost"      => 7, "eost" => 7,
            "gwengolo"  => 8, "gwen" => 8,
            "here"      => 9, "here" => 9,
            "du"        => 10, "du" => 10,
            "kerzu"     => 11, "kzu" => 11,
        ],
        "ms" => [
            "januari"   => 0, "jan" => 0,
            "februari"  => 1, "feb" => 1,
            "mac"       => 2, "mac" => 2,
            "april"     => 3, "apr" => 3,
            "mei"       => 4, "mei" => 4,
            "jun"       => 5, "jun" => 5,
            "julai"     => 6, "jul" => 6,
            "ogos"      => 7, "ogos" => 7,
            "september" => 8, "sep" => 8,
            "oktober"   => 9, "okt" => 9,
            "november"  => 10, "nov" => 10,
            "disember"  => 11, "dis" => 11,
        ],
        "to" => [
            "sānuali"  => 0, "sān" => 0,
            "fēpueli"  => 1, "fēp" => 1,
            "maʻasi"   => 2, "maʻa" => 2,
            "ʻepeleli" => 3, "ʻepe" => 3,
            "mē"       => 4, "mē" => 4,
            "sune"     => 5, "sun" => 5,
            "siulai"   => 6, "siu" => 6,
            "ʻaokosi"  => 7, "ʻaok" => 7,
            "sepitema" => 8, "sep" => 8,
            "ʻokatopa" => 9, "ʻoka" => 9,
            "nōvema"   => 10, "nōv" => 10,
            "tīsema"   => 11, "tīs" => 11,
        ],
    ];

    private static $OutMonthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

    public static function translate($month, $lang)
    {
        $month = mb_strtolower(trim($month), 'UTF-8');

        if (isset(self::$MonthNames[$lang]) && isset(self::$MonthNames[$lang][$month])) {
            return self::$OutMonthNames[self::$MonthNames[$lang][$month]];
        }

        return false;
    }
}
