#!/usr/bin/env php
<?php

set_time_limit(0);

require_once __DIR__.'/../src/kernel/public.php';

$application = new \Symfony\Component\Console\Application();
$application->addCommands([
    new \AwardWallet\MainBundle\Command\ExtensionCreateCommand(),
    new \AwardWallet\MainBundle\Command\ParserCreateCommand()
]);
$application->run();
