<?php

namespace AwardWallet\Engine\airindia\Email;

use AwardWallet\Schema\Parser\Common\Flight;
use AwardWallet\Schema\Parser\Email\Email;
use PlancakeEmailParser;

// parsers with similar formats: jetairways/ETicketItinerary

class Pdf extends \TAccountChecker
{
    public $mailFiles = "airindia/it-26833153.eml, airindia/it-33650375.eml, airindia/it-33723908.eml, airindia/it-33739730.eml, airindia/it-33799378.eml, airindia/it-34027341.eml, airindia/it-37415228.eml, airindia/it-38937212.eml, airindia/it-38961897.eml, airindia/it-39000808.eml, airindia/it-39031575.eml, airindia/it-39035719.eml, airindia/it-39130606.eml, airindia/it-39183684.eml, airindia/it-39800896.eml, airindia/it-39929210.eml, airindia/it-61405045.eml";

    private $lang = 'en';

    private $detects = [
        'en' => 'THIS ADVICE IS GENERATED BY THE AIR INDIA COMPUTER SYSTEM AND DOES NOT REQUIRE A SIGNATURE',
    ];

    private $from = '/[@\.]airindia\.in/';

    private $prov = 'airindia';

    private $pdfText = '';

    /** @var \HttpBrowser */
    private $pdf;

    public function ParsePlanEmailExternal(PlancakeEmailParser $parser, Email $email)
    {
        $pdfs = $parser->searchAttachmentByName('.*pdf');

        if (0 < count($pdfs)) {
            foreach ($pdfs as $pdfNum) {
                $body = \PDF::convertToText($parser->getAttachmentBody($pdfNum));

                foreach ($this->detects as $detect) {
                    if (false !== stripos($body, $detect)) {
                        $this->pdfText = $body;
                        $this->pdf = clone $this->http;
                        $htmlBody = \PDF::convertToHtml($parser->getAttachmentBody($pdfs[0]));
                        $htmlBody = str_replace(['&nbsp;', chr(194) . chr(160), '&#160;'], ' ', $htmlBody);
                        $htmlBody = html_entity_decode($htmlBody);
                        $this->pdf->SetEmailBody($htmlBody);

                        if (!$this->parseEmail($email)) {
                            return null;
                        }

                        break;
                    }
                }
            }
        }
        $class = explode('\\', __CLASS__);
        $email->setType(end($class) . ucfirst($this->lang));

        if (count($email->getItineraries()) === 1) { //it-39031575.eml
            /** @var Flight $it */
            $it = array_values($email->getItineraries())[0];

            if ($it->getNoConfirmationNumber()
                && count($it->getTravellers()) === 0
                && count($it->getSegments()) === 0
                && $this->re("/^[ ]*Issuing Airline:[ ]*(.*)$/im", $this->pdfText) === ''
                && $this->re("/^[ ]*Issued date:[ ]*(.*)$/im", $this->pdfText) === ''
                && $this->re("/^[ ]*Web Reference:[ ]*(.*)$/im", $this->pdfText) === ''
            ) {
                $email->removeItinerary($it);
                $email->setIsJunk(true);
            }
        }

        return $email;
    }

    public function detectEmailByHeaders(array $headers)
    {
        return isset($headers['from']) && preg_match($this->from, $headers['from']);
    }

    public function detectEmailByBody(PlancakeEmailParser $parser)
    {
        $pdfs = $parser->searchAttachmentByName('.*pdf');

        if (0 < count($pdfs)) {
            foreach ($pdfs as $pdfNum) {
                $pdf = \PDF::convertToText($parser->getAttachmentBody($pdfNum));
                $pdf = str_replace('&#160;', ' ', $pdf);

                if (strpos($pdf, $this->prov) !== false) {
                    foreach ($this->detects as $detect) {
                        if (false !== stripos($pdf, $detect)) {
                            return true;
                        }
                    }
                }
            }
        }

        return false;
    }

    public function detectEmailFromProvider($from)
    {
        return preg_match($this->from, $from);
    }

    private function parseEmail(Email $email): bool
    {
        $f = $email->add()->flight();

        $text = $this->pdfText;


        if (($conf = $this->pdf->FindSingleNode("//text()[starts-with(normalize-space(),'Booking reference no (PNR)') or starts-with(normalize-space(),'Booking Reference (PNR)')]", null, true, '/\s*[:]+\s*([A-Z\d]{5,9})\s*(?:\(|$)/'))
            || ($conf = $this->pdf->FindSingleNode("(//p[normalize-space()='Booking Reference:' or normalize-space()='Booking Reference:']/following::p[normalize-space()][1])[1]", null, true, '/^\s*([A-Z\d]{5,9})\s*(?:\(|$)/'))
        ) {
            $f->general()->confirmation($conf);
        } elseif ($conf = $this->pdf->FindSingleNode("//text()[starts-with(normalize-space(.), 'Booking reference no (PNR)')]", null, true, '/\s*\:\s*\(([A-Z\d]{2})\)\s*$/')) {
            if ($conf = $this->http->FindSingleNode("//text()[contains(normalize-space(),'Booking Reference')]", null, false, "/\#\s*\-\s*([A-Z\d]{5,9})\s*$/")) {
                $f->general()
                    ->confirmation($conf);
            } else {
                $f->general()->noConfirmation();
            }
        }

        $total = $this->pdf->FindSingleNode("//p[contains(normalize-space(.), 'TOTAL TICKET COST')]/following-sibling::p[1]");

        if ($total === null) {
            $total = $this->pdf->FindSingleNode("//p[contains(normalize-space(.), 'TOTAL TICKET AMOUNT')]/following-sibling::p[1]");
        }

        if ($total === null) {
            $total = $this->pdf->FindSingleNode("//p[starts-with(normalize-space(),'TOTAL TRIP COST') or starts-with(normalize-space(),'TOTAL TRIP COST')]/following::p[normalize-space()][1]");
        }

        if (preg_match('/([A-Z]{3})[ ]*(\d[\d., ]+)(?:\s{2,}|\n|$)/', $total, $m)) {
            $f->price()
                ->total($this->amount($m[2]))
                ->currency($m[1]);
        }

        $spent = $this->pdf->FindSingleNode("//p[contains(normalize-space(.), 'Total Points')]/following-sibling::p[1]", null, true, "/^\s*(\d+)\s*$/");
        if (!empty($spent)) {
            $f->price()
                ->spentAwards($spent);
        }

        $info = $this->cutText('PASSENGER/ ITINERARY DETAILS', 'TRAVEL INFORMATION', $text);

        if (empty($info)) {
            $info = $this->cutText('PASSENGER/ITINERARY DETAILS', 'TRAVEL INFORMATION', $text);
        }

        if (empty($info)) {
            $info = $this->cutText('Passenger / Itinerary Details', 'Detailed Itinerary', $text);
        }
        $str = $this->re('/PASSENGER[ ]*\/[ ]*ITINERARY DETAILS.*\n([\s\S]+?)\n[ ]*(?:DEP\n|DATE[ ]+DEP[ ]+TIME)/i', $info);
        $pax = $tickets = $accounts = [];
        $seats = [];
        // get Seats
        if (!empty($str)) {
            $rows = array_filter(explode("\n", $str));

            foreach ($rows as $r) {
                $columns = preg_split("/[ ]{2,}/", trim($r));

                if (stripos($columns[0], 'passenger') === false
                    && preg_match("/^\s*(\D{4,}?)\s*$/", $columns[0], $m)
                    && preg_match('/^[ ]{0,20}' . preg_quote($m[1], '/') . '/m', $str)
                    && !preg_match('/^.{21,}' . preg_quote($m[1], '/') . '/m', $str)
                ) {
                    $pax[] = $m[1];
                }

                if (isset($columns[2]) && preg_match("/^\d{3}(?: | ?- ?)?\d{5,}(?: | ?- ?)?\d{1,3}$/", $columns[2])) {
                    // 0982132114701
                    $tickets[] = $columns[2];
                } elseif (preg_match("/(\d{12,})$/", $r, $m)) {
                    $tickets[] = $m[1];
                }

                if (count($columns) < 3) {
                    continue;
                }

                if (preg_match("/^([A-Z\d ]*\d[A-Z\d]{5,})(?:\.BASE)?$/", $columns[1], $m)) {
                    // AI130847085.BASE
                    $accounts[] = $m[1];
                }
            }

            if (preg_match_all("/^[ ]{3,}(\w+\/\w+)(?:[ ]{3,}|\n|$)/mu", $str, $m)) {
                $pax = array_merge($m[1], $pax);
            }
            $p = [mb_strlen($this->re("#(.+TICKET NO.\(S\))#", $str))];

            if (preg_match_all("#(.+\d{10,})#", $str, $m, PREG_SET_ORDER)) {
                foreach ($m as $v) {
                    $p[] = mb_strlen($v[1]);
                }
            }
            $pos1 = max($p);

            if ($pos1 > 0) {
                $width = 20;

                if (preg_match_all("#^.{" . $pos1 . "}(.{20,}?)( {2,}|\n)#m", $str, $st)) {
                    $width = max(array_map(function ($v) {return mb_strlen($v); }, $st[1]));
                }
                $tableInfo = $this->splitCols($str, [$pos1, $pos1 + $width]);

                $node = $this->re("#SEAT REQUEST\s+(.+)#s", $tableInfo[0]);
                $nodes = implode(' ', array_map(function ($s) {
                    return preg_replace("/\s+/", ' ', $s);
                }, explode(',', $node)));

                if (preg_match_all("#([A-Z]{3}(?:\-)?[A-Z]{3}) (\d{1,3}[A-z])#", $nodes, $m, PREG_SET_ORDER)) {
                    foreach ($m as $v) {
                        $seats[str_replace('-', '', $v[1])][] = $v[2];
                    }
                }
            }
        }

        if (count($pax = array_filter(array_unique($pax))) > 0) {
            $pax = array_values($pax);

            if (preg_match("/^\s*(MR|MS|MRS|MISS) /", $pax[0])) {
                $pax = preg_replace("/^\s*(MR|MS|MRS|MISS) /", '', $pax);
            } elseif (preg_match("/^\s*(.*\/.*)(MR|MS|MRS|MISS)$/", $pax[0], $m)) {
                $htmlTraveller = strtolower($this->http->FindSingleNode("//text()[starts-with(normalize-space(), 'Dear Mr/Mrs')]", null, true, "/Dear Mr\/Mrs (.+),/"));

                if (empty(array_diff(preg_split("/\W+/", $htmlTraveller), preg_split("/\W+/", strtolower($m[1]))))) {
                    $pax = preg_replace("/^\s*(.+?) *\/ *(.+?) *(MR|MS|MRS)$/", '$2 $1', $pax);
                }
                $pax = preg_replace("/^\s*(MR|MS|MRS) /", '', $pax);
            }

            $f->general()->travellers($pax);
        }

        if (count($tickets = array_filter(array_unique($tickets))) > 0) {
            $f->issued()->tickets($tickets, false);
        }

        if (count($accounts = array_filter(array_unique($accounts))) > 0) {
            $f->program()->accounts($accounts, false);
        }

        $sText = $this->cutText('TRAVEL INFORMATION', 'FARE DETAILS', $text);

        if (!$sText) {
            $sText = $this->cutText('Detailed Itinerary', 'Fare Details', $text);
        }

        if (!$sText) {
            $sText = $this->cutText('Detailed Itinerary', 'Important Notes', $text);
        }

        if (preg_match("/(.+ )Baggage\n/", $sText, $m)) {
            // remove column "Baggage"
            $newRowLength = mb_strlen($m[1]);
            $sText = preg_replace("/^(.{{$newRowLength}}).*/m", '$1', $sText);
            $sText = preg_replace("/[ ]+$/m", '', $sText);
        }

        $segments = $this->splitter('/^((?:[ ]*(?:[A-Z\d][A-Z]|[A-Z][A-Z\d]) ?\d+[ ]*\/\s*(?:Operated.*)?\n)?.+\s+\([A-Z]{3}\)\s+.+(?:\n.+)?\s+\([A-Z]{3}\))/m', $sText);

        if (count($segments) === 0) {
            $segments = $this->splitter('/^([ ]*(?:[A-Z\d][A-Z]|[A-Z][A-Z\d]) ?\d+[ ]{2}.+)/m', $sText);
        }
        $segments = array_map(function ($s) {
            if (!empty($str = strstr($s, '* All times are local to airport', true)))
                { return $str; }
            return $s; }, $segments);

        foreach ($segments as $seg) {
            unset($pos0, $pos1, $pos2);
            $s = $f->addSegment();
            $seg = preg_replace("#\n[ ]{0,5}\(\+\d+ \)denotes.+#s", '', $seg);

            if (preg_match("/^([\s\S]+?)\n+[ ]*Operated by[ ]+(.+?)[ ]+-[ ]+((?:Departure:|Arrival:).+?)\s*$/i", $seg, $m)) {
                // it-61405045.eml
                $seg = $m[1];
                $s->airline()->operator($m[2]);

                if (preg_match("/Departure:[ ]*Terminal[ ]*([A-Z\d]+)[ ]*(?:\/|$)/i", $m[3], $matches)) {
                    $s->departure()->terminal($matches[1]);
                }

                if (preg_match("/Arrival:[ ]*Terminal[ ]*([A-Z\d]+)$/i", $m[3], $matches)) {
                    $s->arrival()->terminal($matches[1]);
                }
            }

            if (preg_match("/(?:^|\n)([ ]{0,10}(?:[A-Z\d][A-Z]|[A-Z][A-Z\d])[ ]?\d{1,5}.{0,10}?)(?:[ ]{2,}|\n|$)/u", $seg, $m)) {
                $pos0 = mb_strlen($m[1]);

                // additional position correction
                preg_match_all("/^(.{{$pos0}})(.+)/m", $seg, $rowsMatches);
                $additionalPos = [0];

                foreach ($rowsMatches[2] as $key => $m) {
                    if (preg_match("/\S$/", $rowsMatches[1][$key])
                        && preg_match("/^(\S{1,2})[ ]{2}/", $m)
                    ) {
                        $additionalPos[] = mb_strlen($m[1]);
                    }
                }
                $pos0 += max($additionalPos);
            } elseif (preg_match("/(?:^|\n)([ ]{0,10}(?:[A-Z\d][A-Z]|[A-Z][A-Z\d])[ ]?\d{1,5}.*?)[ ][^\s\/]/u", $seg, $m)) {
                $pos0 = mb_strlen($m[1]);
            }

            if (preg_match("/(?:^|\n)([ ]{0,10}Operated by)/u", $seg, $m)) {//it-39929210.eml
                $pos0_1 = mb_strlen($m[1]);
                $rows = explode("\n", $seg); //it-38961897.eml
                $pos0_2 = 100000;

                foreach ($rows as $row) {
                    if (preg_match("/^([^,]+?,)/u", $row, $m)) {
                        $pos0_2 = min($pos0_2, mb_strlen($m[1]));
                    }
                }
            }

            if (preg_match_all("/(.+(?:[ ]+|Terminal ))[^\n,]+? - (?-i)[A-Z]{1,2}\b/i", $seg, $m, PREG_SET_ORDER)
                || preg_match_all("/(.+[ ]{2})(?:Economy|Business).*\n+.+[ ]{2}(?-i)\([A-Z]{1,2}\)/i", $seg, $m, PREG_SET_ORDER) // it-61405045.eml
            ) {
                if (count($m) <= 2) {// it-39035719.eml
                    $pos2 = mb_strlen($m[0][1]);
                }
            }

            if (!isset($pos0, $pos2)) {
                $this->logger->debug('other format');

                return false;
            }

            if (isset($pos0_1)) {
                $pos0 = max($pos0, $pos0_1);
            }

            if (isset($pos0_2) && ($pos0_2 < $pos2)) {
                $pos0 = max($pos0, $pos0_2);
            }
            $table = $this->splitCols($seg, [0, $pos0, $pos2], [1]);

            if (preg_match("/^\s*(?<airline>[A-Z\d][A-Z]|[A-Z][A-Z\d])\s*(?<flight>\d+)(?:\s+|$)/", $table[0], $m)) {
                $s->airline()
                    ->name($m['airline'])
                    ->number($m['flight']);
            } elseif (preg_match("/^\s*Operated by\s*(?<operator>.+?),\s+(?<airline>[A-Z\d][A-Z]|[A-Z][A-Z\d])\s*(?<flight>\d+)(?:\s+|$)/s", $table[0], $m)) {
                $s->airline()
                    ->name($m['airline'])
                    ->number($m['flight'])
                    ->operator(preg_replace("/\s+/", ' ', $m['operator']));
            }

            if (preg_match("/Operated\s+by\s+(?<oper>[\s\S]+), (?<airline>[A-Z\d][A-Z]|[A-Z][A-Z\d])\s*(?<flight>\d+)(\s+|$)/",
                $table[0], $m)) {
                $s->airline()
                    ->carrierName($m['airline'])
                    ->carrierNumber($m['flight']);

                $operator = trim(preg_replace("#\s+#", " ", $m['oper']));

                if (!empty($operator)) {
                    $s->airline()->operator($operator);
                }
            }

            $routes = $this->splitCols($table[1], $this->rowColsPos($this->inOneRow($table[1])));

            if (count($routes) !== 2) {
                $routes = [];
            }

            if (empty($routes)) {
                $rows = array_filter(array_map('trim', explode("\n", $table[1])));
                $error = false;
                $routes[0] = '';
                $routes[1] = '';

                foreach ($rows as $r) {
                    $v = preg_split("#\s{2,}#", $r);

                    if (count($v) == 2) {
                        $routes[0] .= $v[0] . "\n";
                        $routes[1] .= $v[1] . "\n";

                        continue;
                    }

                    if (preg_match("#^\s*(\w{2,4}, ?\d{1,2} \w+ \d{4},) (\w{2,4}, \d{1,2} \w+.+)#", $r, $m)
                            || preg_match("#^\s*(.+?Terminal \w+) (\d{2}:\d{2}.+)#", $r, $m)) {
                        $routes[0] .= $m[1] . "\n";
                        $routes[1] .= $m[2] . "\n";

                        continue;
                    }

                    $error = true;

                    break;
                }

                if ($error === true) {
                    $routes = [];
                }
            }

            if (empty($routes)) {
                unset($pos);

                if (preg_match_all("/\n(.+[ ]+)\(.+?\), \d{4},/u", $table[1], $m, PREG_SET_ORDER)) {
                    $p = [];

                    foreach ($m as $v) {
                        $p[] = mb_strlen($v[1]);
                    }
                    $p = array_filter($p);

                    if (!empty($p)) {
                        $pos = max($p);
                        $routes = $this->splitCols($table[1], [0, $pos]);
                    }
                }
            }

            if (empty($routes)) {// it-39130606.eml
                $rows = explode("\n", $table[1]);
                $p = 0;

                foreach ($rows as $row) {
                    $str = $this->re("#^(.+?)\b(\d+:\d+)#u", $row);

                    if (!empty($str) && empty($this->re("#^(.+?)\b(\d+:\d+).+?\b\d+:\d+#u", $row))) {
                        $p = max($p, mb_strlen($str));
                    }
                }

                if ($p > 0) {
                    $routes = $this->splitCols($table[1], [0, $p]);
                }
            }

            if (empty($routes)) {// it-39183684.eml
                if (preg_match("#\n(.+?\b\d+:\d+.+?\b\d+:\d+)#u", $table[1], $v)
                    && preg_match("#(.+?\b\d+:\d+.+?)\b(?:\d{4},[ ])?\b\d+:\d+#u", $v[1], $m)) {
                    $p = mb_strlen($m[1]);
                    $routes = $this->splitCols($table[1], [0, $p]);
                }
            }

            /*
                Amritsar (ATQ)
                27SEP18
                (THU), 1445,
                Terminal
            */
            $regexp = "/^\s*"
                . "(?<name>[\s\S]{3,}?)?\s*\((?<code>[A-Z]{3})\)"
                . "\s+(?<date>\d+\D+\d+)"
                . "\s+\(.+?\)\s*,\s+(?<hour>\d{1,2})(?<min>\d{2})"
                . "(?:\s*,\s+Terminal\s*(?<term>\w*))?"
                . "/";

            /*
                London, Heathrow
                Airport (LHR)
                07 Jul 2020
                21:30 hrs
            */
            $regexp2 = "/^\s*"
                . "(?<name>[\s\S]{3,}?)?\s*\((?<code>[A-Z]{3})\)"
                . "\s+(?<date>[\s\S]{2,}?\d{4})"
                . "[,\s]+(?<hour>\d{1,2}):(?<min>\d{2})(?i)(?:\s*hrs)?"
                . "\s*(?:,\s+Terminal\s*(?<term>\w*))?"
                . "/";

            if (!empty($routes[0])
                    && (preg_match($regexp, $routes[0], $m) || preg_match($regexp2, $routes[0], $m))) {
                if (!empty($m['name'])) {
                    $s->departure()->name(preg_replace('/\s+/', ' ', $m['name']));
                }
                $s->departure()
                    ->code($m['code'])
                    ->date(strtotime($m['hour'] . ':' . $m['min'], $this->normalizeDate($m['date'])));

                if (!empty($m['term'])) {
                    $s->departure()->terminal($m['term']);
                }
            }

            if (!empty($routes[1])
                    && (preg_match($regexp, $routes[1], $m) || preg_match($regexp2, $routes[1], $m))) {
                if (!empty($m['name'])) {
                    $s->arrival()->name(preg_replace('/\s+/', ' ', $m['name']));
                }
                $s->arrival()
                    ->code($m['code'])
                    ->date(strtotime($m['hour'] . ':' . $m['min'], $this->normalizeDate($m['date'])));

                if (!empty($m['term'])) {
                    $s->arrival()->terminal($m['term']);
                }
            }

            if (preg_match('/(\d{1,2}[A-Z]\s*\d{1,2}[A-Z])/', $table[2], $m)) {
                $s->extra()
                    ->duration($m[1]);
            }

            if (preg_match('/\n(?<cabin>Economy|Business)\s+-\s+(?-i)(?<bookingCode>[A-Z]{1,2})\b/i', $table[2], $m)
                || preg_match('/^\s*(?<cabin>Economy|Business)\s*\((?-i)(?<bookingCode>[A-Z]{1,2})\)/i', $table[2], $m)
                || preg_match('/^\s*(?<cabin>Economy|Business).*\n+[ ]*(?-i)\((?<bookingCode>[A-Z]{1,2})\)/i', $table[2], $m)
            ) {
                $s->extra()
                    ->cabin($m['cabin'])
                    ->bookingCode($m['bookingCode']);
            }

            if (false !== stripos($table[2], 'Confirmed')) {
                $s->setStatus('Confirmed');
            }

            if (preg_match('/\D(\d{1,2})\s+stops/i', $table[2], $m)) {
                $s->extra()
                    ->stops($m[1]);
            }

            if (preg_match('/\s+(\d{1,2}h ?\d{1,2}m)[\s\/]/i', $table[2], $m)) {
                $s->extra()
                    ->duration($m[1]);
            }

            if ($s->getDepCode() && $s->getArrCode() && isset($seats[$s->getDepCode() . $s->getArrCode()])) {
                $s->extra()->seats($seats[$s->getDepCode() . $s->getArrCode()]);
            }
        }

        return true;
    }

    private function normalizeDate($str)
    {
//        $this->logger->alert($str);
        $in = [
            '/(\d{1,2})\s*([A-Z]+)\s*(\d{2,4})/',
            '/^[\w\-]+,\s+(\d{1,2})\s*(\w+)\s*(\d{2,4})$/',
        ];
        $out = [
            '$1 $2 $3',
            '$1 $2 $3',
        ];

        return strtotime(preg_replace($in, $out, $str));
    }

    /**
     * @return string|bool
     */
    private function cutText(string $start, $end, string $text)
    {
        if (empty($start) || empty($end) || empty($text)) {
            return false;
        }

        if (is_array($end)) {
            $begin = strstr($text, $start);

            foreach ($end as $e) {
                if (strstr($begin, $e, true) !== false) {
                    return strstr($begin, $e, true);
                }
            }
        }

        return strstr(strstr($text, $start), $end, true);
    }

    private function re($re, $str, $c = 1)
    {
        preg_match($re, $str, $m);

        if (isset($m[$c])) {
            return $m[$c];
        }

        return null;
    }

    private function splitter($regular, $text): array
    {
        $result = [];

        $array = preg_split($regular, $text, -1, PREG_SPLIT_DELIM_CAPTURE | PREG_SPLIT_NO_EMPTY);
        array_shift($array);

        for ($i = 0; $i < count($array) - 1; $i += 2) {
            $result[] = $array[$i] . $array[$i + 1];
        }

        return $result;
    }

    private function splitCols($text, $pos = false, $noTrimCol = [])
    {
        $cols = [];
        $rows = explode("\n", $text);

        if (!$pos) {
            $pos = $this->rowColsPos($rows[0]);
        }
        arsort($pos);

        foreach ($rows as $row) {
            foreach ($pos as $k => $p) {
                if (in_array($k, $noTrimCol, true)) {
                    $cols[$k][] = mb_substr($row, $p, null, 'UTF-8');
                } else {
                    $cols[$k][] = trim(mb_substr($row, $p, null, 'UTF-8'));
                }
                $row = mb_substr($row, 0, $p, 'UTF-8');
            }
        }
        ksort($cols);

        foreach ($cols as &$col) {
            $col = implode("\n", $col);
        }

        return $cols;
    }

    private function rowColsPos($row)
    {
        $head = array_filter(array_map('trim', explode("|", preg_replace("#\s{2,}#", "|", $row))));
        $pos = [];
        $lastpos = 0;

        foreach ($head as $word) {
            $pos[] = mb_strpos($row, $word, $lastpos, 'UTF-8');
            $lastpos = mb_strpos($row, $word, $lastpos, 'UTF-8') + mb_strlen($word, 'UTF-8');
        }

        return $pos;
    }

    private function inOneRow($text)
    {
        $textRows = array_filter(explode("\n", $text));
        $length = [];

        foreach ($textRows as $key => $row) {
            $length[] = mb_strlen($row);
        }
        $length = max($length);
        $oneRow = '';

        for ($l = 0; $l < $length; $l++) {
            $notspace = false;

            foreach ($textRows as $key => $row) {
                $sym = mb_substr($row, $l, 1);

                if ($sym !== false && trim($sym) !== '') {
                    $notspace = true;
                    $oneRow[$l] = 'a';
                }
            }

            if ($notspace == false) {
                $oneRow[$l] = ' ';
            }
        }

        return $oneRow;
    }

    private function amount($s)
    {
        $s = trim(str_replace(",", ".", preg_replace("#[., ](\d{3})#", "$1", $this->re("#(\d[\d\,\. ]*)#", $s))));

        if (is_numeric($s)) {
            return (float) $s;
        }

        return null;
    }
}
