<?php

namespace AwardWallet\Engine\hoggrob\Email;

use AwardWallet\Engine\MonthTranslate;
use AwardWallet\Schema\Parser\Email\Email;

class NotificationOfTravel extends \TAccountChecker
{
    public $mailFiles = "";
    public static $dict = [
        'en' => [],
    ];

    private $detectFrom = "@HRGWorldwide.com";
    private $detectSubject = [
        'NO ACTION REQUIRED - Notification of Travel for ',
        'Authorization has been requested for',
    ];
    private $detectCompany = ['Hogg Robinson'];

    private $detectBody = [
        'en' => ['mail has been generated by an automated'],
    ];
    private $lang = 'en';

    public function ParsePlanEmailExternal(\PlancakeEmailParser $parser, Email $email)
    {
        $class = explode('\\', __CLASS__);
        $email->setType(end($class) . ucfirst($this->lang));

        $this->parseEmail($email);

        return $email;
    }

    public function detectEmailByBody(\PlancakeEmailParser $parser)
    {
        $body = $parser->getHTMLBody();

        $finded = false;

        foreach ($this->detectCompany as $dCompany) {
            if (stripos($body, $dCompany) !== false) {
                $finded = true;
            }
        }

        if ($finded == false) {
            return false;
        }

        foreach ($this->detectBody as $detectBody) {
            foreach ($detectBody as $dBody) {
                if (strpos($body, $dBody) !== false) {
                    return true;
                }
            }
        }

        return false;
    }

    public function detectEmailByHeaders(array $headers)
    {
        if (isset($headers['from']) && isset($headers["subject"])) {
            if (stripos($headers['from'], $this->detectFrom) === false) {
                return false;
            }

            foreach ($this->detectSubject as $reSubject) {
                if (stripos($headers["subject"], $reSubject) !== false) {
                    return true;
                }
            }
        }

        return false;
    }

    public function detectEmailFromProvider($from)
    {
        return stripos($from, $this->detectFrom) !== false;
    }

    public static function getEmailLanguages()
    {
        return array_keys(self::$dict);
    }

    public static function getEmailTypesCount()
    {
        return count(self::$dict);
    }

    private function parseFlight(Email $email)
    {
        $xpath = "//text()[{$this->eq($this->t('Departing'))}]/ancestor::tr[1][{$this->contains($this->t('Take Off'))} and ./preceding::tr[normalize-space()][1][{$this->starts($this->t('Air - '))}]]/following-sibling::tr[count(td)>3]";
        //		$this->logger->debug($xpath);
        $nodes = $this->http->XPath->query($xpath);

        if ($nodes->length === 0) {
            $this->logger->debug('flights not found');

            return false;
        }
        $f = $email->add()->flight();
        $f->general()
            ->confirmation($this->http->FindSingleNode("//text()[" . $this->eq($this->t("Record Locator:")) . "]/ancestor::td[1]/following-sibling::td[1]", null, true, "#^\s*([A-Z\d]{5,})\s*$#"))
            ->traveller($this->http->FindSingleNode("//text()[" . $this->eq($this->t("Travel Request For:")) . "]/ancestor::td[1]/following-sibling::td[1]"))
        ;

        foreach ($nodes as $root) {
            $s = $f->addSegment();

            // Airline
            $s->airline()
                ->name($this->http->FindSingleNode("td[1]", $root))
                ->number($this->http->FindSingleNode("td[2]", $root))
            ;

            // Departure
            $s->departure()
                ->noCode()
                ->name($this->http->FindSingleNode("td[5]", $root))
                ->date($this->normalizeDate($this->http->FindSingleNode("td[7]", $root)))
            ;

            // Arrival
            $s->arrival()
                ->noCode()
                ->name($this->http->FindSingleNode("td[6]", $root))
                ->date($this->normalizeDate($this->http->FindSingleNode("td[8]", $root)))
            ;

            // Extra
            $s->extra()
                ->cabin($this->http->FindSingleNode("td[3]", $root))
                ->duration($this->http->FindSingleNode("td[9]", $root))
            ;
        }

        return true;
    }

    private function parseHotel(Email $email)
    {
        $xpath = "//text()[{$this->eq($this->t('Check In'))}]/ancestor::tr[1][{$this->contains($this->t('Address'))} and ./preceding::tr[normalize-space()][1][{$this->starts($this->t('Hotel -'))}]]/following-sibling::tr[count(td)>3]";
        //text()[normalize-space(.) = "Departing"]/ancestor::tr[1][contains(., 'Take Off') and ./preceding::tr[normalize-space()][1][starts-with(normalize-space(), 'Air - ')]]
        //		$this->logger->debug($xpath);
        $nodes = $this->http->XPath->query($xpath);

        if ($nodes->length === 0) {
            $this->logger->debug('hotels not found');

            return false;
        }

        foreach ($nodes as $root) {
            $h = $email->add()->hotel();

            // General
            $h->general()
                ->confirmation($this->http->FindSingleNode("td[7]", $root, true, "#^\s*([A-Z\d]{5,})#"))
                ->traveller($this->http->FindSingleNode("//text()[" . $this->eq($this->t("Travel Request For:")) . "]/ancestor::td[1]/following-sibling::td[1]"))
            ;

            // Hotel
            $h->hotel()
                ->name($this->http->FindSingleNode("td[1]", $root))
                ->address($this->http->FindSingleNode("td[8]", $root))
            ;

            // Booked
            $h->booked()
                ->checkIn($this->normalizeDate($this->http->FindSingleNode("td[3]", $root)))
                ->checkOut($this->normalizeDate($this->http->FindSingleNode("td[4]", $root)))
            ;

            $h->addRoom()
                ->setRate($this->http->FindSingleNode("td[5]", $root));
        }

        return true;
    }

    private function parseEmail(Email $email)
    {
        $email->ota()
            ->confirmation($this->http->FindSingleNode("//text()[" . $this->eq($this->t("Booking Reference:")) . "]/ancestor::td[1]/following-sibling::td[1]", null, true, "#^\s*([A-Z\d]{5,})$#"));

        $total = $this->http->FindSingleNode("//text()[" . $this->eq($this->t("Estimated Total:")) . "]/ancestor::td[1]/following-sibling::td[1]");

        if (preg_match("#(?<total>\d[\d\.\,]*)\s*(?<cur>[A-Z]{3})\b#", $total, $m) || preg_match("#(?<cur>[A-Z]{3})\s*(?<total>\d[\d\.\,]*)\b#", $total, $m)) {
            $email->price()
                ->total($m['total'])
                ->currency($m['cur'])
            ;
        }
        $this->parseFlight($email);
        $this->parseHotel($email);

        return true;
    }

    private function t($s)
    {
        if (!isset($this->lang) || !isset(self::$dict[$this->lang][$s])) {
            return $s;
        }

        return self::$dict[$this->lang][$s];
    }

    private function normalizeDate($date)
    {
        $in = [
            //02 Oct 2018 19:15
            '#^(\d+)\s+(\w+)\s+(\d{4})\s+(\d+:\d+(?:\s*[ap]m)?)$#u',
        ];
        $out = [
            '$1 $2 $3 $4',
        ];

        $date = preg_replace($in, $out, $date);

        if (preg_match("#\d+\s+([^\d\s]+)\s+\d{4}#", $date, $m)) {
            if ($en = MonthTranslate::translate($m[1], $this->lang)) {
                $date = str_replace($m[1], $en, $date);
            }
        }

        return strtotime($date);
    }

    private function eq($field)
    {
        $field = (array) $field;

        if (count($field) == 0) {
            return 'false';
        }

        return implode(' or ', array_map(function ($s) {
            return 'normalize-space(.)="' . $s . '"';
        }, $field));
    }

    private function contains($field)
    {
        $field = (array) $field;

        if (count($field) == 0) {
            return 'false';
        }

        return implode(' or ', array_map(function ($s) {
            return 'contains(normalize-space(.),"' . $s . '")';
        }, $field));
    }

    private function starts($field)
    {
        $field = (array) $field;

        if (count($field) == 0) {
            return 'false';
        }

        return implode(' or ', array_map(function ($s) {
            return 'starts-with(normalize-space(.),"' . $s . '")';
        }, $field));
    }

    private function preg_implode($field)
    {
        if (!is_array($field)) {
            $field = [$field];
        }

        return '(?:' . implode("|", array_map(function ($v) {return preg_quote($v, '#'); }, $field)) . ')';
    }
}
