<?php

namespace AwardWallet\Engine\alaskaair\Transfer;

class Register extends \TAccountCheckerAlaskaair
{
    protected static $primaryDepartureCities = [
        'ADK' => 'Adak Island (ADK)',
        'ABQ' => 'Albuquerque (ABQ)',
        'ANC' => 'Anchorage (ANC)',
        'ATL' => 'Atlanta (ATL)',
        'AUS' => 'Austin (AUS)',
        'BWI' => 'Baltimore-Baltimore Washington (BWI)',
        'BRW' => 'Barrow (BRW)',
        'BLI' => 'Bellingham (BLI)',
        'RDM' => 'Redmond/Bend, OR (RDM)',
        'BET' => 'Bethel (BET)',
        'BIL' => 'Billings (BIL)',
        'BOI' => 'Boise (BOI)',
        'BOS' => 'Boston (BOS)',
        'BZN' => 'Bozeman (BZN)',
        'BUR' => 'Burbank (BUR)',
        'SJD' => 'San Jose del Cabo (SJD)',
        'YYC' => 'Calgary (YYC)',
        'CUN' => 'Cancun (CUN)',
        'CHS' => 'Charleston, SC (CHS)',
        'ORD' => 'Chicago-O\'Hare (ORD)',
        'COS' => 'Colorado Springs (COS)',
        'CDV' => 'Cordova (CDV)',
        'CEC' => 'Crescent City (CEC)',
        'DFW' => 'Dallas-Ft. Worth, TX (DFW)',
        'DEN' => 'Denver (DEN)',
        'DTW' => 'Detroit (DTW)',
        'DLG' => 'Dillingham (DLG)',
        'DUT' => 'Dutch Harbor (DUT)',
        'YEG' => 'Edmonton (YEG)',
        'EUG' => 'Eugene (EUG)',
        'FAI' => 'Fairbanks (FAI)',
        'FLL' => 'Fort Lauderdale (FLL)',
        'FAT' => 'Fresno/Yosemite (FAT)',
        'GST' => 'Glacier Bay/Gustavus (GST)',
        'GTF' => 'Great Falls (GTF)',
        'GDL' => 'Guadalajara (GDL)',
        'GUC' => 'Gunnison (GUC)',
        'HLN' => 'Helena (HLN)',
        'HNL' => 'Honolulu (HNL)',
        'IAH' => 'Houston, TX (IAH)',
        'ZIH' => 'Ixtapa/Zihuatanejo (ZIH)',
        'JNU' => 'Juneau (JNU)',
        'OGG' => 'Kahului/Maui (OGG)',
        'KOA' => 'Kailua/Kona (KOA)',
        'FCA' => 'Kalispell (FCA)',
        'MCI' => 'Kansas City (MCI)',
        'YLW' => 'Kelowna (YLW)',
        'PSC' => 'Pasco/Kennewick (PSC)',
        'KTN' => 'Ketchikan (KTN)',
        'AKN' => 'King Salmon (AKN)',
        'ADQ' => 'Kodiak (ADQ)',
        'OTZ' => 'Kotzebue (OTZ)',
        'LAS' => 'Las Vegas (LAS)',
        'LWS' => 'Lewiston (LWS)',
        'LIR' => 'Liberia (LIR)',
        'LIH' => 'Lihue (LIH)',
        'LTO' => 'Loreto (LTO)',
        'LAX' => 'Los Angeles, CA (LAX)',
        'MMH' => 'Mammoth Lakes/Yosemite (MMH)',
        'ZLO' => 'Manzanillo (ZLO)',
        'MZT' => 'Mazatlan (MZT)',
        'MFR' => 'Medford (MFR)',
        'MKE' => 'Milwaukee (MKE)',
        'MSP' => 'Minneapolis (MSP)',
        'MSO' => 'Missoula (MSO)',
        'MRY' => 'Monterey (MRY)',
        'PUW' => 'Pullman, WA/Moscow, ID (PUW)',
        'BNA' => 'Nashville (BNA)',
        'MSY' => 'New Orleans (MSY)',
        'JFK' => 'New York-Kennedy (JFK)',
        'EWR' => 'Newark-Newark Intl. (EWR)',
        'OME' => 'Nome (OME)',
        'OAK' => 'Oakland (OAK)',
        'OKC' => 'Oklahoma City (OKC)',
        'OMA' => 'Omaha (OMA)',
        'ONT' => 'Ontario, CA, US (ONT)',
        'SNA' => 'Santa Ana/Orange County (SNA)',
        'MCO' => 'Orlando (MCO)',
        'PSP' => 'Palm Springs (PSP)',
        'PSG' => 'Petersburg (PSG)',
        'PHL' => 'Philadelphia (PHL)',
        'PHX' => 'Phoenix (PHX)',
        'PDX' => 'Portland, OR (PDX)',
        'SCC' => 'Prudhoe Bay (SCC)',
        'PVR' => 'Riviera Nayarit (PVR)',
        'RDU' => 'Raleigh (RDU)',
        'RNO' => 'Reno (RNO)',
        'SMF' => 'Sacramento (SMF)',
        'SLC' => 'Salt Lake City (SLC)',
        'SAT' => 'San Antonio (SAT)',
        'SAN' => 'San Diego (SAN)',
        'SFO' => 'San Francisco (SFO)',
        'SJC' => 'San Jose, CA (SJC)',
        'SJO' => 'San Jose, CR (SJO)',
        'SBA' => 'Santa Barbara (SBA)',
        'STS' => 'Sonoma County/Santa Rosa (STS)',
        'SEA' => 'Seattle (SEA)',
        'SIT' => 'Sitka (SIT)',
        'GEG' => 'Spokane (GEG)',
        'STL' => 'St. Louis (STL)',
        'HDN' => 'Steamboat Springs (HDN)',
        'SUN' => 'Sun Valley (SUN)',
        'TPA' => 'Tampa (TPA)',
        'TUS' => 'Tucson (TUS)',
        'YVR' => 'Vancouver, BC (YVR)',
        'YYJ' => 'Victoria (YYJ)',
        'ALW' => 'Walla Walla (ALW)',
        'IAD' => 'Washington, DC-Dulles (IAD)',
        'DCA' => 'Washington, DC-Reagan National (DCA)',
        'EAT' => 'Wenatchee (EAT)',
        'WRG' => 'Wrangell (WRG)',
        'YKM' => 'Yakima (YKM)',
        'YAK' => 'Yakutat (YAK)',
    ];

    protected static $countries = [
        'US' => 'United States',
        'CA' => 'Canada',
        'CR' => 'Costa Rica',
        'MX' => 'Mexico',
        'AF' => 'Afghanistan',
        'AL' => 'Albania',
        'DZ' => 'Algeria',
        'AS' => 'American Samoa',
        'AD' => 'Andorra',
        'AO' => 'Angola',
        'AI' => 'Anguilla',
        'AQ' => 'Antarctica',
        'AG' => 'Antigua And Barbuda',
        'AR' => 'Argentina',
        'AM' => 'Armenia',
        'AW' => 'Aruba',
        'AU' => 'Australia',
        'AT' => 'Austria',
        'AZ' => 'Azerbaijan',
        'BS' => 'Bahamas',
        'BH' => 'Bahrain',
        'BD' => 'Bangladesh',
        'BB' => 'Barbados',
        'BY' => 'Belarus',
        'BE' => 'Belgium',
        'BZ' => 'Belize',
        'BJ' => 'Benin',
        'BM' => 'Bermuda',
        'BT' => 'Bhutan',
        'BO' => 'Bolivia',
        'BQ' => 'Bonaire, Saint Eustatius and Saba',
        'BA' => 'Bosnia And Herzegovina',
        'BW' => 'Botswana',
        'BR' => 'Brazil',
        'IO' => 'British Indian Ocean Territory',
        'VG' => 'British Virgin Islands',
        'BN' => 'Brunei Darussalam',
        'BG' => 'Bulgaria',
        'BF' => 'Burkina Faso',
        'BI' => 'Burundi',
        'KH' => 'Cambodia',
        'CM' => 'Cameroon',
        'CV' => 'Cape Verde',
        'KY' => 'Cayman Islands',
        'CF' => 'Central African Republic',
        'TD' => 'Chad',
        'CL' => 'Chile',
        'CN' => 'China',
        'CX' => 'Christmas Island',
        'CC' => 'Cocos (Keeling) Islands',
        'CO' => 'Colombia',
        'KM' => 'Comoros',
        'CG' => 'Congo',
        'CD' => 'Congo (DRC)',
        'CK' => 'Cook Islands',
        'CI' => 'Cote D`ivoire',
        'HR' => 'Croatia',
        'CU' => 'Cuba',
        'CW' => 'Curacao',
        'CY' => 'Cyprus',
        'CZ' => 'Czech Republic',
        'DK' => 'Denmark',
        'DJ' => 'Djibouti',
        'DM' => 'Dominica',
        'DO' => 'Dominican Republic',
        'TP' => 'East Timor',
        'EC' => 'Ecuador',
        'EG' => 'Egypt',
        'SV' => 'El Salvador',
        'GQ' => 'Equatorial Guinea',
        'ER' => 'Eritrea',
        'EE' => 'Estonia',
        'ET' => 'Ethiopia',
        'FK' => 'Falkland Islands (Malvinas)',
        'FO' => 'Faroe Islands',
        'FJ' => 'Fiji',
        'FI' => 'Finland',
        'FR' => 'France',
        'GF' => 'French Guiana',
        'PF' => 'French Polynesia',
        'GA' => 'Gabon',
        'GM' => 'Gambia',
        'GE' => 'Georgia',
        'DE' => 'Germany',
        'GH' => 'Ghana',
        'GI' => 'Gibraltar',
        'GR' => 'Greece',
        'GL' => 'Greenland',
        'GD' => 'Grenada',
        'GP' => 'Guadeloupe',
        'GU' => 'Guam',
        'GT' => 'Guatemala',
        'GN' => 'Guinea',
        'GW' => 'Guinea-Bissau',
        'GY' => 'Guyana',
        'HT' => 'Haiti',
        'VA' => 'Holy See (Vatican City State)',
        'HN' => 'Honduras',
        'HK' => 'Hong Kong',
        'HU' => 'Hungary',
        'IS' => 'Iceland',
        'IN' => 'India',
        'ID' => 'Indonesia',
        'IQ' => 'Iraq',
        'IE' => 'Ireland',
        'IR' => 'Islamic Republic Of Iran',
        'IL' => 'Israel',
        'IT' => 'Italy',
        'JM' => 'Jamaica',
        'JP' => 'Japan',
        'JO' => 'Jordan',
        'KZ' => 'Kazakhstan',
        'KE' => 'Kenya',
        'KI' => 'Kiribati',
        'KP' => 'Korea (DPRK)',
        'KR' => 'Korea (ROK)',
        'CS' => 'Kosovo',
        'KW' => 'Kuwait',
        'KG' => 'Kyrgyzstan',
        'LA' => 'Laos',
        'LV' => 'Latvia',
        'LB' => 'Lebanon',
        'LS' => 'Lesotho',
        'LR' => 'Liberia',
        'LY' => 'Libya',
        'LI' => 'Liechtenstein',
        'LT' => 'Lithuania',
        'LU' => 'Luxembourg',
        'MO' => 'Macao',
        'MK' => 'Macedonia',
        'MG' => 'Madagascar',
        'MW' => 'Malawi',
        'MY' => 'Malaysia',
        'MV' => 'Maldives',
        'ML' => 'Mali',
        'MT' => 'Malta',
        'MH' => 'Marshall Islands',
        'MQ' => 'Martinique',
        'MR' => 'Mauritania',
        'MU' => 'Mauritius',
        'YT' => 'Mayotte',
        'FM' => 'Micronesia',
        'MD' => 'Moldova, Republic Of',
        'MC' => 'Monaco',
        'MN' => 'Mongolia',
        'ME' => 'Montenegro',
        'MS' => 'Montserrat',
        'MA' => 'Morocco',
        'MZ' => 'Mozambique',
        'MM' => 'Myanmar',
        'NA' => 'Namibia',
        'NR' => 'Nauru',
        'NP' => 'Nepal',
        'NL' => 'Netherlands',
        'NC' => 'New Caledonia',
        'NZ' => 'New Zealand',
        'NI' => 'Nicaragua',
        'NE' => 'Niger',
        'NG' => 'Nigeria',
        'NU' => 'Niue',
        'NF' => 'Norfolk Island',
        'MP' => 'Northern Mariana Islands',
        'NO' => 'Norway',
        'OM' => 'Oman',
        'PK' => 'Pakistan',
        'PW' => 'Palau',
        'PA' => 'Panama',
        'PG' => 'Papua New Guinea',
        'PY' => 'Paraguay',
        'PE' => 'Peru',
        'PH' => 'Philippines',
        'PN' => 'Pitcairn',
        'PL' => 'Poland',
        'PT' => 'Portugal',
        'PR' => 'Puerto Rico',
        'QA' => 'Qatar',
        'RE' => 'Reunion',
        'RO' => 'Romania',
        'RU' => 'Russian Federation',
        'RW' => 'Rwanda',
        'WS' => 'Samoa',
        'SM' => 'San Marino',
        'ST' => 'Sao Tome And Principe',
        'SA' => 'Saudi Arabia',
        'SN' => 'Senegal',
        'RS' => 'Serbia',
        'SC' => 'Seychelles',
        'SL' => 'Sierra Leone',
        'SG' => 'Singapore',
        'SK' => 'Slovakia',
        'SI' => 'Slovenia',
        'SB' => 'Solomon Islands',
        'SO' => 'Somalia',
        'ZA' => 'South Africa',
        'ES' => 'Spain',
        'LK' => 'Sri Lanka',
        'SH' => 'St. Helena',
        'KN' => 'St. Kitts And Nevis',
        'LC' => 'St. Lucia',
        'SX' => 'St. Maarten',
        'PM' => 'St. Pierre And Miquelon',
        'VC' => 'St. Vincent And The Grenadines',
        'SD' => 'Sudan',
        'SR' => 'Suriname',
        'SZ' => 'Swaziland',
        'SE' => 'Sweden',
        'CH' => 'Switzerland',
        'SY' => 'Syrian Arab Republic',
        'TW' => 'Taiwan, R.O.C.',
        'TJ' => 'Tajikistan',
        'TH' => 'Thailand',
        'TG' => 'Togo',
        'TK' => 'Tokelau',
        'TO' => 'Tonga',
        'TT' => 'Trinidad And Tobago',
        'TN' => 'Tunisia',
        'TR' => 'Turkey',
        'TM' => 'Turkmenistan',
        'TC' => 'Turks And Caicos Islands',
        'TV' => 'Tuvalu',
        'UM' => 'U.S. Minor Outlying Islands',
        'VI' => 'U.S. Virgin Islands',
        'UG' => 'Uganda',
        'UA' => 'Ukraine',
        'AE' => 'United Arab Emirates',
        'GB' => 'United Kingdom',
        'TZ' => 'United Republic Of Tanzania',
        'UY' => 'Uruguay',
        'UZ' => 'Uzbekistan',
        'VU' => 'Vanuatu',
        'VE' => 'Venezuela',
        'VN' => 'Viet Nam',
        'WF' => 'Wallis And Futuna',
        'EH' => 'Western Sahara',
        'YE' => 'Yemen',
        'ZM' => 'Zambia',
        'ZW' => 'Zimbabwe',
    ];

    protected static $states = [
        'AL'    => 'Alabama, US',
        'AK'    => 'Alaska, US',
        'AZ'    => 'Arizona, US',
        'AR'    => 'Arkansas, US',
        'CA'    => 'California, US',
        'CO'    => 'Colorado, US',
        'CT'    => 'Connecticut, US',
        'DE'    => 'Delaware, US',
        'FL'    => 'Florida, US',
        'GA'    => 'Georgia, US',
        'HI'    => 'Hawaii, US',
        'ID'    => 'Idaho, US',
        'IL'    => 'Illinois, US',
        'IN'    => 'Indiana, US',
        'IA'    => 'Iowa, US',
        'KS'    => 'Kansas, US',
        'KY'    => 'Kentucky, US',
        'LA'    => 'Louisiana, US',
        'ME'    => 'Maine, US',
        'MD'    => 'Maryland, US',
        'MA'    => 'Massachusetts, US',
        'MI'    => 'Michigan, US',
        'MN'    => 'Minnesota, US',
        'MS'    => 'Mississippi, US',
        'MO'    => 'Missouri, US',
        'MT'    => 'Montana, US',
        'NE'    => 'Nebraska, US',
        'NV'    => 'Nevada, US',
        'NH'    => 'New Hampshire, US',
        'NJ'    => 'New Jersey, US',
        'NM'    => 'New Mexico, US',
        'NY'    => 'New York, US',
        'NC'    => 'North Carolina, US',
        'ND'    => 'North Dakota, US',
        'OH'    => 'Ohio, US',
        'OK'    => 'Oklahoma, US',
        'OR'    => 'Oregon, US',
        'PA'    => 'Pennsylvania, US',
        'RI'    => 'Rhode Island, US',
        'SC'    => 'South Carolina, US',
        'SD'    => 'South Dakota, US',
        'TN'    => 'Tennessee, US',
        'TX'    => 'Texas, US',
        'UT'    => 'Utah, US',
        'VT'    => 'Vermont, US',
        'VA'    => 'Virginia, US',
        'WA'    => 'Washington, US',
        'WV'    => 'West Virginia, US',
        'WI'    => 'Wisconsin, US',
        'WY'    => 'Wyoming, US',
        'AA'    => 'AA - Armed Forces America, US',
        'AE'    => 'AE - Armed Forces Europe, US',
        'AP'    => 'AP - Armed Forces Pacific, US',
        'AS'    => 'American Samoa, US',
        'DC'    => 'District Of Columbia, US',
        'FM'    => 'Federated States Of Micronesia, US',
        'GU'    => 'Guam, US',
        'MH'    => 'Marshall Islands, US',
        'MP'    => 'Northern Mariana Islands, US',
        'PW'    => 'Palau, US',
        'PR'    => 'Puerto Rico, US',
        'VI'    => 'Virgin Islands, US',
        'AB'    => 'Alberta, Canada',
        'BC'    => 'British Columbia, Canada',
        'MB'    => 'Manitoba, Canada',
        'NB'    => 'New Brunswick, Canada',
        'NF'    => 'Newfoundland, Canada',
        'NT'    => 'Northwest Territories, Canada',
        'NS'    => 'Nova Scotia, Canada',
        'NU'    => 'Nunavut, Canada',
        'ON'    => 'Ontario, Canada',
        'PE'    => 'Prince Edward Island, Canada',
        'QC'    => 'Quebec, Canada',
        'SK'    => 'Saskatchewan, Canada',
        'YT'    => 'Yukon Territory, Canada',
        'AGS'   => 'Aguascalientes, Mexico',
        'BCN'   => 'Baja California, Mexico',
        'BCS'   => 'Baja California Sur, Mexico',
        'CAM'   => 'Campeche, Mexico',
        'CHIS'  => 'Chiapas, Mexico',
        'CHIH'  => 'Chihuahua, Mexico',
        'COAH'  => 'Coahuila, Mexico',
        'COL'   => 'Colima, Mexico',
        'DF'    => 'Distrito Federal, Mexico',
        'DGO'   => 'Durango, Mexico',
        'GTO'   => 'Guanajuato, Mexico',
        'GRO'   => 'Guerrero, Mexico',
        'HGO'   => 'Hidalgo, Mexico',
        'JAL'   => 'Jalisco, Mexico',
        'MEX'   => 'Mexico, Mexico',
        'MICH'  => 'Michoacan, Mexico',
        'MOR'   => 'Morelos, Mexico',
        'NAY'   => 'Nayarit, Mexico',
        'NL'    => 'Nuevo Leon, Mexico',
        'OAX'   => 'Oaxaca, Mexico',
        'PUE'   => 'Puebla, Mexico',
        'QRO'   => 'Queretaro, Mexico',
        'QROO'  => 'Quintana Roo, Mexico',
        'SLP'   => 'San Luis Potosi, Mexico',
        'SIN'   => 'Sinaloa, Mexico',
        'SON'   => 'Sonora, Mexico',
        'TAB'   => 'Tabasco, Mexico',
        'TAMPS' => 'Tamaulipas, Mexico',
        'TLAX'  => 'Tlaxcala, Mexico',
        'VER'   => 'Veracruz, Mexico',
        'YUC'   => 'Yucatan, Mexico',
        'ZAC'   => 'Zacatecas, Mexico',
    ];

    public function InitBrowser()
    {
        if (ConfigValue(CONFIG_SITE_STATE) === SITE_STATE_PRODUCTION) {
            parent::InitBrowser();
        } else {
            $this->UseCurlBrowser();
            $this->http->SetProxy('localhost:8000');
        }
    }

    public function registerAccount(array $fields)
    {
        $this->http->GetURL('https://www.alaskaair.com/myaccount/join');

        if (!$this->http->ParseForm('joinForm')) {
            throw new \EngineError('Failed to parse account registration form');
        }

        $fields['Gender'] = ['F' => 'Female', 'M' => 'Male'][$fields['Gender']];
        $fields['FullNumber'] = $fields['PhoneAreaCode'] . $fields['PhoneLocalNumber'];

        foreach ([
            'FirstName' => 'FirstName',
            'MiddleName' => 'MiddleName',
            'LastName' => 'LastName',
            'BirthMonth' => 'BirthMonth',
            'BirthDay' => 'BirthDay',
            'BirthYear' => 'BirthYear',
            'Gender' => 'Gender',
            'PhoneCode' => 'PhoneCountryCodeNumeric',
            'PhoneNumber' => 'FullNumber',
            'Email' => 'Email',
            'ConfirmEmail' => 'Email',
            'PrimaryDepartureCity' => 'PrimaryDepartureCity',
            'MailingCountry' => 'Country',
            'AddressLine1' => 'AddressLine1',
            'AddressLine2' => 'AddressLine2',
            'City' => 'City',
            'MailingState' => 'StateOrProvince',
            'Zip' => 'PostalCode',
            'UserID' => 'Login',
            'Password' => 'Password',
            'PasswordConfirm' => 'Password',
        ] as $name => $key) {
            if (!empty($fields[$key])) {
                $this->http->Form[$name] = $fields[$key];
            }
        }
        $this->http->Form['AlreadyHaveMileagePlanNumber'] = 'false';

        if (!$this->http->PostForm()) {
            if (strpos($this->http->Error, 'Network error 28 - Operation timed out') !== false && strpos($this->http->currentUrl(), 'MyAlaskaAir.aspx?isNewMember=true') !== false) {
                // site looks to lag sometimes on successful registration
                $this->ErrorMessage = 'Registration successful';
                $this->http->Log('page timed out, but url suggests that registration came through');

                return true;
            }

            return false;
        }

        $successXpath = '//p[contains(normalize-space(.), "our new member kit, including your Mileage Plan")]';

        if ($msg = $this->http->FindSingleNode($successXpath)) {
            $this->ErrorMessage = $msg;
            $this->logger->info('Registration succeeded, provider reported: "' . $msg . '"');

            return true;
        }

        if ($error = $this->http->FindSingleNode('//p[contains(text(), "The information you entered matches an existing account")]')) {
            throw new \UserInputError($error);
        }

        if ($errors = $this->http->FindNodes('//*[@class="field-validation-error"]')) {
            $errors = array_unique($errors);

            if (count($errors) > 1) {
                $msg = 'Registration errors: ' . implode('; ', $errors);
            } else {
                $msg = 'Registration error: ' . $errors[0];
            }
            $this->logger->error($msg);

            throw new \UserInputError($msg);
        }

        return false;
    }

    public function getRegisterFields()
    {
        return [
            'FirstName' =>
            [
                'Type'     => 'string',
                'Caption'  => 'First Name (as it appears on your ID)',
                'Required' => true,
            ],
            'MiddleName' => [
                'Type'     => 'string',
                'Caption'  => 'Middle Name (if on ID, as it appears on your ID)',
                'Required' => false,
            ],
            'LastName' =>
            [
                'Type'     => 'string',
                'Caption'  => 'Last Name (as it appears on your ID)',
                'Required' => true,
            ],
            'BirthDay' =>
            [
                'Type'     => 'integer',
                'Caption'  => 'Day of Birth Date',
                'Required' => true,
            ],
            'BirthMonth' =>
            [
                'Type'     => 'integer',
                'Caption'  => 'Month of Birth Date',
                'Required' => true,
            ],
            'BirthYear' =>
            [
                'Type'     => 'integer',
                'Caption'  => 'Year of Birth Date',
                'Required' => true,
            ],
            'Gender' =>
            [
                'Type'     => 'string',
                'Caption'  => 'Gender',
                'Required' => true,
                'Options'  => [
                    'M' => 'Male',
                    'F' => 'Female',
                ],
            ],
            'PrimaryDepartureCity' =>
            [
                'Type'     => 'string',
                'Caption'  => 'Primary Departure City',
                'Required' => true,
                'Options'  => self::$primaryDepartureCities,
            ],
            'PhoneCountryCodeNumeric' =>
            [
                'Type'     => 'integer',
                'Caption'  => 'Numeric Phone Country Code',
                'Required' => true,
            ],
            'PhoneAreaCode' =>
            [
                'Type'     => 'string',
                'Caption'  => 'Phone Area Code',
                'Required' => true,
            ],
            'PhoneLocalNumber' =>
            [
                'Type'     => 'string',
                'Caption'  => 'Phone Number',
                'Required' => true,
            ],
            'Country' =>
            [
                'Type'     => 'string',
                'Caption'  => 'Country of Residence',
                'Required' => true,
                'Options'  => self::$countries,
            ],
            'Email' =>
            [
                'Type'     => 'string',
                'Caption'  => 'Email',
                'Required' => true,
            ],
            'Login' => [
                'Type'     => 'string',
                'Caption'  => 'Use your email or create a User ID with a minimum of 7 characters. It must include at least 1 letter and cannot contain spaces or symbols',
                'Required' => true,
            ],
            'Password' =>
            [
                'Type'     => 'string',
                'Caption'  => 'Password (at least 8 characters and includes 1 uppercase letter, 1 lowercase letter, and 1 number)',
                'Required' => true,
            ],
            'StateOrProvince' =>
            [
                'Type'     => 'string',
                'Caption'  => 'State (required for USA, Canada, Mexico)',
                'Required' => false,
                'Options'  => self::$states,
            ],
            'AddressLine1' =>
            [
                'Type'     => 'string',
                'Caption'  => 'Address Line 1',
                'Required' => true,
            ],
            'AddressLine2' =>
            [
                'Type'     => 'string',
                'Caption'  => 'Address Line 2',
                'Required' => false,
            ],
            'City' =>
            [
                'Type'     => 'string',
                'Caption'  => 'City',
                'Required' => true,
            ],
            'PostalCode' =>
            [
                'Type'     => 'string',
                'Caption'  => 'PostalCode',
                'Required' => true,
            ],
        ];
    }

    // registered creds: johndoe123/P4ssw0rd/yojaxa@olypmall.ru/167616993
}
