<?php

class TAccountCheckerBing extends TAccountChecker
{
    private $href = null;
    private $frmProofs = null;
    private $frmProofsPostURL = null;
    private $emailValue = null;

    public static function GetAccountChecker($accountInfo)
    {
        require_once __DIR__ . '/TAccountCheckerBingSelenium.php';

        return new TAccountCheckerBingSelenium();
    }

    public function LoadLoginForm()
    {
        $this->http->removeCookies();

        if (!$this->http->GetURL("https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=11&ct=" . time() . "&rver=6.0.5286.0&wp=MBI&wreply=http:%2F%2Fwww.bing.com%2FPassport.aspx%3Frequrl%3Dhttp%253a%252f%252fwww.bing.com%252f%253fscope%253dweb%2526setmkt%253den-US%2526setlang%253dmatch%2526FORM%253dW5WA%2526uid%253dC3305BD0&lc=1033&id=264960")) {
            return false;
        }
        $this->http->FormURL = $this->http->FindPreg('/urlPost:\s*\'([^\']*)\'/ims');

        if (!isset($this->http->FormURL)) {
            $this->http->Log("failed to find from link");

            return false;
        }
        $PPFT = $this->http->FindPreg("/<input[^>]+name=\"PPFT\"[^>]+value=\"([^\"]+)\"/ims");

        if (!isset($PPFT)) {
            $this->http->Log("failed to find PPFT");

            return false;
        }
        $this->http->Form = [
            "login"        => $this->AccountFields['Login'],
            "passwd"       => $this->AccountFields['Pass'],
            "type"         => "11",
            "LoginOptions" => "3",
            "NewUser"      => "1",
            "MEST"         => "0",
            "PPSX"         => "PassportRN",
            "PPFT"         => $PPFT,
            "idsbho"       => "1",
            //			"PwdPad" => "",
            "sso" => "0",
            "i1"  => "0",
            "i2"  => "1",
            "i3"  => "612837",
            "i4"  => "0",
            "i7"  => "0",
            "i12" => "1",
            "i13" => "0",
            "i14" => "250",
            "i15" => "314",
            "i16" => "1632",
            "i17" => "0",
        ];

        $this->http->setCookie(
            "_FP",
            "mkt=en-US",
            ".bing.com",
            "/"
        );

        $this->http->setCookie(
           "_FS",
            "ui=#en-US",
           ".bing.com"
          );

        return true;
    }

    public function Login()
    {
        $this->http->PostForm();

        if (($message = $this->http->FindPreg("/sErrTxt:\'([^<]+)/ims"))
            || ($message = $this->http->FindPreg("/sErrTxt:\"([^\"]+)/ims"))) {
            throw new CheckException(stripcslashes($message), ACCOUNT_INVALID_PASSWORD);
        }

        //# Security question. 1 variant
        if ($this->http->FindPreg("/Help us protect your account/ims")) {
            $this->http->Log("Security question. 1 variant");
            $this->AskQuestion('To continue, enter the code generated by your authenticator app');
        }

        if (!$this->http->ParseForm("fmHF")) {
            //# Needed verify email address /*checked*/
            if ($message = $this->http->FindSingleNode('//h3[contains(text(), "Please verify your email address")]')) {
                throw new CheckException($message, ACCOUNT_PROVIDER_ERROR);
            }

            return false;
        }
        $this->http->PostForm();

        //# Security question. 2 variant
        $email = $this->http->FindSingleNode("(//select[@id = 'iProofOptions']/option[contains(@value, '@')])[1]");
        $this->emailValue = $this->http->FindSingleNode("(//select[@id = 'iProofOptions']/option[contains(@value, '@')])[1]/@value");

        if (($this->http->FindPreg("/You haven\'t signed in from this location recently/ims")
                || $this->http->FindPreg("/but we need to make sure you can receive a security code/ims"))
            && isset($email)) {
            $this->http->Log("Security question. 2 variant");
            // for answer
            if ($this->http->ParseForm("frmProofs")) {
                $this->frmProofs = $this->http->Form;
                $this->frmProofsPostURL = $this->http->FormURL;
            }

            if (!empty($this->Answers["You need to verify your account. Please enter code which was sent to the following {$email}"])) {
                $this->ProcessStep(null);
            } else {
                $this->http->Log("Sent code to {$email}");
                $this->http->Form = [];
                $this->http->FormURL = 'https://account.live.com/SendSmsOTT';
                $this->http->Form['action'] = 'FamiliarLocationEasy';
                $this->http->Form['channel'] = 'Email';
                $this->http->Form['cxt'] = $this->http->FindPreg("/sContext:\s*\'([^\']+)/ims");
                $this->http->Form['action'] = $this->http->FindPreg("/sAction:\s*\'([^\']+)/ims");
                // sNetId
                $netid = $this->decodingJSEscapeSequences($this->http->FindPreg("/sNetId:\s*\'([^\']+)/ims"));
                $this->http->Log("netid: $netid");
                $this->http->Form['netid'] = $netid;
                // sProofData
                $destination = $this->decodingJSEscapeSequences($this->http->FindPreg("/sProofData:\s*\'([^\']+)/ims"));
                $this->http->Log("destination: $destination");
                $destination = preg_replace('/(.+\|\|)/ims', '', $destination);
                $destination = preg_replace('/(\|.+)/ims', '', $destination);
                $this->http->Log("destination: $destination");
                $this->http->Form['destination'] = $destination;
                $this->http->PostForm();
                $this->AskQuestion("You need to verify your account. Please enter the code which was sent to the following email: {$email}"); /*checked*/
            }
        }

        if ($message = $this->http->FindSingleNode('//span[contains(text(),"Initialize Your Account")]/..')) {
            throw new CheckException($message, ACCOUNT_INVALID_PASSWORD);
        }

        if ($message = $this->http->FindPreg("/((?:Your)? account has been (?:temporarily)? blocked)/ims")) {
            throw new CheckException($message, ACCOUNT_LOCKOUT);
        }

        //# Need create a new password
        elseif ($message = $this->http->FindPreg('/(Before you can sign in to Windows Live, you need to create a new password.)/ims')) {
            throw new CheckException($message, ACCOUNT_INVALID_PASSWORD);
        }
        //# We need you to add some security info for your account
        if ($message = $this->http->FindSingleNode("//h3[contains(text(), 'We need you to add some security info for your account')]")) {
            throw new CheckException($message, ACCOUNT_PROVIDER_ERROR);
        }
        //# To finish signing in, enter the missing information, or unlink the account
        if ($this->http->FindPreg("/To finish signing in, enter the missing information, or unlink the account\./ims")) {
            throw new CheckException("The account you're signing in to is linked to an account that is missing some required information. To finish signing in, enter the missing information, or unlink the account.", ACCOUNT_PROVIDER_ERROR);
        }
        //# Our server is having a problem. We're working to fix it as soon as we can, so try again in a few minutes.
//        if ($message = $this->http->FindPreg("/(Our server is having a problem. We\&\#39;re working to fix it as soon as we can, so try again in a few minutes\.)/ims"))
//            throw new CheckException($message, ACCOUNT_PROVIDER_ERROR);

        $this->href = $this->http->FindPreg("/window\.location\.href=\'([^\'<]+)/ims");
        $this->href = str_replace('\\', '', $this->href);
        $this->http->Log("href ->" . var_export($this->href, true), true);

        if (isset($this->href) && !empty($this->href)) {
            $this->http->GetURL($this->href);

            if ($this->http->Response['code'] == 200) {
                return true;
            }
        }
        //# Form id = 'idForm'
        elseif ($this->http->ParseForm("idForm")) {
            $this->http->PostForm();
        }

        if ($message = $this->http->FindPreg("/((?:Your)? account has been\s*(?:temporarily)? blocked)/ims")) {
            throw new CheckException($message, ACCOUNT_LOCKOUT);
        }

        //$this->http->GetURL("http://www.bing.com:80/start?publ=BING&amp;amp;crea=ME");
        if ($this->http->FindSingleNode("//a[@id = 'sw_tll']/span[1]")) {
            return true;
        }

        if ($this->http->FindSingleNode("//a[contains(@href, 'logout')]/@href")) {
            return true;
        }

        //# Bing services aren't available right now
        if ($message = $this->http->FindSingleNode('//div[contains(text(), "Bing services aren\'t available right now")]')) {
            throw new CheckException($message, ACCOUNT_PROVIDER_ERROR);
        }

        //# Your account has been temporarily blocked
        if ($this->http->ParseForm("idForm")) {
            $this->http->PostForm();
        }

        if ($message = $this->http->FindPreg("/((?:Your)? account has been (?:temporarily)? blocked)/ims")) {
            throw new CheckException($message, ACCOUNT_LOCKOUT);
        }

        return false;
    }

    public function decodingJSEscapeSequences($string)
    {
        $out = preg_replace_callback(
            "(\\\\x([0-9a-f]{2}))i",
            function ($a) {return chr(hexdec($a[1])); },
            $string
        );

        return $out;
    }

    public function ProcessStep($step)
    {
        $this->http->Log("ProcessStep");

        if (($this->http->ParseForm("frmProofs")
            // if was getting another page
            || ((!is_null($this->frmProofs) && !is_null($this->frmProofs))
                && CleanXMLValue($this->http->Response['body'] == '0')))
            && isset($this->Answers[$this->Question])) {
            // Get public key
            $this->http->GetURL("https://login.live.com/ppsecure/JSPublicKey.srf");
            $iPublicKey = $this->http->FindPreg("/SKI=\"([^\"]+)/ims");
            $this->http->Log("iPublicKey: " . $iPublicKey);

            if (isset($this->frmProofs, $this->frmProofsPostURL)) {
                $this->http->Form = $this->frmProofs;
                $this->http->FormURL = $this->frmProofsPostURL;
            }
            $this->http->Log("Security question. 2 variant");
            $this->http->Log("entering code");

            if (is_null($this->emailValue)) {
                $this->$this->emailValue = $this->http->FindSingleNode("(//select[@id = 'iProofOptions']/option[contains(@value, '@')]/@value)[1]");
            }
            $this->http->Form['iProofOptions'] = $this->emailValue;
            $this->http->Form['iOttText'] = $this->Answers[$this->Question];
            $this->http->Form['DisplayPhoneCountryISO'] = 'US';
            // iPublicKey
            $this->http->Form['iPublicKey'] = $iPublicKey;
        } else {
            $this->http->Log("Security question. 1 variant");
            $this->http->Form['AddFD'] = '1';
            $this->http->Form['PPFT'] = $this->http->FindPreg("/sFT:\'([^\']+)/ims");
            $this->http->Form['SentProofID'] = '7977509524275416596';
            $this->http->Form['i14'] = '114';
            $this->http->Form['i15'] = '168';
            $this->http->Form['i16'] = '1105';
            $this->http->Form['i17'] = '0';
            $this->http->Form['i18'] = '__SA_WLStrings|1,__SAWorkflow|1,';
            $this->http->Form['i2'] = '16';
            $this->http->Form['i3'] = '25877';
            $this->http->Form['i7'] = '0';
            $this->http->Form['AddFD'] = '1';
            $this->http->Form['login'] = $this->AccountFields['Login'];
            $this->http->Form["otc"] = $this->Answers[$this->Question];
            $this->http->Form['sacxt'] = '1';
            $this->http->Form['type'] = '19';

            $url = $this->http->FindPreg('/urlPost:\s*\'([^\']*)\'/ims');

            if (isset($url) && !empty($url)) {
                $this->http->FormURL = 'https://login.live.com/ppsecure/post.srf?' . urldecode($url);
            } else {
                return false;
            }
        }

        if (!$this->http->PostForm()) {
            return false;
        }

        if ($this->http->ParseForm("PostForm")) {
            $this->http->PostForm();
        }

        if ($this->http->FindPreg("/Help us protect your account/ims")) {
            $this->http->Log("Security question. 2 variant");
            $this->AskQuestion('To continue, enter the code generated by your authenticator app');

            return false;
        }

        //# Security question. 2 variant
        $email = $this->http->FindSingleNode("(//select[@id = 'iProofOptions']/option[contains(@value, '@')])[1]");

        if (($this->http->FindPreg("/You haven\'t signed in from this location recently/ims")
                || $this->http->FindPreg("/but we need to make sure you can receive a security code/ims"))
            && isset($email)) {
            $this->http->Log("Security question. 2 variant");
            $this->sendNotification("bing / " . $this->Answers[$this->Question]);
//            $this->AskQuestion("You need to verify your account. Please enter the code which was sent to the following email: {$email}");/*checked*/
            return false;
        }

        return true;
    }

    public function Parse()
    {
        $this->http->GetURL("http://www.bing.com/rewards/dashboard");
        //# Lifetime credits
        $this->SetProperty("LifetimeCredits", $this->http->FindSingleNode("//div[span[contains(text(), 'Lifetime Credits')]]/following-sibling::div[1]"));
//        if (!isset($this->Properties['Name']))
//            $this->SetProperty("Name", $this->http->FindSingleNode("//span[@class = 'sw_u']"));

        // It's working
        /*        $this->http->PostURL(
                        "http://www.bing.com/rewardsapp/reportActivity",
                         array(
                                "V" => "web",
                                "url" => "http://www.bing.com/rewards/offers",
                                )
                    );
                ## Balance
                if (!$this->SetBalance($this->http->FindPreg("/credit\"\,\"([^\"<]+)/ims")))
                    $this->SetBalance($this->http->FindPreg("/\.innerHTML = \'([^\']+)/ims"));*/

        // Page with Balance and status
//        $this->http->GetURL('http://www.bing.com/rewardsapp/flyoutpage?style=v2');

        //# Balance - Available Credits
        $this->SetBalance($this->http->FindSingleNode("//div[span[contains(text(), 'Available Credits')]]/following-sibling::div[1]"));
        //# Level
        $this->SetProperty("Level", $this->http->FindSingleNode("//div[@class = 'level-label']"));

        //# Link - 'Join Rewards now'
        if (($this->http->FindPreg("/Only Bing Rewards members get rewarded/ims"))
                && !isset($this->Properties['Level'])) {
            throw new CheckException(self::NOT_MEMBER_MSG, ACCOUNT_PROVIDER_ERROR);
        }

        $this->http->GetURL("https://ssl.bing.com/rewards/settings/profileframed");
        //# Name
        $this->SetProperty("Name", beautifulName($this->http->FindSingleNode("//p[contains(@class, 'name')]")));
    }

    public function GetRedirectParams($targetURL = null)
    {
        $arg = parent::GetRedirectParams($targetURL);
        $arg['CookieURL'] = 'http://www.bing.com/rewards/signup/SignIn?landingAction=Web';
        $arg['SuccessURL'] = 'http://www.bing.com:80/start?publ=BING&amp;amp;crea=ME';

        return $arg;
    }
}
