<?php

namespace AwardWallet\Engine\turkish\RewardAvailability\Helpers;

class FormFieldsInformation
{
    public static $states = [
        'AL' => '1',
        'AK' => '2',
        'AZ' => '3',
        'AR' => '4',
        'CA' => '5',
        'CO' => '6',
        'CT' => '7',
        'DE' => '8',
        'DC' => '9',
        'FL' => '10',
        'GA' => '11',
        'HI' => '12',
        'ID' => '13',
        'IL' => '14',
        'IN' => '15',
        'IA' => '16',
        'KS' => '17',
        'KY' => '18',
        'LA' => '19',
        'ME' => '20',
        'MD' => '21',
        'MA' => '22',
        'MI' => '23',
        'MN' => '24',
        'MS' => '25',
        'MO' => '26',
        'MT' => '27',
        'NE' => '28',
        'NV' => '29',
        'NH' => '30',
        'NJ' => '31',
        'NM' => '32',
        'NY' => '33',
        'NC' => '34',
        'ND' => '35',
        'OH' => '36',
        'OK' => '37',
        'OR' => '38',
        'PA' => '39',
        'RI' => '40',
        'SC' => '41',
        'SD' => '42',
        'TN' => '43',
        'TX' => '44',
        'UT' => '45',
        'VT' => '46',
        'VA' => '47',
        'WA' => '48',
        'WV' => '49',
        'WI' => '50',
        'WY' => '51',
    ];

    private static $genders = [
        'male'   => 'Male',
        'female' => 'Female',
    ];

    private static $zipCodes = [
        '35005' => 'AL',
        '99501' => 'AK',
        '85002' => 'AZ',
        '71603' => 'AR',
        '96106' => 'CA',
        '80001' => 'CO',
        '06001' => 'CT',
        '20011' => 'DC',
        '19701' => 'DE',
        '32007' => 'FL',
        '30002' => 'GA',
        '96701' => 'HI',
        '83204' => 'ID',
        '46001' => 'IN',
        '50003' => 'IA',
        '60042' => 'IL',
        '66025' => 'KS',
        '40022' => 'KY',
        '70001' => 'LA',
        '03901' => 'ME',
        '21930' => 'MD',
        '01001' => 'MA',
        '48003' => 'MI',
        '55001' => 'MN',
        '38601' => 'MS',
        '65899' => 'MO',
        '59001' => 'MT',
        '68001' => 'NE',
        '89830' => 'NV',
        '03031' => 'NH',
        '07001' => 'NJ',
        '87005' => 'NM',
        '14925' => 'NY',
        '27009' => 'NC',
        '58001' => 'ND',
        '43001' => 'OH',
        '73001' => 'OK',
        '97004' => 'OR',
        '15004' => 'PA',
        '02801' => 'RI',
        '29001' => 'SC',
        '57002' => 'SD',
        '37010' => 'TN',
        '73301' => 'TX',
        '84002' => 'UT',
        '05907' => 'VT',
        '20101' => 'VA',
        '98002' => 'WA',
        '26886' => 'WV',
        '53001' => 'WI',
        '82001' => 'WY',
    ];

    public static function getRegisterFields()
    {
        return [
            'FirstName' => [
                'Type'     => 'string',
                'Caption'  => 'First Name (Must 2-30 only characters)',
                'Required' => true,
            ],
            'LastName' => [
                'Type'     => 'string',
                'Caption'  => 'Last Name (Must 2-30 only characters)',
                'Required' => true,
            ],
            'BirthdayDate' => [
                'Type'     => 'date',
                'Caption'  => 'Your date of birth, older than 18 (MM/DD/YYYY)',
                'Required' => true,
            ],
            'Gender' => [
                'Type'     => 'string',
                'Caption'  => 'Gender',
                'Required' => true,
                'Options'  => static::$genders,
            ],
            'State' => [
                'Type'     => 'string',
                'Caption'  => 'Country name',
                'Required' => true,
                'Options'  => static::$states,
            ],
            'ZipCode' => [
                'Type'     => 'string',
                'Caption'  => 'Zip Code',
                'Required' => true,
                'Options'  => static::$zipCodes,
            ],
            'Address' => [
                'Type'     => 'string',
                'Caption'  => 'Address (Must 0-29 characters or numbers long (include . , / \ and space) )',
                'Required' => true,
            ],
            'Email' => [
                'Type'     => 'string',
                'Caption'  => 'Email (max length 50) unique',
                'Required' => true,
            ],
            'PhoneNumber' => [
                'Type'     => 'string',
                'Caption'  => 'Phone Number (10 numbers length)',
                'Required' => true,
            ],
            'Password' => [
                'Type'     => 'string',
                'Caption'  => 'Password (6 unique numbers)',
                'Required' => true,
            ],
            //            'Answer' => [
            //                'Type'     => 'string',
            //                'Caption'  => 'Answer (max length 20)',
            //                'Required' => true,
            //            ],
        ];
    }
}
