<?php

namespace AwardWallet\Engine\finnair\RewardAvailability\Helpers;

class FormFieldsInformationBD
{
    public static $countries_phone_number_length = [
        'AD' => ['label' => 'Andorra', 'phone' => '376', 'length' => 6],
        'AE' => ['label' => 'United Arab Emirates', 'phone' => '971', 'length' => 9],
        'AF' => ['label' => 'Afghanistan', 'phone' => '93', 'length' => 9],
        'AG' => ['label' => 'Antigua and Barbuda', 'phone' => '1-268', 'length' => 10],
        'AI' => ['label' => 'Anguilla', 'phone' => '1-264', 'length' => 10],
        'AL' => ['label' => 'Albania', 'phone' => '355', 'length' => 9],
        'AM' => ['label' => 'Armenia', 'phone' => '374', 'length' => 6],
        'AO' => ['label' => 'Angola', 'phone' => '244', 'length' => 9],
        'AQ' => ['label' => 'Antarctica', 'phone' => '672', 'length' => 6],
        'AR' => ['label' => 'Argentina', 'phone' => '54', 'length' => [6, 7, 8]],
        'AS' => ['label' => 'American Samoa', 'phone' => '1-684', 'length' => 10],
        'AT' => ['label' => 'Austria', 'phone' => '43', 'length' => [10, 11]],
        'AU' => ['label' => 'Australia', 'phone' => '61', 'length' => 9],
        'AW' => ['label' => 'Aruba', 'phone' => '297', 'length' => 7],
        'AX' => ['label' => 'Alland Islands', 'phone' => '358', 'length' => [7, 8, 9, 10]],
        'AZ' => ['label' => 'Azerbaijan', 'phone' => '994', 'length' => 9],
        'BA' => ['label' => 'Bosnia and Herzegovina', 'phone' => '387', 'length' => 8],
        'BB' => ['label' => 'Barbados', 'phone' => '1-246', 'length' => 10],
        'BD' => ['label' => 'Bangladesh', 'phone' => '880', 'length' => 10],
        'BE' => ['label' => 'Belgium', 'phone' => '32', 'length' => 9],
        'BF' => ['label' => 'Burkina Faso', 'phone' => '226', 'length' => 8],
        'BG' => ['label' => 'Bulgaria', 'phone' => '359', 'length' => 9],
        'BH' => ['label' => 'Bahrain', 'phone' => '973', 'length' => 8],
        'BI' => ['label' => 'Burundi', 'phone' => '257', 'length' => 8],
        'BJ' => ['label' => 'Benin', 'phone' => '229', 'length' => 8],
        'BL' => ['label' => 'Saint Barthelemy', 'phone' => '590', 'length' => 9],
        'BM' => ['label' => 'Bermuda', 'phone' => '1-441', 'length' => 10],
        'BN' => ['label' => 'Brunei Darussalam', 'phone' => '673', 'length' => 7],
        'BO' => ['label' => 'Bolivia', 'phone' => '591', 'length' => 9],
        'BR' => ['label' => 'Brazil', 'phone' => '55', 'length' => 11],
        'BS' => ['label' => 'Bahamas', 'phone' => '1-242', 'length' => 10],
        'BT' => ['label' => 'Bhutan', 'phone' => '975', 'length' => 7],
        'BV' => ['label' => 'Bouvet Island', 'phone' => '47', 'length' => 10],
        'BW' => ['label' => 'Botswana', 'phone' => '267', 'length' => 7],
        'BY' => ['label' => 'Belarus', 'phone' => '375', 'length' => 9],
        'BZ' => ['label' => 'Belize', 'phone' => '501', 'length' => 7],
        'CA' => ['label' => 'Canada', 'phone' => '1', 'length' => 10],
        'CC' => ['label' => 'Cocos (Keeling) Islands', 'phone' => '61', 'length' => 10],
        'CD' => ['label' => 'Congo, Democratic Republic of the', 'phone' => '243', 'length' => 7],
        'CF' => ['label' => 'Central African Republic', 'phone' => '236', 'length' => 8],
        'CG' => ['label' => 'Congo, Republic of the', 'phone' => '242', 'length' => 9],
        'CH' => ['label' => 'Switzerland', 'phone' => '41', 'length' => 9],
        'CI' => ['label' => "Cote d'Ivoire", 'phone' => '225', 'length' => 8],
        'CK' => ['label' => 'Cook Islands', 'phone' => '682', 'length' => 5],
        'CL' => ['label' => 'Chile', 'phone' => '56', 'length' => 9],
        'CM' => ['label' => 'Cameroon', 'phone' => '237', 'length' => 9],
        'CN' => ['label' => 'China', 'phone' => '86', 'length' => 11],
        'CO' => ['label' => 'Colombia', 'phone' => '57', 'length' => 10],
        'CR' => ['label' => 'Costa Rica', 'phone' => '506', 'length' => 8],
        'CU' => ['label' => 'Cuba', 'phone' => '53', 'length' => 8],
        'CV' => ['label' => 'Cape Verde', 'phone' => '238', 'length' => 7],
        'CW' => ['label' => 'Curacao', 'phone' => '599', 'length' => 7],
        'CX' => ['label' => 'Christmas Island', 'phone' => '61', 'length' => 9],
        'CY' => ['label' => 'Cyprus', 'phone' => '357', 'length' => 8],
        'CZ' => ['label' => 'Czech Republic', 'phone' => '420', 'length' => 9],
        'DE' => ['label' => 'Germany', 'phone' => '49', 'length' => 10],
        'DJ' => ['label' => 'Djibouti', 'phone' => '253', 'length' => 10],
        'DK' => ['label' => 'Denmark', 'phone' => '45', 'length' => 8],
        'DM' => ['label' => 'Dominica', 'phone' => '1-767', 'length' => 10],
        'DO' => ['label' => 'Dominican Republic', 'phone' => '1-809', 'length' => 10],
        'DZ' => ['label' => 'Algeria', 'phone' => '213', 'length' => 9],
        'EC' => ['label' => 'Ecuador', 'phone' => '593', 'length' => 9],
        'EE' => ['label' => 'Estonia', 'phone' => '372', 'length' => 8],
        'EG' => ['label' => 'Egypt', 'phone' => '20', 'length' => 10],
        'EH' => ['label' => 'Western Sahara', 'phone' => '212', 'length' => 9],
        'ER' => ['label' => 'Eritrea', 'phone' => '291', 'length' => 7],
        'ES' => ['label' => 'Spain', 'phone' => '34', 'length' => 9],
        'ET' => ['label' => 'Ethiopia', 'phone' => '251', 'length' => 9],
        'FI' => ['label' => 'Finland', 'phone' => '358', 'length' => [9, 10, 11]],
        'FJ' => ['label' => 'Fiji', 'phone' => '679', 'length' => 7],
        'FK' => ['label' => 'Falkland Islands (Malvinas)', 'phone' => '500', 'length' => 5],
        'FM' => ['label' => 'Micronesia, Federated States of', 'phone' => '691', 'length' => 7],
        'FO' => ['label' => 'Faroe Islands', 'phone' => '298', 'length' => 5],
        'FR' => ['label' => 'France', 'phone' => '33', 'length' => 9],
        'GA' => ['label' => 'Gabon', 'phone' => '241', 'length' => 7],
        'GB' => ['label' => 'United Kingdom', 'phone' => '44', 'length' => 10],
        'GD' => ['label' => 'Grenada', 'phone' => '1-473', 'length' => 10],
        'GE' => ['label' => 'Georgia', 'phone' => '995', 'length' => 9],
        'GF' => ['label' => 'French Guiana', 'phone' => '594', 'length' => 9],
        'GG' => ['label' => 'Guernsey', 'phone' => '44', 'length' => 10],
        'GH' => ['label' => 'Ghana', 'phone' => '233', 'length' => 9],
        'GI' => ['label' => 'Gibraltar', 'phone' => '350', 'length' => 8],
        'GL' => ['label' => 'Greenland', 'phone' => '299', 'length' => 6],
        'GM' => ['label' => 'Gambia', 'phone' => '220', 'length' => 7],
        'GN' => ['label' => 'Guinea', 'phone' => '224', 'length' => 9],
        'GP' => ['label' => 'Guadeloupe', 'phone' => '590', 'length' => 9],
        'GQ' => ['label' => 'Equatorial Guinea', 'phone' => '240', 'length' => 9],
        'GR' => ['label' => 'Greece', 'phone' => '30', 'length' => 10],
        'GS' => ['label' => 'South Georgia and the South Sandwich Islands', 'phone' => '500', 'length' => 5],
        'GT' => ['label' => 'Guatemala', 'phone' => '502', 'length' => 8],
        'GU' => ['label' => 'Guam', 'phone' => '1-671', 'length' => 10],
        'GW' => ['label' => 'Guinea-Bissau', 'phone' => '245', 'length' => 9],
        'GY' => ['label' => 'Guyana', 'phone' => '592', 'length' => 7],
        'HK' => ['label' => 'Hong Kong', 'phone' => '852', 'length' => 8],
        'HM' => ['label' => 'Heard Island and McDonald Islands', 'phone' => '672', 'length' => 10],
        'HN' => ['label' => 'Honduras', 'phone' => '504', 'length' => 8],
        'HR' => ['label' => 'Croatia', 'phone' => '385', 'length' => 9],
        'HT' => ['label' => 'Haiti', 'phone' => '509', 'length' => 8],
        'HU' => ['label' => 'Hungary', 'phone' => '36', 'length' => 9],
        'ID' => ['label' => 'Indonesia', 'phone' => '62', 'length' => 11],
        'IE' => ['label' => 'Ireland', 'phone' => '353', 'length' => 9],
        'IL' => ['label' => 'Israel', 'phone' => '972', 'length' => 9],
        'IM' => ['label' => 'Isle of Man', 'phone' => '44', 'length' => 10],
        'IN' => ['label' => 'India', 'phone' => '91', 'length' => 10],
        'IO' => ['label' => 'British Indian Ocean Territory', 'phone' => '246', 'length' => 7],
        'IQ' => ['label' => 'Iraq', 'phone' => '964', 'length' => 10],
        'IR' => ['label' => 'Iran, Islamic Republic of', 'phone' => '98', 'length' => 11],
        'IS' => ['label' => 'Iceland', 'phone' => '354', 'length' => 7],
        'IT' => ['label' => 'Italy', 'phone' => '39', 'length' => 10],
        'JE' => ['label' => 'Jersey', 'phone' => '44', 'length' => 10],
        'JM' => ['label' => 'Jamaica', 'phone' => '1-876', 'length' => 10],
        'JO' => ['label' => 'Jordan', 'phone' => '962', 'length' => [8, 9]],
        'JP' => ['label' => 'Japan', 'phone' => '81', 'length' => 9],
        'KE' => ['label' => 'Kenya', 'phone' => '254', 'length' => 10],
        'KG' => ['label' => 'Kyrgyzstan', 'phone' => '996', 'length' => 9],
        'KH' => ['label' => 'Cambodia', 'phone' => '855', 'length' => 9],
        'KI' => ['label' => 'Kiribati', 'phone' => '686', 'length' => 8],
        'KM' => ['label' => 'Comoros', 'phone' => '269', 'length' => 7],
        'KN' => ['label' => 'Saint Kitts and Nevis', 'phone' => '1-869', 'length' => 10],
        'KP' => ['label' => "Korea, Democratic People's Republic of", 'phone' => '850', 'length' => [4, 6, 7, 13]],
        'KR' => ['label' => 'Korea, Republic of', 'phone' => '82', 'length' => [7, 8]],
        'KW' => ['label' => 'Kuwait', 'phone' => '965', 'length' => 8],
        'KY' => ['label' => 'Cayman Islands', 'phone' => '1-345', 'length' => 7],
        'KZ' => ['label' => 'Kazakhstan', 'phone' => '7', 'length' => 10],
        'LA' => ['label' => "Lao People's Democratic Republic", 'phone' => '856', 'length' => [8, 9]],
        'LB' => ['label' => 'Lebanon', 'phone' => '961', 'length' => [7, 8]],
        'LC' => ['label' => 'Saint Lucia', 'phone' => '1-758', 'length' => 7],
        'LI' => ['label' => 'Liechtenstein', 'phone' => '423', 'length' => 7],
        'LK' => ['label' => 'Sri Lanka', 'phone' => '94', 'length' => 7],
        'LR' => ['label' => 'Liberia', 'phone' => '231', 'length' => [8, 9]],
        'LS' => ['label' => 'Lesotho', 'phone' => '266', 'length' => 8],
        'LT' => ['label' => 'Lithuania', 'phone' => '370', 'length' => 8],
        'LU' => ['label' => 'Luxembourg', 'phone' => '352', 'length' => 9],
        'LV' => ['label' => 'Latvia', 'phone' => '371', 'length' => 8],
        'LY' => ['label' => 'Libya', 'phone' => '218', 'length' => 10],
        'MA' => ['label' => 'Morocco', 'phone' => '212', 'length' => 9],
        'MC' => ['label' => 'Monaco', 'phone' => '377', 'length' => 8],
        'MD' => ['label' => 'Moldova, Republic of', 'phone' => '373', 'length' => 8],
        'ME' => ['label' => 'Montenegro', 'phone' => '382', 'length' => 8],
        'MF' => ['label' => 'Saint Martin (French part)', 'phone' => '590', 'length' => 6],
        'MG' => ['label' => 'Madagascar', 'phone' => '261', 'length' => 7],
        'MH' => ['label' => 'Marshall Islands', 'phone' => '692', 'length' => 7],
        'MK' => ['label' => 'Macedonia, the Former Yugoslav Republic of', 'phone' => '389', 'length' => 8],
        'ML' => ['label' => 'Mali', 'phone' => '223', 'length' => 8],
        'MM' => ['label' => 'Myanmar', 'phone' => '95', 'length' => [7, 8, 9, 10]],
        'MN' => ['label' => 'Mongolia', 'phone' => '976', 'length' => 8],
        'MO' => ['label' => 'Macao', 'phone' => '853', 'length' => 8],
        'MP' => ['label' => 'Northern Mariana Islands', 'phone' => '1-670', 'length' => 7],
        'MQ' => ['label' => 'Martinique', 'phone' => '596', 'length' => 9],
        'MR' => ['label' => 'Mauritania', 'phone' => '222', 'length' => 8],
        'MS' => ['label' => 'Montserrat', 'phone' => '1-664', 'length' => 10],
        'MT' => ['label' => 'Malta', 'phone' => '356', 'length' => 8],
        'MU' => ['label' => 'Mauritius', 'phone' => '230', 'length' => 8],
        'MV' => ['label' => 'Maldives', 'phone' => '960', 'length' => 7],
        'MW' => ['label' => 'Malawi', 'phone' => '265', 'length' => [7, 8, 9]],
        'MX' => ['label' => 'Mexico', 'phone' => '52', 'length' => 10],
        'MY' => ['label' => 'Malaysia', 'phone' => '60', 'length' => 7],
        'MZ' => ['label' => 'Mozambique', 'phone' => '258', 'length' => 12],
        'NA' => ['label' => 'Namibia', 'phone' => '264', 'length' => 7],
        'NC' => ['label' => 'New Caledonia', 'phone' => '687', 'length' => 6],
        'NE' => ['label' => 'Niger', 'phone' => '227', 'length' => 8],
        'NF' => ['label' => 'Norfolk Island', 'phone' => '672', 'length' => 6],
        'NG' => ['label' => 'Nigeria', 'phone' => '234', 'length' => 8],
        'NI' => ['label' => 'Nicaragua', 'phone' => '505', 'length' => 8],
        'NL' => ['label' => 'Netherlands', 'phone' => '31', 'length' => 9],
        'NO' => ['label' => 'Norway', 'phone' => '47', 'length' => 8],
        'NP' => ['label' => 'Nepal', 'phone' => '977', 'length' => 10],
        'NR' => ['label' => 'Nauru', 'phone' => '674', 'length' => 7],
        'NU' => ['label' => 'Niue', 'phone' => '683', 'length' => 4],
        'NZ' => ['label' => 'New Zealand', 'phone' => '64', 'length' => [8, 9]],
        'OM' => ['label' => 'Oman', 'phone' => '968', 'length' => 8],
        'PA' => ['label' => 'Panama', 'phone' => '507', 'length' => 8],
        'PE' => ['label' => 'Peru', 'phone' => '51', 'length' => 9],
        'PF' => ['label' => 'French Polynesia', 'phone' => '689', 'length' => 8],
        'PG' => ['label' => 'Papua New Guinea', 'phone' => '675', 'length' => 8],
        'PH' => ['label' => 'Philippines', 'phone' => '63', 'length' => 10],
        'PK' => ['label' => 'Pakistan', 'phone' => '92', 'length' => 10],
        'PL' => ['label' => 'Poland', 'phone' => '48', 'length' => 9],
        'PM' => ['label' => 'Saint Pierre and Miquelon', 'phone' => '508', 'length' => 6],
        'PN' => ['label' => 'Pitcairn', 'phone' => '870', 'length' => 9],
        'PR' => ['label' => 'Puerto Rico', 'phone' => '1', 'length' => 10],
        'PS' => ['label' => 'Palestine, State of', 'phone' => '970', 'length' => 9],
        'PT' => ['label' => 'Portugal', 'phone' => '351', 'length' => 9],
        'PW' => ['label' => 'Palau', 'phone' => '680', 'length' => 7],
        'PY' => ['label' => 'Paraguay', 'phone' => '595', 'length' => 9],
        'QA' => ['label' => 'Qatar', 'phone' => '974', 'length' => 8],
        'RE' => ['label' => 'Reunion', 'phone' => '262', 'length' => 10],
        'RO' => ['label' => 'Romania', 'phone' => '40', 'length' => 10],
        'RS' => ['label' => 'Serbia', 'phone' => '381', 'length' => 9],
        'RU' => ['label' => 'Russian Federation', 'phone' => '7', 'length' => 10],
        'RW' => ['label' => 'Rwanda', 'phone' => '250', 'length' => 9],
        'SA' => ['label' => 'Saudi Arabia', 'phone' => '966', 'length' => 9],
        'SB' => ['label' => 'Solomon Islands', 'phone' => '677', 'length' => 7],
        'SC' => ['label' => 'Seychelles', 'phone' => '248', 'length' => 7],
        'SD' => ['label' => 'Sudan', 'phone' => '249', 'length' => 7],
        'SE' => ['label' => 'Sweden', 'phone' => '46', 'length' => 7],
        'SG' => ['label' => 'Singapore', 'phone' => '65', 'length' => 8],
        'SH' => ['label' => 'Saint Helena', 'phone' => '290', 'length' => 4],
        'SI' => ['label' => 'Slovenia', 'phone' => '386', 'length' => 9],
        'SJ' => ['label' => 'Svalbard and Jan Mayen', 'phone' => '47', 'length' => 8],
        'SK' => ['label' => 'Slovakia', 'phone' => '421', 'length' => 9],
        'SL' => ['label' => 'Sierra Leone', 'phone' => '232', 'length' => 8],
        'SM' => ['label' => 'San Marino', 'phone' => '378', 'length' => 10],
        'SN' => ['label' => 'Senegal', 'phone' => '221', 'length' => 9],
        'SO' => ['label' => 'Somalia', 'phone' => '252', 'length' => [8, 9]],
        'SR' => ['label' => 'Suriname', 'phone' => '597', 'length' => [6, 7]],
        'SS' => ['label' => 'South Sudan', 'phone' => '211', 'length' => 7],
        'ST' => ['label' => 'Sao Tome and Principe', 'phone' => '239', 'length' => 7],
        'SV' => ['label' => 'El Salvador', 'phone' => '503', 'length' => 8],
        'SX' => ['label' => 'Sint Maarten (Dutch part)', 'phone' => '1-721', 'length' => 10],
        'SY' => ['label' => 'Syrian Arab Republic', 'phone' => '963', 'length' => 7],
        'SZ' => ['label' => 'Swaziland', 'phone' => '268', 'length' => 8],
        'TC' => ['label' => 'Turks and Caicos Islands', 'phone' => '1-649', 'length' => 10],
        'TD' => ['label' => 'Chad', 'phone' => '235', 'length' => 6],
        'TF' => ['label' => 'French Southern Territories', 'phone' => '262', 'length' => 10],
        'TG' => ['label' => 'Togo', 'phone' => '228', 'length' => 8],
        'TH' => ['label' => 'Thailand', 'phone' => '66', 'length' => 9],
        'TJ' => ['label' => 'Tajikistan', 'phone' => '992', 'length' => 9],
        'TK' => ['label' => 'Tokelau', 'phone' => '690', 'length' => 5],
        'TL' => ['label' => 'Timor-Leste', 'phone' => '670', 'length' => 7],
        'TM' => ['label' => 'Turkmenistan', 'phone' => '993', 'length' => 8],
        'TN' => ['label' => 'Tunisia', 'phone' => '216', 'length' => 8],
        'TO' => ['label' => 'Tonga', 'phone' => '676', 'length' => 5],
        'TR' => ['label' => 'Turkey', 'phone' => '90', 'length' => 11],
        'TT' => ['label' => 'Trinidad and Tobago', 'phone' => '1-868', 'length' => 7],
        'TV' => ['label' => 'Tuvalu', 'phone' => '688', 'length' => 5],
        'TW' => ['label' => 'Taiwan, Province of China', 'phone' => '886', 'length' => 9],
        'TZ' => ['label' => 'United Republic of Tanzania', 'phone' => '255', 'length' => 7],
        'UA' => ['label' => 'Ukraine', 'phone' => '380', 'length' => 9],
        'UG' => ['label' => 'Uganda', 'phone' => '256', 'length' => 7],
        'US' => ['label' => 'United States', 'phone' => '1', 'length' => 10],
        'UY' => ['label' => 'Uruguay', 'phone' => '598', 'length' => 8],
        'UZ' => ['label' => 'Uzbekistan', 'phone' => '998', 'length' => 9],
        'VA' => ['label' => 'Holy See (Vatican City State)', 'phone' => '379', 'length' => 10],
        'VC' => ['label' => 'Saint Vincent and the Grenadines', 'phone' => '1-784', 'length' => 7],
        'VE' => ['label' => 'Venezuela', 'phone' => '58', 'length' => 7],
        'VG' => ['label' => 'British Virgin Islands', 'phone' => '1-284', 'length' => 7],
        'VI' => ['label' => 'US Virgin Islands', 'phone' => '1-340', 'length' => 10],
        'VN' => ['label' => 'Vietnam', 'phone' => '84', 'length' => 9],
        'VU' => ['label' => 'Vanuatu', 'phone' => '678', 'length' => 5],
        'WF' => ['label' => 'Wallis and Futuna', 'phone' => '681', 'length' => 6],
        'WS' => ['label' => 'Samoa', 'phone' => '685', 'length' => [5, 6, 7]],
        'XK' => ['label' => 'Kosovo', 'phone' => '383', 'length' => 8],
        'YE' => ['label' => 'Yemen', 'phone' => '967', 'length' => 9],
        'YT' => ['label' => 'Mayotte', 'phone' => '262', 'length' => 9],
        'ZA' => ['label' => 'South Africa', 'phone' => '27', 'length' => 9],
        'ZM' => ['label' => 'Zambia', 'phone' => '260', 'length' => 9],
        'ZW' => ['label' => 'Zimbabwe', 'phone' => '263', 'length' => 9],
    ];
    public static $country_codes = [
        "AF" => "Afghanistan (+93)",
        "AL" => "Albania (+355)",
        "DZ" => "Algeria (+213)",
        "AS" => "American Samoa (+1684)",
        "AD" => "Andorra (+376)",
        "AO" => "Angola (+244)",
        "AI" => "Anguilla (+1264)",
        "AG" => "Antigua and Barbuda (+1268)",
        "AR" => "Argentina (+54)",
        "AM" => "Armenia (+374)",
        "AW" => "Aruba (+297)",
        "AU" => "Australia (+61)",
        "AT" => "Austria (+43)",
        "AZ" => "Azerbaijan (+994)",
        "BS" => "Bahamas (+1242)",
        "BH" => "Bahrain (+973)",
        "BD" => "Bangladesh (+880)",
        "BB" => "Barbados (+1246)",
        "BY" => "Belarus (+375)",
        "BE" => "Belgium (+32)",
        "BZ" => "Belize (+501)",
        "BJ" => "Benin (+229)",
        "BM" => "Bermuda (+1441)",
        "BT" => "Bhutan (+975)",
        "BO" => "Bolivia (+591)",
        "BQ" => "Bonaire St Eustatius And Saba (+5993)",
        "BA" => "Bosnia and Herzegovina (+387)",
        "BW" => "Botswana (+267)",
        "BR" => "Brazil (+55)",
        "IO" => "British Indian Ocean Territory (+246)",
        "BN" => "Brunei Darussalam (+673)",
        "BG" => "Bulgaria (+359)",
        "BF" => "Burkina Faso (+226)",
        "BI" => "Burundi (+257)",
        "KH" => "Cambodia (+855)",
        "CM" => "Cameroon (Republic of) (+237)",
        "CA" => "Canada (+1)",
        "CV" => "Cape Verde (Republic of) (+238)",
        "KY" => "Cayman Islands (+1345)",
        "CF" => "Central African Republic (+236)",
        "TD" => "Chad (+235)",
        "CL" => "Chile (+56)",
        "CN" => "China (+86)",
        "CX" => "Christmas Island (+61)",
        "CC" => "Cocos Islands (+61)",
        "CO" => "Colombia (+57)",
        "KM" => "Comoros (+269)",
        "CD" => "Congo (Democratic Republic of) (+243)",
        "CG" => "Congo Brazzaville (+242)",
        "CK" => "Cook Islands (+682)",
        "CR" => "Costa Rica (+506)",
        "CI" => "Cote d'Ivoire (+225)",
        "HR" => "Croatia (+385)",
        "CU" => "Cuba (+53)",
        "CW" => "Curaçao (+5999)",
        "CY" => "Cyprus (+357)",
        "CZ" => "Czech Republic (+420)",
        "DK" => "Denmark (+45)",
        "DJ" => "Djibouti (+253)",
        "DM" => "Dominica (+1767)",
        "DO" => "Dominican Republic (+1809)",
        "EC" => "Ecuador (+593)",
        "EG" => "Egypt (+20)",
        "SV" => "El Salvador (+503)",
        "GQ" => "Equatorial Guinea (+240)",
        "ER" => "Eritrea (+291)",
        "EE" => "Estonia (+372)",
        "ET" => "Ethiopia (+251)",
        "FK" => "Falkland Islands (+500)",
        "FO" => "Faroe Islands (+298)",
        "FJ" => "Fiji (+679)",
        "FI" => "Finland (+358)",
        "FR" => "France (+33)",
        "GF" => "French Guiana (+594)",
        "PF" => "French Polynesia (+689)",
        "GA" => "Gabon (+241)",
        "GM" => "Gambia (+220)",
        "GE" => "Georgia (+995)",
        "DE" => "Germany (+49)",
        "GH" => "Ghana (+233)",
        "GI" => "Gibraltar (+350)",
        "GR" => "Greece (+30)",
        "GL" => "Greenland (+299)",
        "GD" => "Grenada (+1473)",
        "GP" => "Guadeloupe (+590)",
        "GU" => "Guam (+1671)",
        "GT" => "Guatemala (+502)",
        "GN" => "Guinea (+224)",
        "GW" => "Guinea Bissau (+245)",
        "GY" => "Guyana (+592)",
        "HT" => "Haiti (+509)",
        "HN" => "Honduras (+504)",
        "HK" => "Hong Kong, China (+852)",
        "HU" => "Hungary (+36)",
        "IS" => "Iceland (+354)",
        "IN" => "India (+91)",
        "ID" => "Indonesia (+62)",
        "IR" => "Iran (+98)",
        "IQ" => "Iraq (+964)",
        "IE" => "Ireland (Republic of) (+353)",
        "IM" => "Isle Of Man (+44)",
        "IL" => "Israel (+972)",
        "IT" => "Italy (+39)",
        "JM" => "Jamaica (+1876)",
        "JP" => "Japan (+81)",
        "JO" => "Jordan (+962)",
        "KZ" => "Kazakhstan (+7)",
        "KE" => "Kenya (+254)",
        "KI" => "Kiribati (+686)",
        "KP" => "Korea (Democratic People's Republic Of) (+850)",
        "KR" => "Korea (Republic of) (+82)",
        "XK" => "Kosovo (+383)",
        "KW" => "Kuwait (+965)",
        "KG" => "Kyrgyzstan (+996)",
        "LA" => "Lao (People's Democratic Republic) (+856)",
        "LV" => "Latvia (+371)",
        "LB" => "Lebanon (+961)",
        "LS" => "Lesotho (+266)",
        "LR" => "Liberia (+231)",
        "LY" => "Libya (+218)",
        "LI" => "Liechtenstein (+423)",
        "LT" => "Lithuania (+370)",
        "LU" => "Luxembourg (+352)",
        "MO" => "Macao, China (+853)",
        "MK" => "Macedonia - Fyrom (+389)",
        "MG" => "Madagascar Island (+261)",
        "MW" => "Malawi (+265)",
        "MY" => "Malaysia (+60)",
        "MV" => "Maldives Islands (+960)",
        "ML" => "Mali (+223)",
        "MT" => "Malta (+356)",
        "MH" => "Marshall Islands (+692)",
        "MQ" => "Martinique (+596)",
        "MR" => "Mauritania (+222)",
        "MU" => "Mauritius Island (+230)",
        "YT" => "Mayotte (+262)",
        "MX" => "Mexico (+52)",
        "FM" => "Micronesia (+691)",
        "MD" => "Moldova (+373)",
        "MC" => "Monaco (+377)",
        "MN" => "Mongolia (+976)",
        "ME" => "Montenegro (+382)",
        "MS" => "Montserrat (+1664)",
        "MA" => "Morocco (+212)",
        "MZ" => "Mozambique (+258)",
        "MM" => "Myanmar (+95)",
        "NA" => "Namibia (+264)",
        "NR" => "Nauru (+674)",
        "NP" => "Nepal (+977)",
        "NL" => "Netherlands (+31)",
        "NC" => "New Caledonia (+687)",
        "NZ" => "New Zealand (+64)",
        "NI" => "Nicaragua (+505)",
        "NE" => "Niger (+227)",
        "NG" => "Nigeria (+234)",
        "NU" => "Niue (+683)",
        "NF" => "Norfolk Island (+6723)",
        "MP" => "Northern Mariana Islands (+1670)",
        "NO" => "Norway (+47)",
        "OM" => "Oman (+968)",
        "PK" => "Pakistan (+92)",
        "PW" => "Palau Islands (+680)",
        "PS" => "Palestine - State Of (+970)",
        "PA" => "Panama (+507)",
        "PG" => "Papua New Guinea (+675)",
        "PY" => "Paraguay (+595)",
        "PE" => "Peru (+51)",
        "PH" => "Philippines (+63)",
        "PL" => "Poland (+48)",
        "PT" => "Portugal (+351)",
        "PR" => "Puerto Rico (+1)",
        "QA" => "Qatar (+974)",
        "RE" => "Reunion Island (+262)",
        "RO" => "Romania (+40)",
        "RU" => "Russia (+7)",
        "RW" => "Rwanda (+250)",
        "WS" => "Samoa (Independent State of) (+685)",
        "SM" => "San Marino (+378)",
        "ST" => "Sao Tome and Principe Islands (+239)",
        "SA" => "Saudi Arabia (+966)",
        "SN" => "Senegal (+221)",
        "RS" => "Serbia (+381)",
        "SC" => "Seychelles Islands (+248)",
        "SL" => "Sierra Leone (+232)",
        "SG" => "Singapore (+65)",
        "SX" => "Sint Maarten (+599)",
        "SK" => "Slovakia (+421)",
        "SI" => "Slovenia (+386)",
        "SB" => "Solomon Islands (+677)",
        "SO" => "Somalia (+252)",
        "ZA" => "South Africa (+27)",
        "SS" => "South Sudan (+211)",
        "ES" => "Spain (+34)",
        "LK" => "Sri Lanka (+94)",
        "SH" => "St. Helena Island (+290)",
        "KN" => "St. Kitts (+1869)",
        "LC" => "St. Lucia (+1758)",
        "PM" => "St. Pierre and Miquelon (+508)",
        "VC" => "St. Vincent (+1784)",
        "SD" => "Sudan (+249)",
        "SR" => "Suriname (+597)",
        "SZ" => "Swaziland (+268)",
        "SE" => "Sweden (+46)",
        "CH" => "Switzerland (+41)",
        "SY" => "Syrian Arab Republic (+963)",
        "TW" => "Taiwan, China (+886)",
        "TJ" => "Tajikistan (+992)",
        "TZ" => "Tanzania (United Republic) (+255)",
        "TH" => "Thailand (+66)",
        "TL" => "Timor Leste (+670)",
        "TG" => "Togo (+228)",
        "TK" => "Tokelau (+690)",
        "TO" => "Tonga (+676)",
        "TT" => "Trinidad and Tobago (+1868)",
        "TN" => "Tunisia (+216)",
        "TR" => "Turkey (+90)",
        "TM" => "Turkmenistan (+993)",
        "TC" => "Turks and Caicos Islands (+1649)",
        "TV" => "Tuvalu (+688)",
        "UG" => "Uganda (+256)",
        "UA" => "Ukraine (+380)",
        "AE" => "United Arab Emirates (+971)",
        "GB" => "United Kingdom (+44)",
        "US" => "United States Of America (+1)",
        "UY" => "Uruguay (+598)",
        "UZ" => "Uzbekistan (+998)",
        "VU" => "Vanuatu (+678)",
        "VA" => "Vatican (+39)",
        "VE" => "Venezuela (+58)",
        "VN" => "Vietnam (+84)",
        "VG" => "Virgin Islands-British (+1284)",
        "VI" => "Virgin Islands-United States (+1340)",
        "WF" => "Wallis and Futuna Islands (+681)",
        "EH" => "Western Sahara (+212)",
        "YE" => "Yemen Republic (+967)",
        "ZM" => "Zambia (+260)",
        "ZW" => "Zimbabwe (+263)",
    ];
}
