<?php

class TAccountCheckerXbox extends TAccountChecker
{
    public static function GetAccountChecker($accountInfo)
    {
        require_once __DIR__ . '/TAccountCheckerXboxSelenium.php';

        return new TAccountCheckerXboxSelenium();
    }

    public function LoadLoginForm()
    {
        $this->http->removeCookies();

        if (!$this->http->getURL('http://rewards.xbox.com/sign-in')) {
            $this->checkErrors();
        }

        if (preg_match_all('/<input type="hidden" name="([^\"]*)"[^>]*value="([^\"]*)"/ims', $this->http->Response['body'], $matches)) {
            for ($i = 0; $i < count($matches[0]); $i++) {
                $this->http->Form[$matches[1][$i]] = $matches[2][$i];
            }
        }
        $this->http->Form['type'] = '11';
        $this->http->Form['LoginOptions'] = '3';
        $this->http->Form['NewUser'] = '1';
        $this->http->Form['MEST'] = '';
        $this->http->Form['PPSX'] = 'Pass';
        $this->http->Form['idsbho'] = '1';
        $this->http->Form['PwdPad'] = '';
        $this->http->Form['sso'] = '';
        $this->http->Form['i1'] = '';
        $this->http->Form['i2'] = '1';
        $this->http->Form['i3'] = '6313';
        $this->http->Form['i4'] = '';
        $this->http->Form['i12'] = '1';
        $this->http->Form['login'] = $this->AccountFields['Login'];
        $this->http->Form['passwd'] = $this->AccountFields['Pass'];
        $url = $this->http->FindPreg('/urlPost:\s*\'([^\']*)\'/ims');

        if (isset($url) && !empty($url)) {
            $this->http->FormURL = 'https://login.live.com/ppsecure/post.srf?' . urldecode($url);
        } else {
            return false;
        }
        $this->http->PostForm();

        if ($this->http->FindPreg("/Help us protect your account/ims")) {
            $this->AskQuestion('To continue, enter the code generated by your authenticator app');
        }

        $this->checkErrors();

        if (!$this->http->ParseForm('fmHF')) {
            return $this->checkErrors();
        }
        $this->http->PostForm();

        $email = $this->http->FindSingleNode("(//select[@id = 'iProofOptions']/option[contains(@value, '@')])[1]");

        if (($this->http->FindPreg("/You haven\'t signed in from this location recently/ims")
            || $this->http->FindPreg("/but we need to make sure you can receive a security code/ims"))
            && isset($email)) {
            $this->http->Log("Sent code to {$email}");
            $this->http->Form = [];
            $this->http->FormURL = 'https://account.live.com/SendSmsOTT';
            $this->http->Form['action'] = 'FamiliarLocationEasy';
            $this->http->Form['channel'] = 'Email';
            $this->http->Form['cxt'] = $this->http->FindPreg("/sContext:\s*\'([^\']+)/ims");
            $this->http->Form['action'] = $this->http->FindPreg("/sAction:\s*\'([^\']+)/ims");
            $this->http->Form['netid'] = $this->http->FindPreg("/sNetId:\s*\'([^\']+)/ims");
            $this->http->Form['destination'] = $this->http->FindPreg("/sProofData:\s*\'([^\']+)/ims");
            $this->http->PostForm();
            $this->AskQuestion("You need to verify your account. Please enter the code which was sent to the following email: {$email}"); /*checked*/
        }

        $this->tryLogin();

        if ($this->http->ParseForm("idForm")) {
            $this->http->PostForm();
        }
        $this->checkErrors();

        if (!$this->http->ParseForm('PostForm')) {
            return false;
        }

        return true;
    }

    public function tryLogin()
    {
        if ($this->http->ParseForm('fmHF')) {
            $this->http->PostForm();
            $this->tryLogin();
        }
    }

    public function ProcessStep($step)
    {
        if ($this->http->ParseForm("frmProofs")) {
            $this->http->Log("entering code");
            $this->http->Form['iProofOptions'] = $this->http->FindSingleNode("(//select[@id = 'iProofOptions']/option[contains(@value, '@')]/@value)[1]");
            $this->http->Form['iOttText'] = $this->Answers[$this->Question];
        // iPublicKey
        } else {
            $this->http->Form['AddFD'] = '1';
            $this->http->Form['PPFT'] = $this->http->FindPreg("/sFT:\'([^\']+)/ims");
            $this->http->Form['SentProofID'] = '16484607535286462268';
            $this->http->Form['i14'] = '801';
            $this->http->Form['i15'] = '1031';
            $this->http->Form['i16'] = '2047';
            $this->http->Form['i17'] = '0';
            $this->http->Form['i18'] = '__SA_WLStrings|1,__SAWorkflow|1,';
            $this->http->Form['i2'] = '16';
            $this->http->Form['i3'] = '12932';
            $this->http->Form['i7'] = '0';
            $this->http->Form['AddFD'] = '1';
            $this->http->Form['login'] = $this->AccountFields['Login'];
            $this->http->Form["otc"] = $this->Answers[$this->Question];
            $this->http->Form['sacxt'] = '1';
            $this->http->Form['type'] = '19';

            $url = $this->http->FindPreg('/urlPost:\s*\'([^\']*)\'/ims');

            if (isset($url) && !empty($url)) {
                $this->http->FormURL = 'https://login.live.com/ppsecure/post.srf?' . urldecode($url);
            } else {
                return false;
            }
        }

        if (!$this->http->PostForm()) {
            return false;
        }

        $this->tryLogin();

        if ($this->http->ParseForm("PostForm")) {
            $this->http->PostForm();
        }

        if ($this->http->FindPreg("/Help us protect your account/ims")) {
            $this->AskQuestion('To continue, enter the code generated by your authenticator app');
        }

        return true;
    }

    public function checkErrors()
    {
        //# You've tried to sign in too many times with an incorrect email address or password.
        if ($message = $this->http->FindPreg("/(Enter your password and the characters in the picture correctly)/ims")) {
            throw new CheckException("You've tried to sign in too many times with an incorrect email address or password.", ACCOUNT_INVALID_PASSWORD);
        }

        if ($message = $this->http->FindPreg("/sErrTxt:\'([^\<]+)/ims")) {
            throw new CheckException($message, ACCOUNT_INVALID_PASSWORD);
        }

        if ($message = $this->http->FindPreg("/sErrTxt:\"([^\"<]+)/ims")) {
            throw new CheckException($message, ACCOUNT_INVALID_PASSWORD);
        }
        //# Confirm email address
        if ($message = $this->http->FindPreg('/Verify your email address/ims')) {
            throw new CheckException($message, ACCOUNT_INVALID_PASSWORD);
        }
        //# Need create a new password
        if ($message = $this->http->FindPreg('/(Before you can sign in to Windows Live, you need to create a new password.)/ims')) {
            throw new CheckException($message, ACCOUNT_INVALID_PASSWORD);
        }

        if ($message = $this->http->FindSingleNode("//td[@class='cssError']")) {
            throw new CheckException($message, ACCOUNT_INVALID_PASSWORD);
        }
        //# Account blocked
        if ($message = $this->http->FindPreg("/Your account has been temporarily blocked/ims")) {
            throw new CheckException($message, ACCOUNT_LOCKOUT);
        }

        if ($message = $this->http->FindSingleNode('//div[contains(text(),"Your account has been blocked")]')) {
            throw new CheckException($message, ACCOUNT_LOCKOUT);
        }
        //# We need you to add some security info for your account
        if ($message = $this->http->FindSingleNode("//h3[contains(text(), 'We need you to add some security info for your account')]")) {
            throw new CheckException($message, ACCOUNT_PROVIDER_ERROR);
        }
        //# It looks like someone else might be using your account
        if ($message = $this->http->FindSingleNode("//div[contains(text(), 'It looks like someone else might be using your account')]")) {
            throw new CheckException("Please update your profile", ACCOUNT_PROVIDER_ERROR);
        }
        //# You haven't signed in from this location recently.
        if ($message = $this->http->FindPreg("/(To help protect your account, we want to make sure this is you. Let us know how we should verify your account. If none of the options listed work for you, you can still access your account from a location you've used recently\.)/ims")) {
            throw new CheckException($message, ACCOUNT_PROVIDER_ERROR);
        }

        if ($message = $this->http->FindSingleNode("//p[@id = 'idErrorMsg']")) {
            throw new CheckException($message, ACCOUNT_PROVIDER_ERROR);
        }

        //# Call us overprotective, but we need to verify that >email< is yours
        if ($this->http->FindPreg('/(A password isn\'t enough)/ims')
            || $this->http->FindSingleNode("//p[contains(text(), 'Before you can continue, you need to check your inbox for a message from the Microsoft account team')]")
            || $this->http->FindPreg("/Passwords can be forgotten or stolen\.\s*Just in case, add security info now to help you get back into your account if something goes wrong\./ims")) {
            throw new CheckException("Xbox website is asking you to update your profile,
            until you do so we would not be able to retrieve your account information.", ACCOUNT_PROVIDER_ERROR);
        }

        //# Maintenance
        if ($message = $this->http->FindSingleNode("//*[contains(text(), 'currently unavailable')]")) {
            throw new CheckException($message, ACCOUNT_PROVIDER_ERROR);
        }
        //# Xbox LIVE Rewards is currently undergoing a short maintenance period
        if ($message = $this->http->FindPreg("/(Xbox LIVE Rewards is currently undergoing a short maintenance period[^<]+)/ims")) {
            throw new CheckException($message, ACCOUNT_PROVIDER_ERROR);
        }
        //# Our server is having a problem. We&#39;re working to fix it as soon as we can, so try again in a few minutes.
        if ($message = $this->http->FindPreg("/(Our server is having a problem. We\&\#39;re working to fix it as soon as we can, so try again in a few minutes.)/ims")) {
            throw new CheckException($message, ACCOUNT_PROVIDER_ERROR);
        }
        //# An Error Has Occurred
        if ($message = $this->http->FindPreg("/(An Error Has Occurred\.)/ims")) {
            throw new CheckException($message, ACCOUNT_PROVIDER_ERROR);
        }
        //# An error occurred while processing your request
        if ($message = $this->http->FindPreg("/(An error occurred while processing your request\.)/ims")) {
            throw new CheckException($message, ACCOUNT_PROVIDER_ERROR);
        }

        return false;
    }

    public function Login()
    {
        if (!$this->http->PostForm()) {
            return $this->checkErrors();
        }

        if ($this->http->FindPreg('/(for free members upgrading)/ims')) {
            throw new CheckException("Xbox website is asking you to update your profile,
            until you do so we would not be able to retrieve your account information.", ACCOUNT_PROVIDER_ERROR);
        }

        if ($message = $this->http->FindSingleNode('//div[@id="first_time_content"]')) {
            throw new CheckException("We've received your request to become an Xbox LIVE Rewards Member. It'll take about 2 days for us to process your request, so sit tight. We'll shoot you an email when your account is active and you can begin racking up Xbox LIVE Rewards", ACCOUNT_PROVIDER_ERROR);
        }

        if ($message = $this->http->FindPreg("/We want to make sure that you stay informed/ims")) {
            throw new CheckException('There is a pending question in your profile that needs to be answered before we
            will be able to retrieve the balance information.', ACCOUNT_PROVIDER_ERROR);
        }

        //# User is not a member of loyalty program
        if ($message = $this->http->FindSingleNode("//a[contains(text(), 'Before becoming an Xbox Live Rewards member')]")
            || $this->http->currentUrl() == "http://rewards.xbox.com/join-now/") {
            throw new CheckException(self::NOT_MEMBER_MSG, ACCOUNT_PROVIDER_ERROR);
        }

        //# Access ia allowed
        if ($this->http->FindSingleNode("//a[contains(@href, 'sign-out')]/@href")) {
            return true;
        }

        return $this->checkErrors();
    }

    public function Parse()
    {
        $this->http->GetURL("https://rewards.xbox.com/myrewards/");
        //# Balance - You have ... Credits
        $this->SetBalance($this->http->FindSingleNode("//p[@class = 'credits_current']", null, true, '/You have ([\d\.\,]+) Credit/ims'));
        //# Username
        $this->SetProperty("Name", $this->http->FindSingleNode("//span[@class = 'header_gamertag']"));
        //# Member Since
        $this->SetProperty("MemberSince", $this->http->FindSingleNode("//span[contains(text(), 'Rewards member since:')]/parent::h2", null, true, "/Member\s*since\s*:\s*([^<]+)/ims"));
        //# My VIP Status
        $status = $this->http->FindSingleNode("//span[contains(text(), 'My VIP Status:')]/parent::h2", null, true, "/VIP\s*Status\s*:\s*([^<]+)/ims");

        if (strtolower($status) != 'unlock now') {
            $this->SetProperty("MyVIPStatus", $status);
        }
        //# Total Pending Rewards Credits
        $this->SetProperty("PointsPending", $this->http->FindSingleNode("//h3[@id = 'total_pending']/span"));
        //# Lifetime Credits Earned
        $this->SetProperty("LifetimeCreditsEarned", $this->http->FindSingleNode("//h3[contains(text(), 'Lifetime Credits Earned:')]/span"));
        //# Lifetime Microsoft Points Earned
        $this->SetProperty("LifetimeMicrosoftPointsEarned", $this->http->FindSingleNode("//h3[contains(text(), 'Lifetime Microsoft Points Earned:')]/span"));
        //# Next Deposit Date
        $this->SetProperty("NextDepositDate", $this->http->FindSingleNode("//strong[contains(text(), 'Next Deposit Date')]/parent::p", null, true, '/Next\s*Deposit\s*Date\s*([^<]+)/ims'));
        //# My VIP Badges
        $this->SetProperty("MyVIPBadges", count($this->http->FindNodes("//div[@class = 'badgeSlider_slide']/div[@class = 'badge_block']")));
        //# My Achievement Points Earned Last Month
        $this->SetProperty("EarnedLastMonth", $this->http->FindSingleNode("//span[contains(text(), 'Earned Last Month')]/parent::li", null, true, '/Earned\s*Last\s*Month\s*:\s*([^<]+)/ims'));

        if ($this->ErrorCode == ACCOUNT_ENGINE_ERROR) {
            if ($message = $this->http->FindSingleNode("//p[contains(text(), 'Right now, Xbox Live Rewards is evolving to better reward you for doing the things you love on Xbox Live')]")) {
                throw new CheckException($message, ACCOUNT_PROVIDER_ERROR);
            }
        }// if ($this->ErrorCode == ACCOUNT_ENGINE_ERROR)

        //# SubAccount - Xbox Game Score
        if ($link = $this->http->FindSingleNode("//a[contains(text(), 'Xbox.com')]/@href")) {
            $this->http->Log("Go to Xbox.com");
            $this->http->GetURL($link);
            // Sign in
            if ($link = $this->http->FindSingleNode("//a[contains(text(), 'Sign In')]/@href")) {
                $this->http->Log("Sign In Xbox.com");
                $this->http->GetURL($link);

                if ($this->http->ParseForm("fmHF")) {
                    $this->http->PostForm();
                }
            }// if ($link = $this->http->FindSingleNode("//a[contains(text(), 'Sign In')]/@href"))
            $XBXMChg = $this->http->getCookieByName("XBXMChg");
            $XBXNChg = $this->http->getCookieByName("XBXNChg");
            $XBXSPChg = $this->http->getCookieByName("XBXSPChg");
            $XBXChg = $this->http->getCookieByName("XBXChg");

            if (isset($XBXMChg, $XBXNChg, $XBXSPChg, $XBXChg)) {
                $this->http->GetURL("https://live.xbox.com/Handlers/ShellData.ashx?culture=en-US&XBXMChg={$XBXMChg}&XBXNChg={$XBXNChg}&XBXSPChg={$XBXSPChg}&XBXChg={$XBXChg}&_=" . time() . date("B"));
            }
            $response = preg_replace(["/^\s*processShellData\(/ims", "/\);$/ims"], '', $this->http->Response['body']);
            $response = json_decode($response);
            $this->http->Log("<pre>" . var_export($response, true) . "</pre>", false);
            // Game Score
            if (isset($response->gamerscore)) {
                $balance = $response->gamerscore;
            }

            if (isset($balance)) {
                $subAccounts[] = [
                    'Code'        => 'xboxGameScore',
                    'DisplayName' => "Xbox Game Score",
                    'Balance'     => $balance,
                    'XboxStatus'  => (isset($response->tiertext)) ? $response->tiertext : '',
                ];
            }// for ($i = 0; $i < $nodes->length; $i++)

            if (isset($subAccounts)) {
                //# Set Sub Accounts
                $this->SetProperty("CombineSubAccounts", false);
                $this->http->Log("Total subAccounts: " . count($subAccounts));
                //# Set SubAccounts Properties
                $this->SetProperty("SubAccounts", $subAccounts);
            }// if(isset($subAccounts))
        }// if ($link = $this->http->FindSingleNode("//a[contains(text(), 'Xbox.com')]/@href"))
    }
}
